### ISSUE TITLE
Pango GObject-Introspection and record type issue

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#1004]
I created the pango loader based on GObject-Introspection (very basic) : 

```ruby
require "gobject-introspection"
require "cairo"

base_dir = Pathname.new(__FILE__).dirname.dirname.expand_path
vendor_dir = base_dir + "vendor" + "local"
vendor_bin_dir = vendor_dir + "bin"
GLib.prepend_dll_path(vendor_bin_dir)
vendor_girepository_dir = vendor_dir + "lib" + "girepository-1.0"
GObjectIntrospection.prepend_typelib_path(vendor_girepository_dir)

module Pango
  LOG_DOMAIN = "Pango"
  GLib::Log.set_log_domain(LOG_DOMAIN)

  class Loader < GObjectIntrospection::Loader
  end
  loader = Loader.new(self)
  loader.load("Pango")
end
```

When I try it, it fails with this message : 

```
/home/cedlemo/Projets/Ruby/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:137:in `load_struct_info': uninitialized constant Pango::Attr (NameError)
	from /home/cedlemo/Projets/Ruby/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:60:in `load_info'
	from /home/cedlemo/Projets/Ruby/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:43:in `block in load'
	from /home/cedlemo/Projets/Ruby/ruby-gnome2/gobject-introspection/lib/gobject-introspection/repository.rb:27:in `block (2 levels) in each'
	from /home/cedlemo/Projets/Ruby/ruby-gnome2/gobject-introspection/lib/gobject-introspection/repository.rb:26:in `times'
	from /home/cedlemo/Projets/Ruby/ruby-gnome2/gobject-introspection/lib/gobject-introspection/repository.rb:26:in `block in each'
	from /home/cedlemo/Projets/Ruby/ruby-gnome2/gobject-introspection/lib/gobject-introspection/repository.rb:25:in `each'
	from /home/cedlemo/Projets/Ruby/ruby-gnome2/gobject-introspection/lib/gobject-introspection/repository.rb:25:in `each'
	from /home/cedlemo/Projets/Ruby/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:42:in `load'
	from /home/cedlemo/Projets/Ruby/ruby-gnome2/pango/lib/pango.rb:34:in `<module:Pango>'
	from /home/cedlemo/Projets/Ruby/ruby-gnome2/pango/lib/pango.rb:27:in `<top (required)>'
```

In the gir file, the element that cause the error is this one : 

```
    <record name="AttrClass" c:type="PangoAttrClass">
      <doc xml:space="preserve">The #PangoAttrClass structure stores the type and operations for
a particular type of attribute. The functions in this structure should
not be called directly. Instead, one should use the wrapper functions
provided for #PangoAttribute.</doc>
      <field name="type" writable="1">
        <doc xml:space="preserve">the type ID for this attribute</doc>
        <type name="AttrType" c:type="PangoAttrType"/>
      </field>
      <field name="copy" introspectable="0">
        <callback name="copy" introspectable="0">
          <return-value>
            <type name="Attribute" c:type="PangoAttribute*"/>
          </return-value>
          <parameters>
            <parameter name="attr" transfer-ownership="none">
              <type name="Attribute" c:type="const PangoAttribute*"/>
            </parameter>
          </parameters>
        </callback>
      </field>
      <field name="destroy">
        <callback name="destroy">
          <return-value transfer-ownership="none">
            <type name="none" c:type="void"/>
          </return-value>
          <parameters>
            <parameter name="attr" transfer-ownership="none">
              <type name="Attribute" c:type="PangoAttribute*"/>
            </parameter>
          </parameters>
        </callback>
      </field>
      <field name="equal">
        <callback name="equal">
          <return-value transfer-ownership="none">
            <type name="gboolean" c:type="gboolean"/>
          </return-value>
          <parameters>
            <parameter name="attr1" transfer-ownership="none">
              <type name="Attribute" c:type="const PangoAttribute*"/>
            </parameter>
            <parameter name="attr2" transfer-ownership="none">
              <type name="Attribute" c:type="const PangoAttribute*"/>
            </parameter>
          </parameters>
        </callback>
      </field>
    </record>
```

Should I create a rule in `GI::Loader#load_struct_info` in order to not parse this element ?

**Comment by kou** [comment]
Oops.  It's a bug of `GI::Loader`.

**Comment by cedlemo** [comment]
thanks @kou,

All the structures that are named with the "Class" pattern at the end are registred as "record" element in the gir file. Now that I see what you code do, it seems that in the yard-gobject-introspection plugin, I will have to parse the "record" elements,  get the methods defined in it, remove the "Class" pattern of the name of the element that will correspond to the class in which I will add the methods.  

Am I right ?

**Comment by kou** [comment]
(Maybe) Yes!

**Comment by cedlemo** [comment]
@kou, I have an issue because there are no constructor for Pango attributes for example. With the loader I show you, each old tests fail with : 

```
Error: test_end_index(TestAttribute): ArgumentError: wrong number of arguments (given 1, expected 0)
/home/cedlemo/Projets/Ruby/ruby-gnome2/pango/test/test-attribute.rb:5:in `initialize'
/home/cedlemo/Projets/Ruby/ruby-gnome2/pango/test/test-attribute.rb:5:in `new'
/home/cedlemo/Projets/Ruby/ruby-gnome2/pango/test/test-attribute.rb:5:in `setup'
============================================================================================================================================================================================
E
============================================================================================================================================================================================
Error: test_start_index(TestAttribute): ArgumentError: wrong number of arguments (given 1, expected 0)
/home/cedlemo/Projets/Ruby/ruby-gnome2/pango/test/test-attribute.rb:5:in `initialize'
/home/cedlemo/Projets/Ruby/ruby-gnome2/pango/test/test-attribute.rb:5:in `new'
/home/cedlemo/Projets/Ruby/ruby-gnome2/pango/test/test-attribute.rb:5:in `setup'
==========================================================================================
```

the corresponding line is : 

       @attribute = Pango::AttrLanguage.new(Pango::Language.default)

I have tested and the `Pango::Language.default` works.

**Comment by kou** [comment]
We need to define our convenient constructors for raw structs (not `GType`-ed structs) if they are needed.

For example:

```ruby
module Pango
  class AttrLanguage
    alias_method :initialize_raw, :initialize
    def initialize(language)
      initialize_raw
      self.value = language
    end
end
```

**Comment by cedlemo** [comment]
@kou, in order to make it work, we should support interfaces in `rb_gi_field_info_set_field_raw` I was able to make it works with the following modifications (not really clean sorry) :

```diff
diff --git a/gobject-introspection/ext/gobject-introspection/rb-gi-field-info.c b/gobject-introspection/ext/gobject-introspection/rb-gi-field-info.c
index f25716f2a..bd289cd5a 100644
--- a/gobject-introspection/ext/gobject-introspection/rb-gi-field-info.c
+++ b/gobject-introspection/ext/gobject-introspection/rb-gi-field-info.c
@@ -158,6 +158,30 @@ rb_gi_field_info_set_field_raw(GIFieldInfo *info, gpointer memory,
             G_STRUCT_MEMBER(gchar *, memory, offset) = field_value.v_string;
             succeeded = TRUE;
         }
+        if (type_tag == GI_TYPE_TAG_INTERFACE) {
+            GIBaseInfo *interface_info;
+            GIInfoType interface_type;
+
+            interface_info = g_type_info_get_interface(type_info);
+            interface_type = g_base_info_get_type(interface_info);
+            switch (interface_type) {
+              case GI_INFO_TYPE_STRUCT:
+              case GI_INFO_TYPE_UNION:
+              case GI_INFO_TYPE_BOXED:
+                {
+                    int offset;
+
+                    offset = g_field_info_get_offset(info);
+                    G_STRUCT_MEMBER(gpointer, memory, offset) = field_value.v_pointer;
+                    succeeded = TRUE;
+                }
+                break;
+              default:
+                break;
+            }
+            g_base_info_unref(interface_info);
+
+        }
     }
     rb_gi_value_argument_free(rb_field_value, &field_value, type_info);
     g_base_info_unref(type_info);
```

**Comment by kou** [comment]
Oh... Sorry... I forgot to push my change... I've pushed one commit that is similar to yours.

**Comment by cedlemo** [comment]
:) ok, no problem thanks.

**Comment by cedlemo** [comment]
It seems that something is not working, I was not able to debug it.

For example in the tests, I have this : 

```ruby
  def test_start_index
    assert_equal(0, @attribute.attr.start_index)
    @attribute.attr.start_index = 5
    assert_equal(5, @attribute.attr.start_index)
  end
```

If I try to access (read or write) the start_index, the gem crash, here is the output : 

```
/home/cedlemo/Projets/Ruby/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:258: [BUG] Segmentation fault at 0x00000000000008
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0031 p:---- s:0177 e:000176 CFUNC  :set_field_value
c:0030 p:0015 s:0170 e:000169 LAMBDA /home/cedlemo/Projets/Ruby/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:258 [FINISH]
c:0029 p:0020 s:0166 e:000164 METHOD /home/cedlemo/Projets/Ruby/ruby-gnome2/pango/test/test-attribute.rb:10
c:0028 p:0168 s:0161 e:000160 METHOD /usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/testcase.rb:764
c:0027 p:0010 s:0152 e:000151 BLOCK  /usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/testcase.rb:479 [FINISH]
c:0026 p:0034 s:0149 E:0002d8 BLOCK  /usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/fixture.rb:270 [FINISH]
c:0025 p:0034 s:0145 E:001188 BLOCK  /usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/fixture.rb:270 [FINISH]
c:0024 p:0069 s:0141 e:000140 METHOD /usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/fixture.rb:251
c:0023 p:0013 s:0132 e:000131 METHOD /usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/fixture.rb:286
c:0022 p:0009 s:0127 E:002478 BLOCK  /usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/testcase.rb:477 [FINISH]
c:0021 p:---- s:0123 e:000122 CFUNC  :catch
c:0020 p:0064 s:0119 E:0002c0 METHOD /usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/testcase.rb:476
c:0019 p:0029 s:0113 E:000d08 METHOD /usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/testsuite.rb:124
c:0018 p:0097 s:0104 e:000103 METHOD /usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/testsuite.rb:53
c:0017 p:0029 s:0097 E:000a38 METHOD /usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/testsuite.rb:124
c:0016 p:0097 s:0088 e:000087 METHOD /usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/testsuite.rb:53
c:0015 p:0035 s:0081 E:000d28 METHOD /usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/ui/testrunnermediator.rb:67
c:0014 p:0052 s:0076 e:000075 BLOCK  /usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/ui/testrunnermediator.rb:45
c:0013 p:0084 s:0073 E:000918 METHOD /usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/ui/testrunnermediator.rb:102
c:0012 p:0022 s:0064 E:002028 BLOCK  /usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/ui/testrunnermediator.rb:41 [FINISH]
c:0011 p:---- s:0060 e:000059 CFUNC  :catch
c:0010 p:0067 s:0056 E:001ff8 METHOD /usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/ui/testrunnermediator.rb:39
c:0009 p:0011 s:0049 e:000048 METHOD /usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/ui/testrunner.rb:40
c:0008 p:0033 s:0045 e:000044 METHOD /usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/ui/testrunner.rb:25
c:0007 p:0021 s:0041 e:000040 METHOD /usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/ui/testrunnerutilities.rb:24
c:0006 p:0015 s:0035 e:000034 BLOCK  /usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/autorunner.rb:438
c:0005 p:0033 s:0032 e:000031 METHOD /usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/autorunner.rb:494
c:0004 p:0208 s:0027 E:002170 METHOD /usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/autorunner.rb:437
c:0003 p:0079 s:0021 e:000020 METHOD /usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/autorunner.rb:62
c:0002 p:0265 s:0012 E:000398 EVAL   ./run-test.rb:52 [FINISH]
c:0001 p:0000 s:0003 E:000a50 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
./run-test.rb:52:in `<main>'
/usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/autorunner.rb:62:in `run'
/usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/autorunner.rb:437:in `run'
/usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/autorunner.rb:494:in `change_work_directory'
/usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/autorunner.rb:438:in `block in run'
/usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/ui/testrunnerutilities.rb:24:in `run'
/usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/ui/testrunner.rb:25:in `start'
/usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/ui/testrunner.rb:40:in `start_mediator'
/usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/ui/testrunnermediator.rb:39:in `run'
/usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/ui/testrunnermediator.rb:39:in `catch'
/usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/ui/testrunnermediator.rb:41:in `block in run'
/usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/ui/testrunnermediator.rb:102:in `with_listener'
/usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/ui/testrunnermediator.rb:45:in `block (2 levels) in run'
/usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/ui/testrunnermediator.rb:67:in `run_suite'
/usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/testsuite.rb:53:in `run'
/usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/testsuite.rb:124:in `run_test'
/usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/testsuite.rb:53:in `run'
/usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/testsuite.rb:124:in `run_test'
/usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/testcase.rb:476:in `run'
/usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/testcase.rb:476:in `catch'
/usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/testcase.rb:477:in `block in run'
/usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/fixture.rb:286:in `run_setup'
/usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/fixture.rb:251:in `run_fixture'
/usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/fixture.rb:270:in `block in create_fixtures_runner'
/usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/fixture.rb:270:in `block in create_fixtures_runner'
/usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/testcase.rb:479:in `block (2 levels) in run'
/usr/lib/ruby/gems/2.4.0/gems/test-unit-3.2.3/lib/test/unit/testcase.rb:764:in `run_test'
/home/cedlemo/Projets/Ruby/ruby-gnome2/pango/test/test-attribute.rb:10:in `test_start_index'
/home/cedlemo/Projets/Ruby/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:258:in `block in load_field'
/home/cedlemo/Projets/Ruby/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:258:in `set_field_value'

-- Machine register context ------------------------------------------------
 RIP: 0x00007f7508bf21a9 RBP: 0x0000000000000001 RSP: 0x00007ffeb5b46310
 RAX: 0x0000000000000005 RBX: 0x0000000002121a80 RCX: 0x0000000000000000
 RDX: 0x00007f7508c0d5c8 RDI: 0x0000000002121940 RSI: 0x0000000000000050
  R8: 0x0000000001fd4aa0  R9: 0x000000000000187c R10: 0x00000000000003c2
 R11: 0x00007f750bdc38c0 R12: 0x0000000000000000 R13: 0x00007ffeb5b46370
 R14: 0x0000000002121940 R15: 0x0000000000000008 EFL: 0x0000000000010217

-- C level backtrace information -------------------------------------------
/usr/lib/libruby.so.2.4 [0x7f750be95785]
/usr/lib/libruby.so.2.4 [0x7f750be959bc]
/usr/lib/libruby.so.2.4 [0x7f750bd706d4]
/usr/lib/libruby.so.2.4 [0x7f750be2c0ee]
/usr/lib/libc.so.6 [0x7f750b974a90]
/usr/lib/libgirepository-1.0.so.1(g_field_info_set_field+0x199) [0x7f7508bf21a9]
/home/cedlemo/Projets/Ruby/ruby-gnome2/gobject-introspection/ext/gobject-introspection/gobject_introspection.so(rb_gi_field_info_set_field_raw+0x60) [0x7f7508e2ace0]
/home/cedlemo/Projets/Ruby/ruby-gnome2/gobject-introspection/ext/gobject-introspection/gobject_introspection.so [0x7f7508e25d42]
```

**Comment by kou** [comment]
Ah, we should set `Pango::Attribute` as `AttrXXX`'s parent class like the following:

```ruby
  class Loader < GObjectIntrospection::Loader
    def pre_load(repository, namespace)
      @pending_attribute_infos = []
    end

    def post_load(repository, namespace)
      @pending_attribute_infos.each do |info|
        define_struct(info, :parent => Attribute)
      end
    end

    def load_struct_info(info)
      case info.name
      when /Class\z/
        super
      when/\AAttr[A-Z]/
        @pending_attribute_infos << info
      else
        super
      end
    end
  end
```

We can use `Pango::AttrLanguage#start_index` when `Pango::AttrLanguage` is a subclass of `Pango::Attribute`.

**Comment by cedlemo** [comment]
Thanks, I understood the relation between the `Attribute` and the `AttrXXX` but I was not able to see how do it like with this : 

```
define_struct(info, :parent => Attribute)
```

The following test, 
```
   assert_equal(GLib::MAXUINT, @attribute.end_index)
```
make me write the `AttrLanguage` class like this:  

```ruby
module Pango
  class AttrLanguage
    alias_method :initialize_raw, :initialize
    def initialize(language)
      initialize_raw
      init(self)
      self.value = language
    end
  end
end
```

Focusing on the usage of  `Pango::Attribute#init` in this class, is it Ok for you ?

**Comment by cedlemo** [comment]
@kou,
I would like to push what I already have done (after you solve the issue #1006) because otherwise, there will be too much commits in the same Pull request and it will be difficult for you to review my work.

**Comment by kou** [comment]
> I would like to push what I already have done

It's reasonable. Could you create a pull request? You don't need to wait #1006. I want to try the case on my environment. I need your works for it.

**Comment by kou** [comment]
`init(self)` isn't good because `self` isn't `PangoAttrClass`. We should set `end_index` to `2 ** 32 -1` by ourselves. We should use `PANGO_ATTR_INDEX_TO_TEXT_END` instead of `2 ** 32 - 1` but GObject Introspection doesn't export it. Perhaps, `#define PANGO_ATTR_INDEX_TO_TEXT_END G_MAXUINT` is the problem. GObject Introspection may not support `G_MAXUINT` yet.

Could you report it to GObject Introspection?

**Comment by cedlemo** [comment]
@kou,

you mean that instead of : 

```ruby
    def initialize(language)
      initialize_raw
      init(self)
      self.value = language
    end
```

I should write this

```ruby
    def initialize(language)
      initialize_raw
      self.value = language
      self.start_index = 0
      self.end_index = 2 ** 32 - 1
    end
```

because the object we pass to `#init` is not the right class

I have 2 questions :

*   why the following test is working ?

```ruby
assert_equal(GLib::MAXUINT, @attribute.end_index)
```

*  Just to be sure : 

you want me to ask the GObjectIntrospection to export the following constant `PANGO_ATTR_INDEX_TO_TEXT_END` or `G_MAXUINT` is it good ?

**Comment by kou** [comment]
> you mean that instead of : 
> 
> ...
> 
> I should write this
> 
> ...
> 
> because the object we pass to `#init` is not the right class

Right! But I found a stupid code. `2 ** 32 - 1` should be `GLib::MAXUINT`.

> I have 2 questions :
> 
> *   why the following test is working ?
> 
> ```ruby
> assert_equal(GLib::MAXUINT, @attribute.end_index)
> ```

Because `self.end_index = 2 ** 32 - 1` in `#initialize` set the value that equals to `GLib::MAXUINT`.

> *  Just to be sure : 
> 
> you want me to ask the GObjectIntrospection to export the following constant `PANGO_ATTR_INDEX_TO_TEXT_END` or `G_MAXUINT` is it good ?

Almost right. We don't need `G_MAXUINT` because we have `GLib::MAXUINT`.

We only `PANGO_ATTR_INDEX_TO_TEXT_END`. We don't want to care the value of `PANGO_ATTR_INDEX_TO_TEXT_END`. For example, we don't want to care its value is `G_MAXUINT` or `G_MAXULONG`. It's an implementation detail.

**Comment by cedlemo** [comment]
> Because self.end_index = 2 ** 32 - 1 in #initialize set the value that equals to GLib::MAXUINT.

@kou, It seems that I was not clear enought, the following test : 

        assert_equal(GLib::MAXUINT, @attribute.end_index)

works when the `initialize` method is written like this : 

```ruby
  class AttrLanguage
    alias_method :initialize_raw, :initialize
    def initialize(language)
      initialize_raw
      init(self)
      self.value = language
    end
  end
```
with this code, it is the C code that initialize the value of the structure. Is it working while it should not as you said me, it is just a coincidence ?

I will fill a bug to see if they can show the `PANGO_ATTR_INDEX_TO_TEXT_END` in gobject-introspection.

**Comment by kou** [comment]
> Is it working while it should not as you said me, it is just a coincidence ?

`#init` calls [`pango_attribute_init()`](https://git.gnome.org/browse/pango/tree/pango/pango-attributes.c#n146). `pango_attribute_init()` sets `klass`, `start_index` and `end_index`. The test is passed because `end_index` is set to `G_MAXUINT`. But `pango_attribute_init()` also sets `klass` and `klass` value is invalid. It'll cause SEGV when `klass` is used. For example [`pango_attr_list_change()`](https://git.gnome.org/browse/pango/tree/pango/pango-attributes.c#n1407) uses `klass`.

... but we can't use `Pango::AttrList`. It requires `Pango::AttrLanguage` is created by `pango_attr_language_new()` but `pango_attr_language_new()` isn't exported by GObject Introspection. We should report it to Pango project.

> I will fill a bug to see if they can show the `PANGO_ATTR_INDEX_TO_TEXT_END` in gobject-introspection.

**Comment by cedlemo** [comment]
I have no response now for the pango bug (there are in the freeze part for gnome 3.24, so I guess we will have to wait)

Is the following commit https://github.com/ruby-gnome2/ruby-gnome2/commit/dc403a656dc2322a04212749eed74c4dd290dd49 is related to the problem of the initialization .

**Comment by kou** [comment]
> Is the following commit dc403a6 is related to the problem of the initialization .

It's related a bit. The commit is for `Pango::AttrList`. It's not for other `Pango::AttrXXX` such as `Pango::AttrLanguage`.

**Comment by cedlemo** [comment]
@kou, I have two questions : 

*  should I ask to the pango maintainers to make the others `pango_attr_.*_new` functions introspectable.

*  for the `PANGO_ATTR_INDEX_TO_TEXT_END`, it seems like you said that the `G_MAXUINT` is not supported by the parser of `GObject-Introspection` (I did not understand this statement first because I have not the knowledge you have on GI). I proposed to the pango team to write the macro like this : 

    #define PANGO_ATTR_INDEX_TO_TEXT_END   ((guint32) 0xffffffff)

based on the definition og `G_MAXUINT32` from gtypes.h. My tests show that the GObject-Introspection parser handles this (ie: it works). Based on your knowledge, do you think it is a good solution or should I contact the `GObject-Introspection` maintainers/dev in order to ask them to support G_MAXUINT or G_MAXUINT32 ?

**Comment by kou** [comment]
> * should I ask to the pango maintainers to make the others `pango_attr_.*_new` functions introspectable.

Yes!

> * for the `PANGO_ATTR_INDEX_TO_TEXT_END`, it seems like you said that the `G_MAXUINT` is not supported by the parser of GObject-Introspection (I did not understand this statement first because I have not the knowledge you have on GI).

Yes.

> I proposed to the pango team to write the macro like this :
>
> ```c
> #define PANGO_ATTR_INDEX_TO_TEXT_END ((guint32) 0xffffffff)
> ```
>
> based on the definition of `G_MAXUINT32` from gtypes.h.

Yes. It's a solution.

> Based on your knowledge, do you think it is a good solution or should I contact the GObject-Introspection maintainers/dev in order to ask them to support `G_MAXUINT` or `G_MAXUINT32`?

I think that it's better that reporting this to GObject Introspection maintainers. Because not only Pango but also all GObject Introspection users can use `G_MAXUINT32` when GObject Introspection supports `G_MAXUINT32`. Code that uses `G_MAXUINT32` is more readable than code that uses `((guint32) 0xffffffff)`.

But reporting the above solution to Pango maintainers isn't bad. Because Pango users via GObject Introspection (including us) can use `PANGO_ATTR_INDEX_TO_TEXT_END`.

**Comment by cedlemo** [comment]
@kou,

it seems that we will have a problem with the support of `pango_attr_language_new` by gobject-introspection. 

*  1. When I look at the warnings during the building step, the gir parser says that the PangoAttrLanguage must be defined as a BOXED type and when I look at the code, it seems (to me) that the `PangoAttribute` and `PangoAttr*` are not "organized" like classical GObject. I tried to look a little but I hardly see how I can propose a patch. You I am that kind of clever guy that tried this : 

```

G_DEFINE_BOXED_TYPE (PangoAttrLanguage, pango_attr_language,
                     pango_attr_language_copy,
                     pango_attr_language_destroy);
```

and of course it did not work ( :-) ) . Have you got an idea on how I can propose them something ?

by the way here is the link of the bug request : https://bugzilla.gnome.org/show_bug.cgi?id=780463

**Comment by kou** [comment]
This change will make `pango_attr_language_new()` GObject Introspective-able:

```diff
diff --git a/pango/pango-attributes.c b/pango/pango-attributes.c
index df3104f0..9c2d3061 100644
--- a/pango/pango-attributes.c
+++ b/pango/pango-attributes.c
@@ -276,7 +276,7 @@ pango_attr_family_new (const char *family)
 static PangoAttribute *
 pango_attr_language_copy (const PangoAttribute *attr)
 {
-  return pango_attr_language_new (((PangoAttrLanguage *)attr)->value);
+  return (PangoAttribute *)pango_attr_language_new (((PangoAttrLanguage *)attr)->value);
 }
 
 static void
@@ -294,6 +294,10 @@ pango_attr_language_equal (const PangoAttribute *attr1,
   return ((PangoAttrLanguage *)attr1)->value == ((PangoAttrLanguage *)attr2)->value;
 }
 
+G_DEFINE_BOXED_TYPE (PangoAttrLanguage, pango_attr_language,
+                     (GBoxedCopyFunc) pango_attr_language_copy,
+                     (GBoxedFreeFunc) pango_attr_language_destroy);
+
 /**
  * pango_attr_language_new:
  * @language: language tag
@@ -303,7 +307,7 @@ pango_attr_language_equal (const PangoAttribute *attr1,
  * Return value: (transfer full): the newly allocated #PangoAttribute,
  *               which should be freed with pango_attribute_destroy().
  **/
-PangoAttribute *
+PangoAttrLanguage *
 pango_attr_language_new (PangoLanguage *language)
 {
   PangoAttrLanguage *result;
@@ -319,7 +323,7 @@ pango_attr_language_new (PangoLanguage *language)
   pango_attribute_init (&result->attr, &klass);
   result->value = language;
 
-  return (PangoAttribute *)result;
+  return result;
 }
 
 static PangoAttribute *
diff --git a/pango/pango-attributes.h b/pango/pango-attributes.h
index e9b19571..fc3326ce 100644
--- a/pango/pango-attributes.h
+++ b/pango/pango-attributes.h
@@ -450,8 +450,10 @@ PANGO_AVAILABLE_IN_ALL
 gboolean         pango_attribute_equal       (const PangoAttribute *attr1,
 					      const PangoAttribute *attr2) G_GNUC_PURE;
 
+PANGO_AVAILABLE_IN_1_40
+GType              pango_attr_language_get_type      (void) G_GNUC_CONST;
 PANGO_AVAILABLE_IN_ALL
-PangoAttribute *pango_attr_language_new      (PangoLanguage              *language);
+PangoAttrLanguage *pango_attr_language_new      (PangoLanguage              *language);
 PANGO_AVAILABLE_IN_ALL
 PangoAttribute *pango_attr_family_new        (const char                 *family);
 PANGO_AVAILABLE_IN_ALL
```

**Comment by cedlemo** [comment]
Ha Ok, I was afraid to change the signature of `pango_attr_language_new`.

Since you don't want to post the patch on the gnome bugzilla, I will have to appropriate your work again (they ask for patch and those patch are linked to my github account) and I deeply apologize @kou.

**Comment by kou** [comment]
> I will have to appropriate your work again (they ask for patch and those patch are linked to my github account) and I deeply apologize

I don't care about it. :-)
I just want to improve free software. I don't need kudos.

I thank you that you report our problems to upstream instead of me! (It's difficult to me that I write many English... :<)

**Comment by kou** [comment]
I've implemented them in C.
