### ISSUE TITLE
NotImplementedError: TODO: allocates GIArgument(array)[c][interface]  for output

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#1006]
@kou,

In some pango tests, I have the following error: 

```
Error: test_families(TestContext): NotImplementedError: TODO: allocates GIArgument(array)[c][interface] for output
/home/cedlemo/Projets/Ruby/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:537:in `invoke'
/home/cedlemo/Projets/Ruby/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:537:in `block in define_method'
/home/cedlemo/Projets/Ruby/ruby-gnome2/pango/test/test-context.rb:94:in `test_families'
     91:   end
     92: 
     93:   def test_families
  => 94:     family_names = @context.list_families.collect(&:name)
     95:     assert do
     96:       family_names.include?("Monospace")
     97:     end

```

I have been able to fix it with : 

```diff
diff --git a/gobject-introspection/ext/gobject-introspection/rb-gi-argument.c b/gobject-introspection/ext/gobject-introspection/rb-gi-argument.c
index 54258c927..8af093a0c 100644
--- a/gobject-introspection/ext/gobject-introspection/rb-gi-argument.c
+++ b/gobject-introspection/ext/gobject-introspection/rb-gi-argument.c
@@ -1244,6 +1244,8 @@ rb_gi_out_argument_init_array_c(GIArgument *argument,
       case GI_TYPE_TAG_FILENAME:
       case GI_TYPE_TAG_ARRAY:
       case GI_TYPE_TAG_INTERFACE:
+        argument->v_pointer = xmalloc(sizeof(gpointer *));
+        break;
       case GI_TYPE_TAG_GLIST:
       case GI_TYPE_TAG_GSLIST:
       case GI_TYPE_TAG_GHASH:
@@ -1801,6 +1803,8 @@ rb_gi_out_argument_fin_array_c(GIArgument *argument,
       case GI_TYPE_TAG_FILENAME:
       case GI_TYPE_TAG_ARRAY:
       case GI_TYPE_TAG_INTERFACE:
+        xfree(argument->v_pointer);
+        break;
       case GI_TYPE_TAG_GLIST:
       case GI_TYPE_TAG_GSLIST:
       case GI_TYPE_TAG_GHASH:
```

But I am not sure if it is the right thing to do, I hope it can help you.

**Comment by kou** [comment]
I've fixed this. Sorry for my late work.

**Comment by cedlemo** [comment]
> I've fixed this. Sorry for my late work.

No problem, thanks.
