### ISSUE TITLE
Gtk3 Sample issue in the rotated_text demo

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#1042]
When you run the demo : 

    ./main.rb -r rotated_text

It crash with the following message : 

```
/home/cedlemo/.gem/ruby/2.4.0/gems/gobject-introspection-3.1.7/lib/gobject-introspection/loader.rb:265: [BUG] Segmentation fault at 0x00000000000008
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0014 p:---- s:0082 e:000081 CFUNC  :get_field_value
c:0013 p:0012 s:0076 e:000075 LAMBDA /home/cedlemo/.gem/ruby/2.4.0/gems/gobject-introspection-3.1.7/lib/gobject-introspection/loader.rb:265 [FINISH]
c:0012 p:0040 s:0072 e:000070 METHOD /home/cedlemo/Projets/Ruby/ruby-gnome2/gtk3/sample/gtk-demo/rotated_text.rb:76
c:0011 p:0014 s:0062 e:000061 BLOCK  /home/cedlemo/Projets/Ruby/ruby-gnome2/gtk3/sample/gtk-demo/rotated_text.rb:132 [FINISH]
c:0010 p:---- s:0056 e:000055 CFUNC  :invoke
c:0009 p:0090 s:0051 e:000050 LAMBDA /home/cedlemo/.gem/ruby/2.4.0/gems/gobject-introspection-3.1.7/lib/gobject-introspection/loader.rb:573 [FINISH]
c:0008 p:0066 s:0045 e:000044 BLOCK  /home/cedlemo/Projets/Ruby/ruby-gnome2/gtk3/sample/gtk-demo/rotated_text.rb:153 [FINISH]
c:0007 p:---- s:0041 e:000040 CFUNC  :times
c:0006 p:0015 s:0037 e:000036 METHOD /home/cedlemo/Projets/Ruby/ruby-gnome2/gtk3/sample/gtk-demo/rotated_text.rb:148
c:0005 p:0042 s:0031 e:000030 BLOCK  /home/cedlemo/Projets/Ruby/ruby-gnome2/gtk3/sample/gtk-demo/rotated_text.rb:43 [FINISH]
c:0004 p:---- s:0025 e:000024 CFUNC  :invoke
c:0003 p:0107 s:0019 e:000018 LAMBDA /home/cedlemo/.gem/ruby/2.4.0/gems/gobject-introspection-3.1.7/lib/gobject-introspection/loader.rb:575 [FINISH]
c:0002 p:0371 s:0013 E:0007e0 EVAL   ./main.rb:516 [FINISH]
c:0001 p:0000 s:0003 E:001210 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
./main.rb:516:in `<main>'
/home/cedlemo/.gem/ruby/2.4.0/gems/gobject-introspection-3.1.7/lib/gobject-introspection/loader.rb:575:in `block in define_method'
/home/cedlemo/.gem/ruby/2.4.0/gems/gobject-introspection-3.1.7/lib/gobject-introspection/loader.rb:575:in `invoke'
/home/cedlemo/Projets/Ruby/ruby-gnome2/gtk3/sample/gtk-demo/rotated_text.rb:43:in `block in initialize'
/home/cedlemo/Projets/Ruby/ruby-gnome2/gtk3/sample/gtk-demo/rotated_text.rb:148:in `draw_the_rotated_texts'
/home/cedlemo/Projets/Ruby/ruby-gnome2/gtk3/sample/gtk-demo/rotated_text.rb:148:in `times'
/home/cedlemo/Projets/Ruby/ruby-gnome2/gtk3/sample/gtk-demo/rotated_text.rb:153:in `block in draw_the_rotated_texts'
/home/cedlemo/.gem/ruby/2.4.0/gems/gobject-introspection-3.1.7/lib/gobject-introspection/loader.rb:573:in `block in define_method'
/home/cedlemo/.gem/ruby/2.4.0/gems/gobject-introspection-3.1.7/lib/gobject-introspection/loader.rb:573:in `invoke'
/home/cedlemo/Projets/Ruby/ruby-gnome2/gtk3/sample/gtk-demo/rotated_text.rb:132:in `block in initialize_da_pango_layout'
/home/cedlemo/Projets/Ruby/ruby-gnome2/gtk3/sample/gtk-demo/rotated_text.rb:76:in `fancy_shape_renderer'
/home/cedlemo/.gem/ruby/2.4.0/gems/gobject-introspection-3.1.7/lib/gobject-introspection/loader.rb:265:in `block in load_field_reader'
/home/cedlemo/.gem/ruby/2.4.0/gems/gobject-introspection-3.1.7/lib/gobject-introspection/loader.rb:265:in `get_field_value'
```

**Comment by kou** [comment]
Oh, sorry. I missed this.
I've fixed this after I released Ruby-GNOME2 3.1.7. :<
