### ISSUE TITLE
Cannot install gobject-introspection 3.1.7 on Mac, but 3.1.6 works

### ISSUE THREAD

**Issue by andymeneely** [ruby-gnome2/ruby-gnome2#1058]
Here's the output I get:

```
$ gem install gobject-introspection 
Building native extensions.  This could take a while...
ERROR:  Error installing gobject-introspection:
	ERROR: Failed to build gem native extension.

    current directory: /Users/andy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.1.7/ext/gobject-introspection
/Users/andy/.rbenv/versions/2.3.3/bin/ruby -r ./siteconf20170713-23956-1udjgme.rb extconf.rb
checking for --enable-debug-build option... no
checking for -Wall option to compiler... yes
checking for -Waggregate-return option to compiler... yes
checking for -Wcast-align option to compiler... yes
checking for -Wextra option to compiler... yes
checking for -Wformat=2 option to compiler... yes
checking for -Winit-self option to compiler... yes
checking for -Wlarger-than-65500 option to compiler... yes
checking for -Wmissing-declarations option to compiler... yes
checking for -Wmissing-format-attribute option to compiler... yes
checking for -Wmissing-include-dirs option to compiler... yes
checking for -Wmissing-noreturn option to compiler... yes
checking for -Wmissing-prototypes option to compiler... yes
checking for -Wnested-externs option to compiler... yes
checking for -Wold-style-definition option to compiler... yes
checking for -Wpacked option to compiler... yes
checking for -Wp,-D_FORTIFY_SOURCE=2 option to compiler... yes
checking for -Wpointer-arith option to compiler... yes
checking for -Wswitch-default option to compiler... yes
checking for -Wswitch-enum option to compiler... yes
checking for -Wundef option to compiler... yes
checking for -Wout-of-line-declaration option to compiler... yes
checking for -Wunsafe-loop-optimizations option to compiler... no
checking for -Wwrite-strings option to compiler... yes
checking for Windows... no
checking for gobject-introspection-1.0... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/andy/.rbenv/versions/2.3.3/bin/$(RUBY_BASE_NAME)
	--enable-debug-build
	--disable-debug-build
	--with-pkg-config
	--without-pkg-config
	--with-override-variables
	--without-override-variables
/Users/andy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pkg-config-1.2.3/lib/pkg-config.rb:296:in `parse_pc': .pc for libffi doesn't exist. (RuntimeError)
	from /Users/andy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pkg-config-1.2.3/lib/pkg-config.rb:196:in `declaration'
	from /Users/andy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pkg-config-1.2.3/lib/pkg-config.rb:210:in `collect_cflags'
	from /Users/andy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pkg-config-1.2.3/lib/pkg-config.rb:145:in `cflags'
	from /Users/andy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pkg-config-1.2.3/lib/pkg-config.rb:212:in `block in collect_cflags'
	from /Users/andy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pkg-config-1.2.3/lib/pkg-config.rb:211:in `collect'
	from /Users/andy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pkg-config-1.2.3/lib/pkg-config.rb:211:in `collect_cflags'
	from /Users/andy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pkg-config-1.2.3/lib/pkg-config.rb:154:in `cflags_only_other'
	from /Users/andy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pkg-config-1.2.3/lib/pkg-config.rb:443:in `cflags_only_other'
	from /Users/andy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pkg-config-1.2.3/lib/pkg-config.rb:490:in `have_package'
	from /Users/andy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/glib2-3.1.7/lib/mkmf-gnome2.rb:488:in `required_pkg_config_package'
	from extconf.rb:53:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/andy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-16/2.3.0-static/gobject-introspection-3.1.7/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/andy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.1.7 for inspection.
Results logged to /Users/andy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-16/2.3.0-static/gobject-introspection-3.1.7/gem_make.out

```

But, 3.1.6 works:

```
$ gem install gobject-introspection -v '3.1.6'
Building native extensions.  This could take a while...
Successfully installed gobject-introspection-3.1.6
Parsing documentation for gobject-introspection-3.1.6
Done installing documentation for gobject-introspection after 0 seconds
```

Here's my `uname -a`:

```
16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_6
```

macOS Sierra 10.12.5

**Comment by andymeneely** [comment]
Ok, it appears that this issue has come up before. This advice still works: https://github.com/ruby-gnome2/ruby-gnome2/issues/259#issuecomment-59751807

But I'd rather not require my users to do this - what changed in 3.1.7 to break the easy install?

**Comment by kou** [comment]
Thanks for your report.
I've fixed it. We should release a new version with it.

**Comment by andymeneely** [comment]
Awesome. Thank you for being so responsive!!
