### ISSUE TITLE
Issues installing/using rsvg2 gem on heroku-16

### ISSUE THREAD

**Issue by Chocksy** [ruby-gnome2/ruby-gnome2#1063]
I tried to use the rsvg2 gem on heroku but there is an error when installing the dependencies.
```
       Installing cairo 1.15.9 with native extensions
       Installing glib2 3.1.8 with native extensions
       Fetching cairo-gobject 3.1.8
       Fetching gobject-introspection 3.1.8
       Installing cairo-gobject 3.1.8 with native extensions
       Installing gobject-introspection 3.1.8 with native extensions
       The latest bundler is 1.15.2, but you are currently running 1.15.1.
       To update, run `gem install bundler`
       Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
       
       current directory:
       /tmp/build_1b590bc59e05ca1d996a41044f1a57ba/azertys-pxls-166f3cb4eae2f72cdbcc85694685f9781b182006/vendor/bundle/ruby/2.4.0/gems/gobject-introspection-3.1.8/ext/gobject-introspection
       /tmp/build_1b590bc59e05ca1d996a41044f1a57ba/azertys-pxls-166f3cb4eae2f72cdbcc85694685f9781b182006/vendor/ruby-2.4.0/bin/ruby
       -r ./siteconf20170718-205-l8a9at.rb extconf.rb
       checking for --enable-debug-build option... no
       checking for -Wall option to compiler... yes
       checking for -Waggregate-return option to compiler... yes
       checking for -Wcast-align option to compiler... yes
       checking for -Wextra option to compiler... yes
       checking for -Wformat=2 option to compiler... yes
       checking for -Winit-self option to compiler... yes
       checking for -Wlarger-than-65500 option to compiler... yes
       checking for -Wmissing-declarations option to compiler... yes
       checking for -Wmissing-format-attribute option to compiler... yes
       checking for -Wmissing-include-dirs option to compiler... yes
       checking for -Wmissing-noreturn option to compiler... yes
       checking for -Wmissing-prototypes option to compiler... yes
       checking for -Wnested-externs option to compiler... yes
       checking for -Wold-style-definition option to compiler... yes
       checking for -Wpacked option to compiler... yes
       checking for -Wp,-D_FORTIFY_SOURCE=2 option to compiler... yes
       checking for -Wpointer-arith option to compiler... yes
       checking for -Wswitch-default option to compiler... yes
       checking for -Wswitch-enum option to compiler... yes
       checking for -Wundef option to compiler... yes
       checking for -Wout-of-line-declaration option to compiler... no
       checking for -Wunsafe-loop-optimizations option to compiler... yes
       checking for -Wwrite-strings option to compiler... yes
       checking for Windows... no
       checking for gobject-introspection-1.0... no
       installing 'libgirepository1.0-dev' native package... require super user
       privilege
       'libgirepository1.0-dev' native package is required.
       Run the following command as super user to install required native package:
       # apt install -V -y libgirepository1.0-dev
       *** extconf.rb failed ***
       Could not create Makefile due to some reason, probably lack of necessary
       libraries and/or headers.  Check the mkmf.log file for more details.  You may
       need configuration options.
       
       Provided configuration options:
       --with-opt-dir
       --without-opt-dir
       --with-opt-include
       --without-opt-include=${opt-dir}/include
       --with-opt-lib
       --without-opt-lib=${opt-dir}/lib
       --with-make-prog
       --without-make-prog
       --srcdir=.
       --curdir
       --ruby=/tmp/build_1b590bc59e05ca1d996a41044f1a57ba/azertys-pxls-166f3cb4eae2f72cdbcc85694685f9781b182006/vendor/ruby-2.4.0/bin/$(RUBY_BASE_NAME)
       --enable-debug-build
       --disable-debug-build
       --with-pkg-config
       --without-pkg-config
       --with-override-variables
       --without-override-variables
       
       To see why this extension failed to compile, please check the mkmf.log which can
       be found here:
       
       /tmp/build_1b590bc59e05ca1d996a41044f1a57ba/azertys-pxls-166f3cb4eae2f72cdbcc85694685f9781b182006/vendor/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0/gobject-introspection-3.1.8/mkmf.log
       
       extconf failed, exit code 1
       
       Gem files will remain installed in
       /tmp/build_1b590bc59e05ca1d996a41044f1a57ba/azertys-pxls-166f3cb4eae2f72cdbcc85694685f9781b182006/vendor/bundle/ruby/2.4.0/gems/gobject-introspection-3.1.8
       for inspection.
       Results logged to
       /tmp/build_1b590bc59e05ca1d996a41044f1a57ba/azertys-pxls-166f3cb4eae2f72cdbcc85694685f9781b182006/vendor/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0/gobject-introspection-3.1.8/gem_make.out
       
       An error occurred while installing gobject-introspection (3.1.8), and Bundler
       cannot continue.
       Make sure that `gem install gobject-introspection -v '3.1.8'` succeeds before
       bundling.
       
       In Gemfile:
       rsvg2 was resolved to 3.1.8, which depends on
       gdk_pixbuf2 was resolved to 3.1.8, which depends on
       gio2 was resolved to 3.1.8, which depends on
       gobject-introspection
 !
 !     Failed to install gems via Bundler.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed
```
I tried to use the 3.0.7 version but it does not install on my local mac https://github.com/ruby-gnome2/ruby-gnome2/issues/900

I'm using ruby 2.4.0 and rails 5.0.2

**Comment by kou** [comment]
> ```text
>        checking for gobject-introspection-1.0... no
>        installing 'libgirepository1.0-dev' native package... require super user
>        privilege
>        'libgirepository1.0-dev' native package is required.
>        Run the following command as super user to install required native package:
>        # apt install -V -y libgirepository1.0-dev
>        *** extconf.rb failed ***
> ```

Please install `libgirepository1.0-dev`.

**Comment by Chocksy** [comment]
@kou thanks for the reply.
Heroku says it already has that package but it's not `-dev` see here https://devcenter.heroku.com/articles/stack-packages

**Comment by Chocksy** [comment]
I managed to install libgirepository1.0-dev via the apt buildpack but i get a weird error now that i did not see on my mac.

```
       Fetching cairo-gobject 3.1.8
       Fetching gobject-introspection 3.1.8
       Installing cairo-gobject 3.1.8 with native extensions
       Installing gobject-introspection 3.1.8 with native extensions
       The latest bundler is 1.15.2, but you are currently running 1.15.1.
       To update, run `gem install bundler`
       Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
       
       current directory:
       /tmp/build_25daf0a1fba18f41d4f8dcc89ca790f7/azertys-pxls-6f4ee8289b16f85574182ffcfaa94b5b99800126/vendor/bundle/ruby/2.4.0/gems/gobject-introspection-3.1.8/ext/gobject-introspection
       /tmp/build_25daf0a1fba18f41d4f8dcc89ca790f7/azertys-pxls-6f4ee8289b16f85574182ffcfaa94b5b99800126/vendor/ruby-2.4.0/bin/ruby
       -r ./siteconf20170719-466-uzbut5.rb extconf.rb
       checking for --enable-debug-build option... no
       checking for -Wall option to compiler... yes
       checking for -Waggregate-return option to compiler... yes
       checking for -Wcast-align option to compiler... yes
       checking for -Wextra option to compiler... yes
       checking for -Wformat=2 option to compiler... yes
       checking for -Winit-self option to compiler... yes
       checking for -Wlarger-than-65500 option to compiler... yes
       checking for -Wmissing-declarations option to compiler... yes
       checking for -Wmissing-format-attribute option to compiler... yes
       checking for -Wmissing-include-dirs option to compiler... yes
       checking for -Wmissing-noreturn option to compiler... yes
       checking for -Wmissing-prototypes option to compiler... yes
       checking for -Wnested-externs option to compiler... yes
       checking for -Wold-style-definition option to compiler... yes
       checking for -Wpacked option to compiler... yes
       checking for -Wp,-D_FORTIFY_SOURCE=2 option to compiler... yes
       checking for -Wpointer-arith option to compiler... yes
       checking for -Wswitch-default option to compiler... yes
       checking for -Wswitch-enum option to compiler... yes
       checking for -Wundef option to compiler... yes
       checking for -Wout-of-line-declaration option to compiler... no
       checking for -Wunsafe-loop-optimizations option to compiler... yes
       checking for -Wwrite-strings option to compiler... yes
       checking for Windows... no
       checking for gobject-introspection-1.0... yes
       creating rbgiversion.h
       checking for g_interface_info_find_signal() in girepository.h... no
       creating gobject-introspection-enum-types.c
       creating gobject-introspection-enum-types.h
       creating ruby-gobject-introspection.pc
       creating Makefile
       
       To see why this extension failed to compile, please check the mkmf.log which can
       be found here:
       
       /tmp/build_25daf0a1fba18f41d4f8dcc89ca790f7/azertys-pxls-6f4ee8289b16f85574182ffcfaa94b5b99800126/vendor/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0/gobject-introspection-3.1.8/mkmf.log
       
       current directory:
       /tmp/build_25daf0a1fba18f41d4f8dcc89ca790f7/azertys-pxls-6f4ee8289b16f85574182ffcfaa94b5b99800126/vendor/bundle/ruby/2.4.0/gems/gobject-introspection-3.1.8/ext/gobject-introspection
       make "DESTDIR=" clean
       
       current directory:
       /tmp/build_25daf0a1fba18f41d4f8dcc89ca790f7/azertys-pxls-6f4ee8289b16f85574182ffcfaa94b5b99800126/vendor/bundle/ruby/2.4.0/gems/gobject-introspection-3.1.8/ext/gobject-introspection
       make "DESTDIR="
       compiling rb-gi-arg-info.c
       compiling rb-gi-callback-info.c
       compiling rb-gi-registered-type-info.c
       compiling rb-gi-type-tag.c
       compiling rb-gi-union-info.c
       compiling rb-gi-repository.c
       compiling rb-gi-vfunc-info.c
       compiling rb-gi-signal-info.c
       compiling rb-gi-callable-info.c
       compiling rb-gi-interface-info.c
       compiling rb-gi-type-info.c
       compiling rb-gi-constructor-info.c
       compiling gobject-introspection-enum-types.c
       compiling rb-gi-loader.c
       compiling rb-gi-field-info.c
       compiling rb-gi-enum-info.c
       compiling rb-gi-unresolved-info.c
       compiling rb-gi-method-info.c
       compiling rb-gi-object-info.c
       compiling rb-gi-argument.c
       compiling rb-gobject-introspection.c
       compiling rb-gi-function-info.c
       compiling rb-gi-base-info.c
       compiling rb-gi-property-info.c
       compiling rb-gi-boxed-info.c
       compiling rb-gi-value-info.c
       compiling rb-gi-constant-info.c
       rb-gi-constant-info.c: In function ‘rg_value’:
       rb-gi-constant-info.c:52:10: warning: variable ‘value_size’ set but not used
       [-Wunused-but-set-variable]
       gint value_size;
       ^
       rb-gi-constant-info.c: At top level:
       cc1: warning: unrecognized command line option ‘-Wno-self-assign’
       cc1: warning: unrecognized command line option ‘-Wno-constant-logical-operand’
       cc1: warning: unrecognized command line option ‘-Wno-parentheses-equality’
       cc1: warning: unrecognized command line option ‘-Wno-tautological-compare’
       compiling rb-gi-flags-info.c
       compiling rb-gi-struct-info.c
       linking shared-object gobject_introspection.so
       /usr/bin/ld:
       /tmp/build_25daf0a1fba18f41d4f8dcc89ca790f7/azertys-pxls-6f4ee8289b16f85574182ffcfaa94b5b99800126/.apt/usr/lib/x86_64-linux-gnu/libgirepository-1.0.a(libgirepository_1_0_la-giarginfo.o):
       relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a
       shared object; recompile with -fPIC
       /tmp/build_25daf0a1fba18f41d4f8dcc89ca790f7/azertys-pxls-6f4ee8289b16f85574182ffcfaa94b5b99800126/.apt/usr/lib/x86_64-linux-gnu/libgirepository-1.0.a:
       error adding symbols: Bad value
       collect2: error: ld returned 1 exit status
       Makefile:257: recipe for target 'gobject_introspection.so' failed
       make: *** [gobject_introspection.so] Error 1
       
       make failed, exit code 2
       
       Gem files will remain installed in
       /tmp/build_25daf0a1fba18f41d4f8dcc89ca790f7/azertys-pxls-6f4ee8289b16f85574182ffcfaa94b5b99800126/vendor/bundle/ruby/2.4.0/gems/gobject-introspection-3.1.8
       for inspection.
       Results logged to
       /tmp/build_25daf0a1fba18f41d4f8dcc89ca790f7/azertys-pxls-6f4ee8289b16f85574182ffcfaa94b5b99800126/vendor/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0/gobject-introspection-3.1.8/gem_make.out
       
       An error occurred while installing gobject-introspection (3.1.8), and Bundler
       cannot continue.
       Make sure that `gem install gobject-introspection -v '3.1.8'` succeeds before
       bundling.
       
       In Gemfile:
       rsvg2 was resolved to 3.1.8, which depends on
       gdk_pixbuf2 was resolved to 3.1.8, which depends on
       gio2 was resolved to 3.1.8, which depends on
       gobject-introspection
 !
 !     Failed to install gems via Bundler.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed
```

Any idea why this would happen?

**Comment by Chocksy** [comment]
The above error happens with using the apt buildpack: https://github.com/heroku/heroku-buildpack-apt
But also with the buildpack i made that just installs the libgirepository1.0-dev package: https://github.com/EpicCoders/heroku-buildpack-rsvg2

What i'm trying is to use rsvg2 on heroku to generate svg -> png images for our project.

**Comment by kou** [comment]
> ```text
>        /tmp/build_25daf0a1fba18f41d4f8dcc89ca790f7/azertys-pxls-6f4ee8289b16f85574182ffcfaa94b5b99800126/.apt/usr/lib/x86_64-linux-gnu/libgirepository-1.0.a(libgirepository_1_0_la-giarginfo.o):
> ```

You should link to shared library not static library.

It seems that your `libgirepository1.0-dev.tar.gz` doesn't include `libgirepository-1.0.so.1.0.0`.

**Comment by Chocksy** [comment]
@kou the zip i use includes that file. https://s3.amazonaws.com/epic-heroku/libgirepository1.0-dev.tar.gz
You can see it's here:
![image](https://user-images.githubusercontent.com/178892/28372883-8d5edecc-6ca9-11e7-9160-72fb168350a5.png)

But also why would the apt version not have this? Maybe the gem does not use the packages where they are installed.

**Comment by kou** [comment]
I said
`libgirepository-1.0.so.1.0.0`
not
`libgirepository-1.0.so`.

`libgirepository-1.0.so` is just a symbolic link file. It doesn't contain real data.

**Comment by kou** [comment]
I think that `libgirepository-1.0.so.1.0.0` is included in `libgirepository-1.0` package.

**Comment by Chocksy** [comment]
Ok so i got it to work by using just the apt buildpack: https://github.com/heroku/heroku-buildpack-apt
and this Aptfile:
```
libgirepository-1.0-1
libgirepository1.0-dev
```

Though as with the previous issue i get this error when the app is starting:
```
2017-07-20T09:46:54.706042+00:00 app[sidekiq.1]: bundler: failed to load command: sidekiq (/app/vendor/bundle/ruby/2.4.0/bin/sidekiq)
2017-07-20T09:46:54.706072+00:00 app[sidekiq.1]: GObjectIntrospection::RepositoryError::TypelibNotFound: Typelib file for namespace 'Gio' (any version) not found
2017-07-20T09:46:54.706073+00:00 app[sidekiq.1]:   /app/vendor/bundle/ruby/2.4.0/gems/gobject-introspection-3.1.8/lib/gobject-introspection/loader.rb:37:in `require'
2017-07-20T09:46:54.706074+00:00 app[sidekiq.1]:   /app/vendor/bundle/ruby/2.4.0/gems/gobject-introspection-3.1.8/lib/gobject-introspection/loader.rb:37:in `load'
2017-07-20T09:46:54.706074+00:00 app[sidekiq.1]:   /app/vendor/bundle/ruby/2.4.0/gems/gio2-3.1.8/lib/gio2.rb:39:in `<module:Gio>'
2017-07-20T09:46:54.706075+00:00 app[sidekiq.1]:   /app/vendor/bundle/ruby/2.4.0/gems/gio2-3.1.8/lib/gio2.rb:29:in `<top (required)>'
2017-07-20T09:46:54.706076+00:00 app[sidekiq.1]:   /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
2017-07-20T09:46:54.706076+00:00 app[sidekiq.1]:   /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
2017-07-20T09:46:54.706077+00:00 app[sidekiq.1]:   /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
2017-07-20T09:46:54.706078+00:00 app[sidekiq.1]:   /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
2017-07-20T09:46:54.706078+00:00 app[sidekiq.1]:   /app/vendor/bundle/ruby/2.4.0/gems/rsvg2-3.1.8/lib/rsvg2.rb:19:in `<top (required)>'
2017-07-20T09:46:54.706079+00:00 app[sidekiq.1]:   /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:82:in `require'
2017-07-20T09:46:54.706080+00:00 app[sidekiq.1]:   /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
2017-07-20T09:46:54.706080+00:00 app[sidekiq.1]:   /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:77:in `each'
2017-07-20T09:46:54.706081+00:00 app[sidekiq.1]:   /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:77:in `block in require'
2017-07-20T09:46:54.706082+00:00 app[sidekiq.1]:   /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:66:in `each'
2017-07-20T09:46:54.706082+00:00 app[sidekiq.1]:   /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:66:in `require'
2017-07-20T09:46:54.706083+00:00 app[sidekiq.1]:   /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler.rb:108:in `require'
2017-07-20T09:46:54.706084+00:00 app[sidekiq.1]:   /app/config/application.rb:7:in `<top (required)>'
2017-07-20T09:46:54.706084+00:00 app[sidekiq.1]:   /app/config/environment.rb:2:in `require_relative'
2017-07-20T09:46:54.706085+00:00 app[sidekiq.1]:   /app/config/environment.rb:2:in `<top (required)>'
2017-07-20T09:46:54.706085+00:00 app[sidekiq.1]:   /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/cli.rb:257:in `require'
2017-07-20T09:46:54.706086+00:00 app[sidekiq.1]:   /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/cli.rb:257:in `boot_system'
2017-07-20T09:46:54.706087+00:00 app[sidekiq.1]:   /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/cli.rb:54:in `run'
2017-07-20T09:46:54.706087+00:00 app[sidekiq.1]:   /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.4/bin/sidekiq:12:in `<top (required)>'
2017-07-20T09:46:54.706088+00:00 app[sidekiq.1]:   /app/vendor/bundle/ruby/2.4.0/bin/sidekiq:22:in `load'
2017-07-20T09:46:54.706088+00:00 app[sidekiq.1]:   /app/vendor/bundle/ruby/2.4.0/bin/sidekiq:22:in `<top (required)>'
```

It seems as with #900 it is the same error. Didn't this get fixed in the new versions? Why does it still happen?

**Comment by kou** [comment]
It's not related.
You need to add the directory that has `*.typelib` file such as `Gio-2.0.typelib` to `GI_TYPELIB_PATH` environment variable.

**Comment by Chocksy** [comment]
I tried to set the variable `GI_TYPELIB_PATH ` to `/app/.apt/usr/lib/x86_64-linux-gnu/libgirepository-1.0.a` 
Here is where i have the packages:
![we](http://take.ms/IKZID)

But i still get the same error.

**Comment by Chocksy** [comment]
I actually looked in the gobject-introspection where girepository-1.0 should be and it does not seem to have it using the apt-get install.

I see in this repo that this has that https://github.com/respeaker/respeaker-feed/tree/master/gobject-introspection/files/usr/lib

**Comment by kou** [comment]
Again, you need to specify "directory" to `GI_TYPELIB_PATH`. It's not a file. 
Maybe, `Gio-2.0.typelib` is included in `gir1.2-glib-2.0` package.

**Comment by Chocksy** [comment]
OK it finally works. Thanks for the help @kou.
Here is what i made for rsvg2 to work on heroku cedar-16:

- Add buildpack apt to your app: `heroku buildpacks:add --index 1 https://github.com/heroku/heroku-buildpack-apt.git`
- Add `Aptfile` to your rails root directory.
- Include in the `Aptfile` the following packages:
  ```
  gir1.2-gdkpixbuf-2.0
  gir1.2-glib-2.0
  libgirepository-1.0-1
  libgirepository1.0-dev
  ```
- In your gemfile add 
  ```
   gem 'rsvg2', '~> 3.0.9'
   gem 'gobject-introspection', '~> 3.0.9'
   gem 'gio2', '~> 3.0.9'
  ```
- Add the following ENV var: `GI_TYPELIB_PATH = /app/.apt/usr/lib/x86_64-linux-gnu/girepository-1.0`

It should all be working now.

I did not manage to get the last version of rsvg2 3.1.8 to work. It seems to require different typelibs for that one.

**Comment by kou** [comment]
Thanks for the summary. How about creating document for Heroku under https://github.com/ruby-gnome2/ruby-gnome2/tree/master/doc ?



> I did not manage to get the last version of rsvg2 3.1.8 to work. It seems to require different typelibs for that one.

`gir1.2-rsvg-2.0` will be what you need.

**Comment by Chocksy** [comment]
@kou i'll make a PR with that. 
I did add that package but now i get this error if i try with the last version: `GObjectIntrospection::RepositoryError::TypelibNotFound: Typelib file for namespace 'cairo', version '1.0' not found`

I tried to install cairo and libcairo2 but it does not solve it. I also tried libcairo-gobject2

**Comment by Chocksy** [comment]
I searched through the packages but i could not find a typelib named cairo. Maybe i'm missing something again.

**Comment by Chocksy** [comment]
I made an initial PR with the details above but i'll update it once this above issue is resolved i guess.
https://github.com/ruby-gnome2/ruby-gnome2/pull/1071

**Comment by kou** [comment]
`gir1.2-freedesktop` includes `cairo-1.0.typelib`.

**Comment by Chocksy** [comment]
Ok with that it seems to be working. The code also works. So it's all good. I also updated the PR with the details.

Thanks a lot @kou for the help!!

**Comment by kou** [comment]
:)
