### ISSUE TITLE
Poppler test-constants error

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#1082]
In the test-constants file, when I run the tests, I have the following error message : 

```
./run-test.rb -t TestConstants
/home/cedlemo/.gem/ruby/2.4.0/gems/gobject-introspection-3.1.9/lib/gobject-introspection/loader.rb:166: warning: Invalid constant name '3D' - skipped
/home/cedlemo/.gem/ruby/2.4.0/gems/gobject-introspection-3.1.9/lib/gobject-introspection/loader.rb:166: warning: Invalid constant name '3D' - skipped
/home/cedlemo/.gem/ruby/2.4.0/gems/gobject-introspection-3.1.9/lib/gobject-introspection/loader.rb:166: warning: Invalid constant name '0' - skipped
/home/cedlemo/.gem/ruby/2.4.0/gems/gobject-introspection-3.1.9/lib/gobject-introspection/loader.rb:166: warning: Invalid constant name '90' - skipped
/home/cedlemo/.gem/ruby/2.4.0/gems/gobject-introspection-3.1.9/lib/gobject-introspection/loader.rb:166: warning: Invalid constant name '180' - skipped
/home/cedlemo/.gem/ruby/2.4.0/gems/gobject-introspection-3.1.9/lib/gobject-introspection/loader.rb:166: warning: Invalid constant name '270' - skipped
Loaded suite test
Started
/home/cedlemo/Projets/Ruby/ruby-gnome2/poppler/test/test-constants.rb:4:in `test_annotation': 'Poppler::AnnotationType' has been deprecated. Use 'Poppler::AnnotType'.
E
============================================================================================================================================================================
Error: test_annotation(TestConstants): NameError: uninitialized constant Poppler::AnnotType::TYPE_3D
/home/cedlemo/Projets/Ruby/ruby-gnome2/poppler/test/test-constants.rb:4:in `test_annotation'
     1: class TestConstants < Test::Unit::TestCase
     2:   def test_annotation
     3:     assert_const_defined(Poppler, :AnnotType)
  => 4:     assert_equal("3d", Poppler::AnnotationType::TYPE_3D.nick)
     5:     assert_const_defined(Poppler, :AnnotFlag)
     6:     assert_const_defined(Poppler, :AnnotMarkupReplyType)
     7:     assert_const_defined(Poppler, :AnnotExternalDataType)

```

I tried to rename the constants name in the `loader.rb` file in the following functions : 

* load_enum_value
* load_enum_info
* define_enum 

but without success. Furthermore, I saw that the error message `warning: Invalid constant name '3D' - skipped` came from the file *glib2/ext/glib2/rbgobj_enumflags.c* : 

```
void
rbgobj_define_const(VALUE mod, const char *name,
			VALUE value)
{
    if (name[0] >= 'A' && name[0] <= 'Z') {
        rb_define_const(mod, name, value);
    } else {
        char *new_name = rg_obj_constant_lookup(name);

        if (new_name) {
            rb_define_const(mod, new_name, value);
            g_free(new_name);
        } else {
            rb_warn("Invalid constant name '%s' - skipped", name);
        }
    }
}
```

I was not able to create a patch for this sorry.

**Comment by kou** [comment]
I've implemented.
We can use `GObjectIntrospection::Loader.register_constant_rename_map` to rename constant name.
