### ISSUE TITLE
Test failures with webkit 2.17.90

### ISSUE THREAD

**Issue by jbicha** [ruby-gnome2/ruby-gnome2#1095]
I recently uploaded webkit2gtk 2.17.90 to Ubuntu 17.10 Alpha. webkit2gtk follows GNOME's [release schedule](https://wiki.gnome.org/ThreePointTwentyfive) so this is a beta version with the final release coming next month.

ruby-gnome2's tests are failing with the new version. (The new version of webkit2gtk is in artful-proposed; it's being blocked from migrating to the regular artful repositories because of this issue.)

You can see the full log at http://autopkgtest.ubuntu.com/packages/r/ruby-gnome2/artful/amd64
I just search for the string "Failure:"

Here's an excerpt:
```
===============================================================================
Failure: <#<WebKit2Gtk::UserContentManager:0xc94d814e78 ptr=0xc94e6aa530>> was expected
 to be nil.
test: with context(TestWebKit2GtkWebView::.new::Hash form)
/tmp/autopkgtest.Qr6CTz/build.vNp/ruby-gnome2-3.1.8/webkit2-gtk/test/
test-webkit2-gtk-web-view.rb:27:in `block (3 levels) in <class:TestWebKit2GtkWebView>'
     24:         context = WebKit2Gtk::WebContext.new
     25:         webview = WebKit2Gtk::WebView.new(context: context)
     26:         assert_equal(context, webview.context)
  => 27:         assert_nil(webview.user_content_manager)
     28:       end
     29: 
     30:       test "with settings" do
===============================================================================
E
===============================================================================
Error: test: with related view(TestWebKit2GtkWebView::.new::Hash form): NoMethodError:
undefined method `new_with_related_view' for #<WebKit2Gtk::WebView:0xc94d12b918
ptr=0xc94d6ca930>
/tmp/autopkgtest.Qr6CTz/build.vNp/ruby-gnome2-3.1.8/webkit2-gtk/test/
test-webkit2-gtk-web-view.rb:46:in `block (3 levels) in <class:TestWebKit2GtkWebView>'
===============================================================================
F
===============================================================================
Failure: <#<WebKit2Gtk::UserContentManager:0xc94d2dbec0 ptr=0xc94d787590>> was
 expected to be nil.
test: with settings(TestWebKit2GtkWebView::.new::Hash form)
/tmp/autopkgtest.Qr6CTz/build.vNp/ruby-gnome2-3.1.8/webkit2-gtk/test/
test-webkit2-gtk-web-view.rb:34:in `block (3 levels) in <class:TestWebKit2GtkWebView>'
     31:         settings = WebKit2Gtk::Settings.new
     32:         webview = WebKit2Gtk::WebView.new(settings: settings)
     33:         assert_equal(settings, webview.settings)
  => 34:         assert_nil(webview.user_content_manager)
     35:       end
     36: 
     37:       test "with user content manager" do
===============================================================================
```

**Comment by kou** [comment]
Thanks for your report.
Maybe, I've fixed them.

**Comment by jbicha** [comment]
Thank you. That appears to work here too!
