### ISSUE TITLE
Vte::Regex#new and the PCRE2 flags.

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#1100]
@kou,

it seems that in fact the `Vte::Regex#new` need PCRE2 flags. For example in my little terminal, when I use `Vte::Regex` instead of `GLib::Regex`,  : 

```
@regexes.each do |name|
       regex_name = TopinambourRegex.const_get(name)
       flags = [:optimize,
                :multiline]
      if Vte::Regex
         regex = Vte::Regex.new(regex_name, flags, :for_match => true)
         match_add_regex(regex, 0)
       else
         regex = GLib::Regex.new(regex_name, :compile_options => flags)
         match_add_gregex(regex, 0)
       end
      end
    end
```

I have the following warning:

```
Vte-WARNING **: (vtegtk.cc:1735):int vte_terminal_match_add_regex(VteTerminal*, VteRegex*, guint32): runtime check failed: (_vte_regex_get_compile_flags(regex) & PCRE2_MULTILINE)
	from /home/cedlemo/.gem/ruby/2.4.0/gems/gobject-introspection-3.1.9/lib/gobject-introspection/loader.rb:576:in `block in define_method'
	from /home/cedlemo/Projets/Ruby/topinambour/lib/terminal.rb:164:in `block in add_matches'
	from /home/cedlemo/Projets/Ruby/topinambour/lib/terminal.rb:153:in `each'
	from /home/cedlemo/Projets/Ruby/topinambour/lib/terminal.rb:153:in `add_matches'
	from /home/cedlemo/Projets/Ruby/topinambour/lib/terminal.rb:146:in `configure'
	from /home/cedlemo/Projets/Ruby/topinambour/lib/terminal.rb:61:in `initialize'
	from /home/cedlemo/Projets/Ruby/topinambour/lib/terminal.rb:25:in `new'
	from /home/cedlemo/Projets/Ruby/topinambour/lib/terminal.rb:25:in `initialize'
	from /home/cedlemo/Projets/Ruby/topinambour/lib/window.rb:39:in `new'
	from /home/cedlemo/Projets/Ruby/topinambour/lib/window.rb:39:in `add_terminal'
	from /home/cedlemo/Projets/Ruby/topinambour/lib/application.rb:47:in `block in initialize'
	from /home/cedlemo/.gem/ruby/2.4.0/gems/gobject-introspection-3.1.9/lib/gobject-introspection/loader.rb:576:in `invoke'
	from /home/cedlemo/.gem/ruby/2.4.0/gems/gobject-introspection-3.1.9/lib/gobject-introspection/loader.rb:576:in `block in define_method'
	from /home/cedlemo/Projets/Ruby/topinambour/lib/application.rb:65:in `block in initialize'
	from /home/cedlemo/.gem/ruby/2.4.0/gems/gobject-introspection-3.1.9/lib/gobject-introspection/loader.rb:576:in `invoke'
	from /home/cedlemo/.gem/ruby/2.4.0/gems/gobject-introspection-3.1.9/lib/gobject-introspection/loader.rb:576:in `block in define_method'
	from ./bin/topinambour:60:in `<main>'
``` 

Then after reading the doc (https://developer.gnome.org/vte/0.48/VteRegex.html#vte-regex-new-for-match) and the sources of gnome-terminal (
https://github.com/GNOME/gnome-terminal/commit/1a94499aca8f9a06479f5149e70e246bf9249ac0#diff-04078b10b2b71b4abbb0aa5fed88dc70) it appears that : 

* `Vte::Regex.new` does not want `GLib::RegexCompileFlags` but PCRE2 flags
* that those flags does not exist under Ruby-GNOME2

I modified my terminal with this (the hexadecimal values come from *ocre2.h* ): 

```
diff --git a/lib/terminal.rb b/lib/terminal.rb
index 8095343..2c9c8ea 100644
--- a/lib/terminal.rb
+++ b/lib/terminal.rb
@@ -155,6 +155,11 @@ class TopinambourTerminal < Vte::Terminal
       flags = [:optimize,
                :multiline]
       if Vte::Regex
+        # PCRE2_UTF | PCRE2_NO_UTF_CHECK | PCRE2_MULTILINE
+        pcre2_utf = "0x00080000".to_i(16)
+        pcre2_no_utf_check = "0x40000000".to_i(16)
+        pcre2_multiline = "0x00000400".to_i(16)
+        flags = pcre2_utf | pcre2_no_utf_check | pcre2_multiline
         regex = Vte::Regex.new(regex_name, flags, :for_match => true)
         match_add_regex(regex, 0)
       else
```
and I have no warnings.

Is there a better way to use the PCRE2 flags (we will have to modify the tests (https://github.com/ruby-gnome2/ruby-gnome2/blob/master/vte3/test/test-regex.rb).

**Comment by kou** [comment]
Oh...
How about asking to VTE developers? We need GObject Introspection-available flags instead of direct PCRE2 flags for bindings. VTE developers may help us for the situation.

I think that `VteRegex` supports `GRegex`'s flags is an option...

**Comment by cedlemo** [comment]
> How about asking to VTE developers?

Of course, I will see with them. I hope that they will be more enthusiastic than the pango developers (I still have 2 or 3 pendings patches and bug requests.).

**Comment by kou** [comment]
OK.
We will provide PCRE flags in `Vte`. The issue on GNOME/vte can be closed.

Thanks for reporting this to upstream!
