### ISSUE TITLE
Cannot call Gio::InputStream#read_all

### ISSUE THREAD

**Issue by paulvt** [ruby-gnome2/ruby-gnome2#1110]
Although `#read` and `#read_all` on `Gio::InputStream` have the same signature, I can call `#read` but not `#read_all`:

```
got exception: no implicit conversion of Fixnum into Array (TypeError)
backtrace:
| /usr/lib/ruby/vendor_ruby/gobject-introspection/loader.rb:520:in `invoke'
| /usr/lib/ruby/vendor_ruby/gobject-introspection/loader.rb:520:in `block in define_method'
| script/gio-test.rb:161:in `handle_server_connection'
| script/gio-test:135:in `block (2 levels) in start_server'
```

I am not sure if this is an issue in Ruby GNOME2 or in the GIR data?

**Comment by kou** [comment]
Please provide a script that reproduces the problem.

**Comment by paulvt** [comment]
This is an example script that I came up with:

```ruby
#!/usr/bin/env ruby

require "glib2"
require "gio2"

mainloop = GLib::MainLoop.new(nil, true)

ss = Gio::SocketService.new
ss.signal_connect("incoming") do |_, conn, _|
  input = conn.input_stream.read(4)     # Works
  puts "read(4): #{input}"
  input = conn.input_stream.read_all(4) # Doesn't work
  puts "read all(4): #{input}"
end

ss.add_inet_port(4321)
ss.start

puts "running..."
mainloop.run
```

When using telnet to port 4321 and send some random input I get:

```
running...
read: adfa
/usr/lib/ruby/vendor_ruby/gobject-introspection/loader.rb:519:in `invoke': no implicit conversion of Fixnum into Array
	 from /usr/lib/ruby/vendor_ruby/gobject-introspection/loader.rb:519:in `block in define_method'
	 from test-gio.rb:12:in `block in <main>'
	 from test-gio.rb:20:in `run'
	 from test-gio.rb:20:in `<main>'
```

**Comment by kou** [comment]
Thanks.
I've implemented.
