### ISSUE TITLE
gtk_drag_get_source_widget in Ruby

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#1115]
@kou,

I am working on the *toolpalette.c* demo adaptation in Ruby, but I am stuck with the function
[ `gtk_drag_get_source_widget` ](https://developer.gnome.org/gtk3/stable/gtk3-Drag-and-Drop.html#gtk-drag-get-source-widget). I can not find it under `Gtk` or `Gtk::Drag`. 

```
irb(main):002:0> Gtk::Drag.methods.grep(/source/)
=> [:source_set, :source_set_icon, :source_set_icon_name, :source_unset, :source_set_target_list, :source_get_target_list, :source_add_text_targets, :source_add_image_targets, :source_add_uri_targets]
irb(main):003:0> Gtk.methods.grep(/source/)
=> []
irb(main):004:0> 
```

Any idea ?

**Comment by kou** [comment]
You can find it at `Gdk::DragContext#source_width` with master.

**Comment by kou** [comment]
NOTE: It's `Gdk` not `Gtk`.

**Comment by cedlemo** [comment]
@kou,

after the update of my local copy, I can not run any demo from the command line:

```
./main.rb -r css_blendmodes
ArgumentError: the 2nd argument must not nil: <start_editing>
/home/cedlemo/.gem/ruby/2.4.0/gems/gobject-introspection-3.2.2/lib/gobject-introspection/loader.rb:583:in `invoke'
/home/cedlemo/.gem/ruby/2.4.0/gems/gobject-introspection-3.2.2/lib/gobject-introspection/loader.rb:583:in `block in define_method'
./main.rb:200:in `select_treeview_item'
./main.rb:397:in `run_application'
./main.rb:257:in `block in initialize'
/home/cedlemo/.gem/ruby/2.4.0/gems/gobject-introspection-3.2.2/lib/gobject-introspection/loader.rb:583:in `invoke'
/home/cedlemo/.gem/ruby/2.4.0/gems/gobject-introspection-3.2.2/lib/gobject-introspection/loader.rb:583:in `block in define_method'
./main.rb:276:in `block in initialize'
/home/cedlemo/.gem/ruby/2.4.0/gems/gobject-introspection-3.2.2/lib/gobject-introspection/loader.rb:583:in `invoke'
/home/cedlemo/.gem/ruby/2.4.0/gems/gobject-introspection-3.2.2/lib/gobject-introspection/loader.rb:583:in `block in define_method'
./main.rb:518:in `<main>'
```

I will try to see why.

**Comment by kou** [comment]
It's a bug of `gtk-demo`.
I've fixed it.
