### ISSUE TITLE
Gstreamer Pipeline and Elements in it not unref'ed properly after MainLoop.quit?

### ISSUE THREAD

**Issue by KaiKruschel** [ruby-gnome2/ruby-gnome2#1130]
Hi,
I am trying to stream video received from a custom network camera source over the network to a different computer. 
Building the pipeline works great. When I start the GLib main loop, the pipeline's ref_count goes up to 7, which is expected. However after main_loop.quit the ref_count should go back down. Printing the pipeline's ref_count property shows it still at 7.

The problem I have is that the network camera I work with has a locking mechanism that gets released in the source elements finalize function. 

So as long as the source element does not get properly unref'ed and freed, the cameras lock is not released until the whole process is terminated. Since this is going to be part of a server, terminating the process to release the camera is not a good option.

The code below opens a videotestsrc, outputs it over an autovideosink and after closing that window goes into an idle loop. 

I tested the code with ruby v 2.1.0 and 2.2.5

A C Script from which this is adapted and a Python Script adapted from that C code work as expected with the restriction that in Python calling unref on the pipeline is not enough, I have to explicitly call unref on the source element directly as well.

I spent quite some time trying to debug this and would greatly appreciate if you could have a look and see if this is a problem with the bindings themselves or if this is a problem with me using them in a wrong way. 

all the best,
Kai

```ruby
require "gst"

# Example adapted from the Gstreamer 1.0 C Hello World example

def build_pipeline()

  main_loop = GLib::MainLoop.new(nil, false);


  #  /* Create gstreamer elements */
  pipeline = Gst::Pipeline.new()
  source   = Gst::ElementFactory.make("videotestsrc")
  capsfilter = Gst::ElementFactory.make("capsfilter")
  caps = Gst::caps_from_string("video/x-bayer")
  capsfilter.caps = caps
  rgb_conv = Gst::ElementFactory.make("bayer2rgb")
  conv     = Gst::ElementFactory.make("videoconvert")
  sink     = Gst::ElementFactory.make("autovideosink")

  if (not pipeline or not source or not capsfilter or not conv or not sink) 
    puts("One element could not be created. Exiting.\n")
    return -1
  end

  #  /* Set up the pipeline */

  #  /* we add a message handler */
  bus = pipeline.bus
  bus.add_watch do |bus_name, message|
    #puts "starting event handler"
    ret_val = true
    case message.type
    when Gst::MessageType::EOS
      puts "End of Stream"
      pipeline.stop
      main_loop.quit
      ret_val = false
    when Gst::MessageType::ERROR
      puts "Error"
      puts "Error Parsed" 
      puts "pipe error 1 ref count: #{pipeline.ref_count}" 
      pipeline.stop
      main_loop.quit
      puts "pipe error 2 ref count: #{pipeline.ref_count}" 
      puts "Quit Main Loop"
      ret_val = false
    end
    ret_val 
  end

  #  /* we add all elements into the pipeline */
  pipeline.add(source)
  pipeline.add(capsfilter)
  pipeline.add(rgb_conv)
  pipeline.add(conv)
  pipeline.add(sink)

  #/* we link the elements together */
  source >> capsfilter
  capsfilter >> rgb_conv
  rgb_conv >> conv
  conv >> sink


  #/* Set the pipeline to "playing" state*/
  pipeline.set_state(Gst::State::PLAYING)


  #/* Iterate */
  puts("Running...\n")
  main_loop.run() 


  #/* Out of the main loop, clean up nicely */
  puts("Returned, stopping playback\n")
  pipeline.set_state(Gst::State::NULL)
  
  puts("building: pipe 1 ref count: ", pipeline.ref_count)
  puts("building: source 1 ref count: ", source.ref_count)

  puts("Deleting source\n")
  source.unref()
  puts("building: source 2 ref count: ", source.ref_count)
  source = nil

  puts("Deleting pipeline\n")
  pipeline.unref()
  puts("build pipe 2 ref count: ", pipeline.ref_count)
  
  pipeline = nil
  
  true 
end

def main (argc, argv)

  #/* Initialisation */
  Gst.init
  ret_val = build_pipeline

  i = 0
  while(1) 
    sleep(1)
    puts("Empty loop no. #{i}")
    i+=1
  end
end

main(nil, nil)
```

**Comment by kou** [comment]
You should not call `unref` by yourself.
If you want to force to free unused objects, use `GC.start`.
But GC may not free all unused objects at once. You may need to run `GC.start` later.

The following modified Ruby scripts show that the number of `Gst::Pipeline` objects is `1`. It means that unused `Gst::Pipelne` objects are freed by GC eventually.

```ruby
require "gst"

# Example adapted from the Gstreamer 1.0 C Hello World example

def build_pipeline()

  main_loop = GLib::MainLoop.new(nil, false);


  #  /* Create gstreamer elements */
  pipeline = Gst::Pipeline.new()
  source   = Gst::ElementFactory.make("videotestsrc")
  capsfilter = Gst::ElementFactory.make("capsfilter")
  caps = Gst::caps_from_string("video/x-bayer")
  capsfilter.caps = caps
  rgb_conv = Gst::ElementFactory.make("bayer2rgb")
  conv     = Gst::ElementFactory.make("videoconvert")
  sink     = Gst::ElementFactory.make("autovideosink")

  if (not pipeline or not source or not capsfilter or not conv or not sink) 
    puts("One element could not be created. Exiting.\n")
    return -1
  end

  #  /* Set up the pipeline */

  #  /* we add a message handler */
  bus = pipeline.bus
  bus.add_watch do |bus_name, message|
    #puts "starting event handler"
    ret_val = true
    case message.type
    when Gst::MessageType::EOS
      puts "End of Stream"
      pipeline.stop
      main_loop.quit
      ret_val = false
    when Gst::MessageType::ERROR
      puts "Error"
      puts "Error Parsed" 
      puts "pipe error 1 ref count: #{pipeline.ref_count}" 
      pipeline.stop
      main_loop.quit
      puts "pipe error 2 ref count: #{pipeline.ref_count}" 
      puts "Quit Main Loop"
      ret_val = false
    end
    ret_val 
  end

  #  /* we add all elements into the pipeline */
  pipeline.add(source)
  pipeline.add(capsfilter)
  pipeline.add(rgb_conv)
  pipeline.add(conv)
  pipeline.add(sink)

  #/* we link the elements together */
  source >> capsfilter
  capsfilter >> rgb_conv
  rgb_conv >> conv
  conv >> sink


  #/* Set the pipeline to "playing" state*/
  pipeline.set_state(Gst::State::PLAYING)


  #/* Iterate */
  puts("Running...\n")
  main_loop.run() 


  #/* Out of the main loop, clean up nicely */
  puts("Returned, stopping playback\n")
  pipeline.set_state(Gst::State::NULL)
  
  puts("building: pipe 1 ref count: ", pipeline.ref_count)
  puts("building: source 1 ref count: ", source.ref_count)

  puts("Deleting source\n")
  # source.unref()
  puts("building: source 2 ref count: ", source.ref_count)
  source = nil

  puts("Deleting pipeline\n")
  # pipeline.unref()
  puts("build pipe 2 ref count: ", pipeline.ref_count)
  
  pipeline = nil
  
  true 
end

def main (argc, argv)
  #/* Initialisation */
  ret_val = build_pipeline

  i = 0
  while(1)
    GC.start
    p [:n_pipelines, ObjectSpace.each_object(Gst::Pipeline) {}]
    break
    sleep(1)
    puts("Empty loop no. #{i}")
    i+=1
  end
end

Gst.init

10.times do
  main(nil, nil)
end
```

**Comment by KaiKruschel** [comment]
Hello Kou,
I tried your modifications. 
Unfortunately my problem with the source element not being reliably unreferenced persists despite the repeated calls to GC.start. This results in the first loop working and subsequent loops failing, because the camera remains locked. 

I suppose this is a somewhat niche problem and might be unique to the source element I am using. 

The source used is the Aravis Project's Gstreamer plugin. 

Is there any way to force the finalize on a GObject in Ruby? Or is it simply that Ruby is not a good fit for this particular usecase?

**Comment by kou** [comment]
Can you try this?

```ruby
require "gst"

# Example adapted from the Gstreamer 1.0 C Hello World example

def build_pipeline()

  main_loop = GLib::MainLoop.new(nil, false);


  #  /* Create gstreamer elements */
  pipeline = Gst::Pipeline.new()
  source   = Gst::ElementFactory.make("videotestsrc")
  capsfilter = Gst::ElementFactory.make("capsfilter")
  caps = Gst::caps_from_string("video/x-bayer")
  capsfilter.caps = caps
  rgb_conv = Gst::ElementFactory.make("bayer2rgb")
  conv     = Gst::ElementFactory.make("videoconvert")
  sink     = Gst::ElementFactory.make("autovideosink")

  if (not pipeline or not source or not capsfilter or not conv or not sink) 
    puts("One element could not be created. Exiting.\n")
    return -1
  end

  #  /* Set up the pipeline */

  #  /* we add a message handler */
  bus = pipeline.bus
  bus.add_watch do |bus_name, message|
    #puts "starting event handler"
    ret_val = true
    case message.type
    when Gst::MessageType::EOS
      puts "End of Stream"
      pipeline.stop
      main_loop.quit
      ret_val = false
    when Gst::MessageType::ERROR
      puts "Error"
      puts "Error Parsed" 
      puts "pipe error 1 ref count: #{pipeline.ref_count}" 
      pipeline.stop
      main_loop.quit
      puts "pipe error 2 ref count: #{pipeline.ref_count}" 
      puts "Quit Main Loop"
      ret_val = false
    end
    ret_val 
  end

  #  /* we add all elements into the pipeline */
  pipeline.add(source)
  pipeline.add(capsfilter)
  pipeline.add(rgb_conv)
  pipeline.add(conv)
  pipeline.add(sink)

  #/* we link the elements together */
  source >> capsfilter
  capsfilter >> rgb_conv
  rgb_conv >> conv
  conv >> sink


  #/* Set the pipeline to "playing" state*/
  pipeline.set_state(Gst::State::PLAYING)


  #/* Iterate */
  puts("Running...\n")
  main_loop.run() 


  #/* Out of the main loop, clean up nicely */
  puts("Returned, stopping playback\n")
  pipeline.set_state(Gst::State::NULL)
  
  puts("building: pipe 1 ref count: ", pipeline.ref_count)
  puts("building: source 1 ref count: ", source.ref_count)

  puts("Deleting source\n")
  source.unref()
  puts("building: source 2 ref count: ", source.ref_count)
  source = nil

  puts("Deleting pipeline\n")
  # pipeline.unref()
  puts("build pipe 2 ref count: ", pipeline.ref_count)
  
  pipeline = nil
  
  true 
end

def main (argc, argv)
  #/* Initialisation */
  ret_val = build_pipeline

  i = 0
  while(1)
    GC.start
    p [:n_pipelines, ObjectSpace.each_object(Gst::Pipeline) {}]
    break
    sleep(1)
    puts("Empty loop no. #{i}")
    i+=1
  end
end

Gst.init

Gst::Object.send(:remove_method, :unref)

10.times do
  main(nil, nil)
end
```

Changes:

  * `Gst::Object#unref` is removed.
  * `source.unref` is uncommented.

**Comment by KaiKruschel** [comment]
Unfortunately changing the source to aravissrc still exhibits the same behaviour. The first iteration runs fine also now showing the refcount of the source element to be 0. However the second iteration and after show GLib-GObject-CRITICAL Error on line 71. This is the main_loop.run() in build_pipeline. The precise Text is 
``GLib-GObject-CRITICAL **: g_object_set: assertion 'G_IS_OBJECT (object)' failed``

``	from pipe_build_test.rb:71:in `build_pipeline'``
``	from pipe_build_test.rb:97:in `main'``
``	from pipe_build_test.rb:115:in `block in <main>'``
	``from pipe_build_test.rb:114:in `times'``
	``from pipe_build_test.rb:114:in `<main>'``  

followed by a couple times 
`(pipe_build_test.rb:13978): Aravis-CRITICAL **: arv_stream_push_buffer: assertion 'ARV_IS_STREAM (stream)' failed` 
which I assume would be a result of the source not being created properly due to not getting a lock on the camera.
