### ISSUE TITLE
ruby-gstreamer: Overflow of nanoseconds on 32-bit platforms

### ISSUE THREAD

**Issue by dai-vdr** [ruby-gnome2/ruby-gnome2#1137]
forwarded from: https://bugs.debian.org/766020

-----

Querying position and duration information on a 32-bit platform
is more or less completely useless, since the unit of time
returned by GStreamer is nanoseconds, which does not fit (and therefore
overflow and wrap) into a 32-bit value:

```ruby
require 'gst'

bin = Gst::parse_launch("playbin")
bin.uri = 'http://delysid.org/music/delYsid-delUxe.ogg'
bin.play
sleep 1
result, dur = bin.query_duration(Gst::Format::TIME)
puts dur
```

On this 32-bit system, I get:

-1010310203

which nicely confirms the overflow.

I am actually not sure if this is a problem with GStreamer API, or with
the GStreamer Ruby bindings.  I am filing against the Ruby bindings
because this is where I noticed the bug.

Note that everything works fine on a 64-bit platform.

----

Unfortunately I know very little about gstreamer itself, so I end up
having a hard time reproducing your issue. Right now I only get
this:

```
/usr/lib/ruby/vendor_ruby/gobject-introspection/loader.rb:87:in `invoke': no element "playbin" (Gst::ParseError::NoSuchElement)
  from /usr/lib/ruby/vendor_ruby/gobject-introspection/loader.rb:87:in `block (2 levels) in define_module_function'
  from /usr/lib/ruby/vendor_ruby/gst.rb:51:in `method_missing'
  from foo.rb:2:in `<main>'
```

Maybe you can come up with a more complete sample (i.e. what
other packages are needed).

(I /think/ the issue lies more in (ruby-)gobject-introspection than
in ruby-gstreamer itself, but hard to say without seeing more.)

**Comment by cedlemo** [comment]
Just by curiosity, could you show in the /usr/share/gir-1.0/Gst-1.0 file the following part : 

```xml
      <method name="query_duration" c:identifier="gst_element_query_duration">
        <doc xml:space="preserve">Queries an element (usually top-level pipeline or playbin element) for the
total stream duration in nanoseconds. This query will only work once the
pipeline is prerolled (i.e. reached PAUSED or PLAYING state). The application
will receive an ASYNC_DONE message on the pipeline bus when that is the case.

If the duration changes for some reason, you will get a DURATION_CHANGED
message on the pipeline bus, in which case you should re-query the duration
using this function.</doc>
        <return-value transfer-ownership="none">
          <doc xml:space="preserve">%TRUE if the query could be performed.</doc>
          <type name="gboolean" c:type="gboolean"/>
        </return-value>
        <parameters>
          <instance-parameter name="element" transfer-ownership="none">
            <doc xml:space="preserve">a #GstElement to invoke the duration query on.</doc>
            <type name="Element" c:type="GstElement*"/>
          </instance-parameter>
          <parameter name="format" transfer-ownership="none">
            <doc xml:space="preserve">the #GstFormat requested</doc>
            <type name="Format" c:type="GstFormat"/>
          </parameter>
          <parameter name="duration"
                     direction="out"
                     caller-allocates="0"
                     transfer-ownership="full"
                     optional="1"
                     allow-none="1">
            <doc xml:space="preserve">A location in which to store the total duration, or %NULL.</doc>
            <type name="gint64" c:type="gint64*"/>
          </parameter>
        </parameters>
      </method>
```

On my 64-bit system the out parameter "duration" is a gint64. If on your 32 bit system it is a gint32 then the problem does not lies in gobejct-introspection.

**Comment by kou** [comment]
Thanks for forwarding it.
I've fixed it.
