### ISSUE TITLE
mikutter 3.6.5 does not start with ruby-gnome2 3.2.2 and 3.2.3

### ISSUE THREAD

**Issue by dai-vdr** [ruby-gnome2/ruby-gnome2#1154]
forwarded from https://bugs.debian.org/894816 and https://dev.mikutter.hachune.net/issues/1199

----

mikutter 3.6.5 does not start with ruby-gnome2 3.2.2 and 3.2.3.

```
$ mikutter 
Traceback (most recent call last):
	54: from /usr/share/mikutter/mikutter.rb:42:in `<main>'
	53: from /usr/share/mikutter/core/miquire.rb:18:in `miquire'
	52: from /usr/share/mikutter/core/miquire.rb:75:in `miquire'
	51: from /usr/share/mikutter/core/miquire.rb:75:in `each'
	50: from /usr/share/mikutter/core/miquire.rb:76:in `block in miquire'
	49: from /usr/share/mikutter/core/miquire.rb:95:in `file_or_directory_require'
	48: from /usr/share/mikutter/core/miquire.rb:98:in `miquire_original_require'
	47: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	46: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	45: from /usr/share/mikutter/core/boot/load_plugin.rb:10:in `<top (required)>'
	44: from /usr/share/mikutter/core/miquire_plugin.rb:96:in `load_all'
	43: from /usr/share/mikutter/core/miquire_plugin.rb:36:in `each_spec'
	42: from /usr/share/mikutter/core/miquire_plugin.rb:33:in `each'
	41: from /usr/share/mikutter/core/miquire_plugin.rb:33:in `each'
	40: from /usr/share/mikutter/core/miquire_plugin.rb:38:in `block in each_spec'
	39: from /usr/share/mikutter/core/miquire_plugin.rb:98:in `block in load_all'
	38: from /usr/share/mikutter/core/miquire_plugin.rb:146:in `load'
	37: from /usr/share/mikutter/core/utils.rb:278:in `atomic'
	36: from /usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	35: from /usr/share/mikutter/core/utils.rb:278:in `block in atomic'
	34: from /usr/share/mikutter/core/miquire_plugin.rb:147:in `block in load'
	33: from /usr/share/mikutter/core/miquire_plugin.rb:147:in `each'
	32: from /usr/share/mikutter/core/miquire_plugin.rb:149:in `block (2 levels) in load'
	31: from /usr/share/mikutter/core/miquire_plugin.rb:146:in `load'
	30: from /usr/share/mikutter/core/utils.rb:278:in `atomic'
	29: from /usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	28: from /usr/share/mikutter/core/utils.rb:278:in `block in atomic'
	27: from /usr/share/mikutter/core/miquire_plugin.rb:147:in `block in load'
	26: from /usr/share/mikutter/core/miquire_plugin.rb:147:in `each'
	25: from /usr/share/mikutter/core/miquire_plugin.rb:149:in `block (2 levels) in load'
	24: from /usr/share/mikutter/core/miquire_plugin.rb:146:in `load'
	23: from /usr/share/mikutter/core/utils.rb:278:in `atomic'
	22: from /usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	21: from /usr/share/mikutter/core/utils.rb:278:in `block in atomic'
	20: from /usr/share/mikutter/core/miquire_plugin.rb:158:in `block in load'
	19: from /usr/share/mikutter/core/miquire_plugin.rb:158:in `load'
	18: from /usr/share/mikutter/core/plugin/gtk/gtk.rb:7:in `<top (required)>'
	17: from /usr/share/mikutter/core/miquire.rb:18:in `miquire'
	16: from /usr/share/mikutter/core/miquire.rb:75:in `miquire'
	15: from /usr/share/mikutter/core/miquire.rb:75:in `each'
	14: from /usr/share/mikutter/core/miquire.rb:76:in `block in miquire'
	13: from /usr/share/mikutter/core/miquire.rb:95:in `file_or_directory_require'
	12: from /usr/share/mikutter/core/miquire.rb:98:in `miquire_original_require'
	11: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	10: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 9: from /usr/share/mikutter/core/mui/cairo_cell_renderer_message.rb:3:in `<top (required)>'
	 8: from /usr/share/mikutter/core/miquire.rb:18:in `miquire'
	 7: from /usr/share/mikutter/core/miquire.rb:75:in `miquire'
	 6: from /usr/share/mikutter/core/miquire.rb:75:in `each'
	 5: from /usr/share/mikutter/core/miquire.rb:76:in `block in miquire'
	 4: from /usr/share/mikutter/core/miquire.rb:95:in `file_or_directory_require'
	 3: from /usr/share/mikutter/core/miquire.rb:98:in `miquire_original_require'
	 2: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/share/mikutter/core/mui/cairo_miracle_painter.rb:21:in `<top (required)>': uninitialized constant Gtk::Object (NameError)
Did you mean?  Object
```

I downgraded ruby-gnome2 from 3.2.3 to 3.2.1 and mikutter started again.

----

reverting 9b76f52c4 then mikutter starts. it seems that 9b76f52c4 introduces compatibility breakage.

**Comment by kou** [comment]
Thanks for your report.
I've fixed.

I'll release a bug fix release but this is a workaround:

```ruby
Gtk::Object = GLib::Type["GtkObject"].to_class
```
