### ISSUE TITLE
gtk-demo error: List Box

### ISSUE THREAD

**Issue by kojix2** [ruby-gnome2/ruby-gnome2#1181]
gtk-demo error report : List Box
```bash
/ruby-gnome2/gtk3/sample/gtk-demo$ ruby main.rb
```
I cannot run List Box example. 
This is the error message.
```bash
failed to run demo: ./listbox.rb
ArgumentError: <Gtk::Widget#set_visible>: the 0th argument must not nil: <visible>
gem/ruby/2.5.0/gems/gobject-introspection-3.2.6/lib/gobject-introspection/loader.rb:585:in `invoke'
gem/ruby/2.5.0/gems/gobject-introspection-3.2.6/lib/gobject-introspection/loader.rb:585:in `block in define_method'
/ruby-gnome2/gtk3/sample/gtk-demo/listbox.rb:161:in `message_row_update'
/ruby-gnome2/gtk3/sample/gtk-demo/listbox.rb:136:in `initialize'
/ruby-gnome2/gtk3/sample/gtk-demo/listbox.rb:39:in `new'
/ruby-gnome2/gtk3/sample/gtk-demo/listbox.rb:39:in `block in initialize'
/ruby-gnome2/gtk3/sample/gtk-demo/listbox.rb:37:in `each_line'
/ruby-gnome2/gtk3/sample/gtk-demo/listbox.rb:37:in `initialize'
main.rb:181:in `new'
main.rb:181:in `run_demo_from_file'
main.rb:367:in `block in run_application'
gem/ruby/2.5.0/gems/gobject-introspection-3.2.6/lib/gobject-introspection/loader.rb:585:in `invoke'
gem/ruby/2.5.0/gems/gobject-introspection-3.2.6/lib/gobject-introspection/loader.rb:585:in `block in define_method'
main.rb:518:in `<main>'
```
passing nil to function here. 
https://github.com/ruby-gnome2/ruby-gnome2/blob/11b25db03be8c8788dabd8f95f19d3703f03c5de/gtk3/sample/gtk-demo/listbox.rb#L161
https://github.com/ruby-gnome2/ruby-gnome2/blob/11b25db03be8c8788dabd8f95f19d3703f03c5de/gtk3/sample/gtk-demo/listbox.rb#L163
`@message.n_favorites` is Integer. 
`nonzero?` returns self if num is not zero, nil otherwise. (not true or false) 
So nil is passed.
`!= 0`  `!zero?` is ok in my PC. 

system:

- Ubuntu 16.04
- ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
- libgtk-3-0 3.18.9-1ubuntu3.3
- ruby gtk3 (3.2.6)

**Comment by kojix2** [comment]
I checked it. Thank you!
