### ISSUE TITLE
Installing gtk3 on windows 10 : 'missing pango.so'

### ISSUE THREAD

**Issue by glurp** [ruby-gnome2/ruby-gnome2#1189]
Hello,

```
c:\usr\local\ruby>ruiby_demo
C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- pango.so (LoadError)
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pango-3.2.5-x64-mingw32/lib/pango/loader.rb:72:in `rescue in require_extension'
```

**Comment by kou** [comment]
Can you confirm that you're using the latest cairo gem?

**Comment by glurp** [comment]
it is ok after manualy install cairo :  
```
c:\usr\local\ruby>gem install cairo
Fetching: cairo-1.15.13-x64-mingw32.gem (100%)
Successfully installed cairo-1.15.13-x64-mingw32
Parsing documentation for cairo-1.15.13-x64-mingw32
Installing ri documentation for cairo-1.15.13-x64-mingw32
Done installing documentation for cairo after 1 seconds
1 gem installed
```
Thank-you,
