### ISSUE TITLE
gtk-demo error: Printing/Printing

### ISSUE THREAD

**Issue by kojix2** [ruby-gnome2/ruby-gnome2#1193]
gtk-demo error report: Printing/Printing

system:
- Ubuntu **18.04**
- ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
- libgtk-3-0 **3.22**.30-1ubuntu1

Steps to reproduce: 
1. Run Printing/Printing Demo
```bash
ruby ruby-gnome2/gtk3/sample/gtk-demo/main.rb
```
2. The print dialog is displayed on the screen.
3. Click the [Cancel] button
4. Crash

This is the error message. 
```bash
main.rb:374:in `block in run_application': undefined method `signal_connect' for #<Gtk::PrintOperationResult cancel>
	 gem/ruby/2.5.0/gems/gobject-introspection-3.2.6/lib/gobject-introspection/loader.rb:587:in `invoke'
	 gem/ruby/2.5.0/gems/gobject-introspection-3.2.6/lib/gobject-introspection/loader.rb:587:in `block in define_method'
	 from main.rb:518:in `<main>'
```
main.rb:374 is here. 
https://github.com/ruby-gnome2/ruby-gnome2/blob/2e05cb3fa731b054c2c1ed49d94105bbab5e9e08/gtk3/sample/gtk-demo/main.rb#L374

**Comment by kojix2** [comment]
Thank you. I checked it.
