### ISSUE TITLE
 uninitialized constant Atk::Version::MAJOR_VERSION (NameError)

### ISSUE THREAD

**Issue by kigotho** [ruby-gnome2/ruby-gnome2#1242]
using GTK3

```console
$ ./gtk-todo
Traceback (most recent call last):
	12: from ./gtk-todo:3:in `<main>'
	11: from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	10: from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	 9: from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	 8: from /home/godown/.rvm/gems/ruby-2.5.0/gems/gtk2-3.2.9/lib/gtk2.rb:11:in `<top (required)>'
	 7: from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 6: from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 5: from /home/godown/.rvm/gems/ruby-2.5.0/gems/gtk2-3.2.9/lib/gtk2/base.rb:13:in `<top (required)>'
	 4: from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 3: from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 2: from /home/godown/.rvm/gems/ruby-2.5.0/gems/atk-3.2.9/lib/atk.rb:26:in `<top (required)>'
	 1: from /home/godown/.rvm/gems/ruby-2.5.0/gems/atk-3.2.9/lib/atk.rb:46:in `<module:Atk>'
/home/godown/.rvm/gems/ruby-2.5.0/gems/atk-3.2.9/lib/atk.rb:47:in `<module:Version>': uninitialized constant Atk::Version::MAJOR_VERSION (NameError)

```

**Comment by kou** [comment]
I don't know about `gtk-todo` but you're using gtk2 gem not gtk3 gem.
