### ISSUE TITLE
Trouble with 'set_connect_func' method in Gtk3 3.2.9

### ISSUE THREAD

**Issue by kojix2** [ruby-gnome2/ruby-gnome2#1245]
Hello.

Trouble with `set_connect_func` method in Gtk3 3.2.9

I write a small [script](https://github.com/kojix2/yardview) based on the following the tutorial. 
[Creating a Linux Desktop application with Ruby
](https://iridakos.com/tutorials/2018/01/25/creating-a-gtk-todo-application-with-ruby.html)

It worked with Gtk3 3.2.8.
But, it does not work with Gtk3 3.2.9. 

The `set_connect_func` method below get an error.
https://github.com/kojix2/yardview/blob/b9d429ef53f86938349d6b4f3ec818ac6fd643f4/lib/yardview/application_window.rb#L14
```ruby
module Yardview
  class ApplicationWindow < Gtk::ApplicationWindow
    type_register

    def self.init
      set_template resource: '/com/github/kojix2/yardview/yardview.ui'
      bind_template_child 'box'
    end

    def initialize(application)
      # Error 3.2.9
      self.class.set_connect_func { |handler| method(handler) }

      super application: application
      set_title 'YardView'

```
Error
```
gobject-introspection-3.2.9/lib/gobject-introspection/loader.rb:587:in `invoke': wrong argument type Class (expected GLib::Object)
gobject-introspection-3.2.9/lib/gobject-introspection/loader.rb:587:in `block in define_method'
gtk3-3.2.9/lib/gtk3/widget.rb:55:in `set_connect_func'

```
I am aiming to connect signal handlers after instantiation.
Actually, I do not know ... just trial and error. Are there any ideas?

system:

- Ubuntu 18.04
- ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
- libgtk-3-0 3.22.30-1ubuntu1

**Comment by cedlemo** [comment]
I have the same issue (I spotted it yesterday but I am not sure when it started):

* Archlinux
* gtk3 3.24.1
* git version of the gems (3.3.0)

**Comment by kou** [comment]
Thanks for your report.
I've fixed it.

BTW, you should not call `set_connect_func` in `#initialize`. It should be called in `.init`. You can get the active `ApplicationWindow` by `application.active_window`:

```diff
diff --git a/exe/yardview b/exe/yardview
index aa87182..86b094c 100755
--- a/exe/yardview
+++ b/exe/yardview
@@ -6,7 +6,7 @@ require 'fileutils'
 resource_xml = File.expand_path('../resources/gresources.xml', __dir__)
 resource_bin = File.expand_path('../gresource.bin', __dir__)
 
-app = Gtk::Application.new 'com.github.kojix2.yardview', Gio::ApplicationFlags::FLAGS_NONE
+app = Yardview.application
 
 system('glib-compile-resources',
        '--target', resource_bin,
diff --git a/lib/yardview.rb b/lib/yardview.rb
index 6dc7cb5..e9c72fd 100644
--- a/lib/yardview.rb
+++ b/lib/yardview.rb
@@ -1,4 +1,5 @@
 require 'yardview/version'
+require 'yardview/application'
 require 'yardview/application_window'
 require 'webkit2-gtk'
 
diff --git a/lib/yardview/application.rb b/lib/yardview/application.rb
new file mode 100644
index 0000000..ef59bd1
--- /dev/null
+++ b/lib/yardview/application.rb
@@ -0,0 +1,10 @@
+require 'gtk3'
+
+module Yardview
+  class << self
+    def application
+      @@application ||= Gtk::Application.new('com.github.kojix2.yardview',
+                                             :flags_none)
+    end
+  end
+end
diff --git a/lib/yardview/application_window.rb b/lib/yardview/application_window.rb
index e4bd4da..0dea3c0 100644
--- a/lib/yardview/application_window.rb
+++ b/lib/yardview/application_window.rb
@@ -7,12 +7,14 @@ module Yardview
     def self.init
       set_template resource: '/com/github/kojix2/yardview/yardview.ui'
       bind_template_child 'box'
+      set_connect_func do |handler_name|
+        lambda do
+          Yardview.application.active_window.__send__(handler_name)
+        end
+      end
     end
 
     def initialize(application)
-      # calling class method.
-      self.class.set_connect_func { |handler| method(handler) }
-
       super application: application
       set_title 'YardView'
       set_icon GdkPixbuf::Pixbuf.new resource: '/com/github/kojix2/yardview/ruby.png'
```

And you should use `SIGINT` instead of `SIGTERM` for YARD server. `SIGINT` is mapped for shutdown:

```diff
diff --git a/lib/yardview/application_window.rb b/lib/yardview/application_window.rb
index 0dea3c0..f0d52f0 100644
--- a/lib/yardview/application_window.rb
+++ b/lib/yardview/application_window.rb
@@ -25,11 +25,10 @@ module Yardview
 
     def create_gui
       signal_connect('destroy') do
-        Gtk.main_quit
-        Process.kill(:TERM, @yard)
+        Process.kill(:INT, @yard)
         @yard = nil
       end
-      at_exit { Process.kill(:TERM, @yard) unless @yard.nil? }
+      at_exit { Process.kill(:INT, @yard) unless @yard.nil? }
       @view = WebKit2Gtk::WebView.new
       @view.load_uri('http://localhost:8808')
       box.add @view, expand: true, fill: true
```

**Comment by kou** [comment]
Ah, one more. You don't need to call `Gtk.main_quit` in `destroy` signal. Because it's cared by `GtkApplication`.

**Comment by kojix2** [comment]
Wow!! Thank you very much!!!
