### ISSUE TITLE
Slight warnings in gtk3/sample/gtk-demo/dialog.rb

### ISSUE THREAD

**Issue by shevegen** [ruby-gnome2/ruby-gnome2#198]
Hi.

Some warnings in gtk3 subfolder when running main.rb file:

```
gtk3/sample/gtk-demo/dialog.rb:24:in `initialize': 'Gtk::VBox.new' has been deprecated. Use 'Gtk::Box.new(:vertical, spacing)'.
gtk3/sample/gtk-demo/dialog.rb:31:in `new': 'Gtk::Button#initialize(label_or_stock_id, use_underline = nil)' style has been deprecated. Use 'Gtk::Button#initialize(:label => nil, :mnemonic => nil, :stock_id => nil)' style.
gtk3/sample/gtk-demo/dialog.rb:37:in `initialize': 'Gtk::HSeparator.new' has been deprecated. Use 'Gtk::Separator.new(:horizontal)'.
gtk3/sample/gtk-demo/dialog.rb:42:in `initialize': 'Gtk::VBox.new' has been deprecated. Use 'Gtk::Box.new(:vertical, spacing)'.
gtk3/sample/gtk-demo/dialog.rb:44:in `new': 'Gtk::Button#initialize(label_or_stock_id, use_underline = nil)' style has been deprecated. Use 'Gtk::Button#initialize(:label => nil, :mnemonic => nil, :stock_id => nil)' style.
```

Can we replace Gtk::HSeparator.new with Gtk::Separator.new(:horizontal)?

I am not sure how to use git and send a patch ... it should be a trivial fix though.

**Comment by kou** [comment]
It must be fixed at master.
