### ISSUE TITLE
Unable to find pkg-config

### ISSUE THREAD

**Issue by mspanc** [ruby-gnome2/ruby-gnome2#293]
Hi, I am unable to use the gem "gstreamer", it fails in finding pkg-config (which is successfully installed).

Bundler suggest that problem lies in gobject-introspection.

Ubuntu 14.04, ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux-gnu]

````
 $ bundle exec gem install gobject-introspection -v '2.2.4'
Successfully installed pkg-config-1.1.6
Building native extensions.  This could take a while...
ERROR:  Error installing gobject-introspection:
	ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.1 extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/ruby2.1
/home/rails/radiokit_staging/shared/bundle/ruby/2.1.0/gems/glib2-2.2.4/lib/mkmf-gnome2.rb:14:in `require': cannot load such file -- pkg-config (LoadError)
	from /home/rails/radiokit_staging/shared/bundle/ruby/2.1.0/gems/glib2-2.2.4/lib/mkmf-gnome2.rb:14:in `<top (required)>'
	from extconf.rb:15:in `require'
	from extconf.rb:15:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /home/rails/radiokit_staging/shared/bundle/ruby/2.1.0/gems/glib2-2.2.4 for inspection.
Results logged to /home/rails/radiokit_staging/shared/bundle/ruby/2.1.0/extensions/x86_64-linux/2.1.0/glib2-2.2.4/gem_make.out
````

**Comment by mspanc** [comment]
Ok it seems that libgirepository1.0-dev is missing.

**Comment by Nakilon** [comment]
@mspanc I get this on trying to gem install glib2 -v '3.0.8' on Mac OS rbenv Ruby 2.1
On default Mac OS Ruby 2.0 it was smooth.
Can you tell when is libgirepository1.0-dev? How do I install it?

**Comment by mspanc** [comment]
It is package from Ubuntu, not Mac OS. Sorry I can help you as I don't use this approach any more.

If you need to write glib/gtk apps with nicer approach than pure C I can recommend Vala or JS instead of Ruby. Ruby is awesome but not necessarily for that purpose

**Comment by Nakilon** [comment]
I'm just installing gem ruby-vips that depends on gem glib.
[This hint to use `--debug --backtrace --verbose`](http://stackoverflow.com/a/19078478/322020) now shows me this:
```
GET https://api.rubygems.org/api/v1/dependencies?gems=pkg-config
Exception `OpenSSL::SSL::SSLErrorWaitReadable' at /Users/nakilon/.rbenv/versions/2.1.10/lib/ruby/2.1.0/openssl/buffering.rb:182 - read would block
200 OK
Exception `NoMethodError' at /Users/nakilon/.rbenv/versions/2.1.10/lib/ruby/2.1.0/rubygems/package.rb:443 - undefined method `readpartial' for #<Gem::Package::TarReader::Entry:0x007f9436d1c5a0>
```
Seems like pkg-config fails to install but that does not stop install of glib2 that is weird.
