### ISSUE TITLE
Gtk::ToolButton usage

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#320]
In one of the script that I am  updating, I have to create a ToolButton object.

Following the deprecatable message:

```'Gtk::ToolButton#initialize(icon_widget_or_stock_id = nil, label = nil)' style has been deprecated. Use 'Gtk::ToolButton#initialize(:icon_widget => nil, :label => nil, :stock_id => nil)' style.````

I use this :

```ruby
require "gtk3"

class MyWin < Gtk::Window
  def initialize
    super
    set_default_size 600,400
    set_title "Toolbar_test"
    signal_connect "destroy" do
      Gtk.main_quit
    end
    toolbar = Gtk::Toolbar.new
    button_open = Gtk::ToolButton.new(:icon_widget => nil, :label => "Open stock id",:stock_id => Gtk::Stock::OPEN)# do
#      puts "nothing"
#    end
    toolbar.insert(button_open,0)
    add(toolbar)
  end
end

win = MyWin.new

win.show
Gtk.main  
```

And get this error:

```
/home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:284:in `invoke': invalid argument Hash (expect #<Class:0x00000002501d90>) (ArgumentError)
	from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:284:in `block (2 levels) in load_constructor_infos'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:300:in `block in load_constructor_infos'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.5/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'
	from toolbar.rb:12:in `new'
	from toolbar.rb:12:in `initialize'
	from toolbar.rb:20:in `new'
	from toolbar.rb:20:in `<main>'

```

**Comment by kou** [comment]
Thanks for your report.
I've fixed it at master.
