### ISSUE TITLE
Gtk::Assistant TODO

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#321]
I am checking gtk3/sample/misc/assistant.rb which stop running at (line 203) : 

```ruby
    assistant.set_forward_page_func do |current_page|
      retval = -1
      if current_page == 0
        if @selected_branch == "A"
          retval = 1
        else
          retval = 2
        end
      elsif current_page == 1 || current_page == 2
        retval = 3
      end
      retval
    end
```

With this message:

```
/home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:471:in `invoke': TODO: <AssistantPageFunc>(page_func) callback is not /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:471:in `invoke': TODO: <AssistantPageFunc>(page_func) callback is not supported yet.
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:471:in `block in define_method'
	 from assistant.rb:203:in `create_nonlinear_assistant'
	 from assistant.rb:40:in `run_assistant'
	 from assistant.rb:34:in `run_nonlinear_assistant'
	 from assistant.rb:259:in `block in <main>'
	 from assistant.rb:276:in `call'
	 from assistant.rb:276:in `block (2 levels) in <main>'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:112:in `call'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:112:in `invoke'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:112:in `block in define_singleton_method'
	 from assistant.rb:281:in `<main>'

```

**Comment by cedlemo** [comment]
solved with 8de749c6e68daedcdacffba1a3e4490d72713e12 thanks kou. Now I have a new issue #324
