### ISSUE TITLE
TODO: Ruby -> GIArgument(gslist) error message

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#324]
When creating an RadioButton I have this message (in irb for example):

```
irb(main):002:0> Gtk::RadioButton.new("test")
NotImplementedError: TODO: Ruby -> GIArgument(gslist)
	from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:284:in `invoke'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:284:in `block (2 levels) in load_constructor_infos'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:300:in `block in load_constructor_infos'
	from (irb):2:in `new'
	from (irb):2
	from /usr/bin/irb:11:in `<main>'

```

**Comment by kou** [comment]
Thanks for your report.
I've fixed it.
