### ISSUE TITLE
Gtk::Dialog.new issue

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#327]
In this script:

```ruby
require "gtk3"

window = Gtk::Window.new("Gtk::Dialog sample2")
button = Gtk::Button.new(:label => "Create Dialog")
button.signal_connect("clicked") do
  dialog = Gtk::Dialog.new(  dialog = Gtk::Dialog.new(:title =>"Gtk::Dialog Sample 2",
                           :parent => window,
                           :flags => Gtk::DialogFlags::MODAL,
                           :buttons => [[Gtk::Stock::OK, Gtk::ResponseType::OK],
                           [Gtk::Stock::CANCEL, Gtk::ResponseType::CANCEL]])
  dialog.child.add(Gtk::Label.new("Gtk::Dialog Sample 2"))
  dialog.set_default_size(300, 300)
  dialog.child.show_all
  result = dialog.run
  case result
  when Gtk::ResponseType::OK
    p "OK"
  when Gtk::ResponseType::CANCEL
    p "Cancel"
  end
  dialog.destroy
end

window.add(button)
window.show_all
window.signal_connect("destroy") {Gtk.main_quit}

Gtk.main
```
As you can see, for the creation of the Gtk::Dialog, I have followed some warnings that said:

    Gtk::Dialog#initialize(title, parent, flags, *buttons)' style has been deprecated. Use 'Gtk::Dialog#initialize(:title => nil, :parent => nil, :flags => 0, :buttons => nil)' style.

But I have still this error:

```
/home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:361:in `find_suitable_callable_info': wrong number of arguments (1 for 0)
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:296:in `block in load_constructor_infos'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:299:in `call'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:299:in `block in load_constructor_infos'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.5/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'
	 from dialog2.rb:16:in `new'
	 from dialog2.rb:16:in `block in <main>'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:112:in `call'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:112:in `invoke'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:112:in `block in define_singleton_method'
	 from dialog2.rb:38:in `<main>'

```

**Comment by kou** [comment]
I've fixed it.
