### ISSUE TITLE
TODO: free GIArgument(filename) everything 

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#334]
Simple example:
```ruby
require "gtk3"

dialog = Gtk::FileChooserDialog.new(:title => "Choose a file",
                                    :action => Gtk::FileChooserAction::OPEN,
                                    :buttons => [[Gtk::Stock::CANCEL, Gtk::ResponseType::CANCEL],
                                    [Gtk::Stock::OPEN, Gtk::ResponseType::ACCEPT]]
                                    )

if dialog.run == Gtk::ResponseType::ACCEPT
  puts dialog.filename
end
```
Error message:
```
home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb: line 471
   Gtk-MESSAGE **:GtkDialog mapped without a transient parent. This is discouraged.
/home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:471:in `invoke': TODO: free GIArgument(filename) everything (NotImplementedError)
	from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:471:in `block in define_method'
	from filechooser.rb:10:in `<main>'
```

**Comment by kou** [comment]
Thanks for your report.
I've fixed it.
