### ISSUE TITLE
ComboBox error at initialization

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#340]
With this code:

```ruby
#!/usr/bin/env ruby
require "gtk3"

#
# Icon and text
#
window = Gtk::Window.new
model = Gtk::ListStore.new(Gdk::Pixbuf, String)
[[Gtk::Stock::QUIT, "quit"],
 [Gtk::Stock::CANCEL, "cancel"],
 [Gtk::Stock::OK, "ok"]].each do |stock, name|
  iter = model.append
  iter[0] = window.render_icon_pixbuf(stock, Gtk::IconSize::MENU)
  iter[1] = name
end

combo2 = Gtk::ComboBox.new(:model => model)

```

I have this error:

```
/home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:284:in `invoke': invalid argument Hash (expect #<Class:0x000000030e2330>) (ArgumentError)
	from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:284:in `block (2 levels) in load_constructor_infos'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:300:in `block in load_constructor_infos'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.5/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'
	from combobox.rb:17:in `new'
	from combobox.rb:17:in `<main>'
```

**Comment by cedlemo** [comment]
I think it is the same kind of issue that #320 I would like try to solve it if you have no objections.

**Comment by kou** [comment]
Sorry for my late response. :<
Good work. :-)
