### ISSUE TITLE
Gtk::TextBuffer serialize/deserialize issues

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#353]
Here is an example (note:  this script create a binary file ~/serialize.dat and doesn't delete it):

```ruby
#!/usr/bin/env ruby
require "gtk3"


class MyWin < Gtk::Window
  def initialize
    super
    filename = "#{ENV["HOME"]}/serialize.dat"
    set_title "serialize test"
    set_default_size 400, 600
    vbox = Gtk::Box.new(:vertical, 0)
    textview = Gtk::TextView.new
    textview.set_size_request 400,500
    buffer = textview.buffer
    buffer.text="this a test"
    serialize_format = buffer.register_serialize_tagset(nil)
    deserialize_format = buffer.register_deserialize_tagset(nil)
    format = buffer.serialize_formats[0]
    puts serialize_format
    button = Gtk::Button.new(:label => "serialize") 
    button.signal_connect "clicked" do
      File.open(filename, "wb") {|io|
        io.write(buffer.serialize(buffer, serialize_format, buffer.start_iter, buffer.end_iter))
      }

    end
    vbox.pack_start(textview, :fill => true, :expand => true)
    vbox.pack_start(button, :fill => false, :expand => false)
    add(vbox)
    show_all
    signal_connect("destroy") {Gtk.main_quit}
  end
end
win = MyWin.new

Gtk.main
```

The script stops with this message:

```
#<Gdk::Atom:0x000000026f0890>
/home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:475:in `invoke': TODO: GIArgument(array)[c][guint8] -> Ruby
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:475:in `block in define_method'
	 from textbuffer_serialize.rb:23:in `block (2 levels) in initialize'
	 from textbuffer_serialize.rb:22:in `open'
	 from textbuffer_serialize.rb:22:in `block in initialize'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:112:in `call'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:112:in `invoke'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:112:in `block in define_singleton_method'
	 from textbuffer_serialize.rb:36:in `<main>'
```

I would like to point out that if I use the serialization format that I get with (like suggested in a lot of documentation):

    format = buffer.serialize_formats[0]

instead of 

    serialize_format = buffer.register_serialize_tagset(nil)

I have this following error :

```
    home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb: line 475
   Gtk-CRITICAL **:gtk_text_buffer_serialize: assertion 'format != GDK_NONE' failed
```

**Comment by kou** [comment]
Thanks for your report!
I've implemented.
