### ISSUE TITLE
textbuffer_serialize.rb update

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#357]
I am currently stuck with the update of textbuffer_serialize.rb. Here is a simple script that show my problem : 

```ruby
#!/usr/bin/env ruby
require "gtk3"


class MyWin < Gtk::Window
  def initialize
    super
    filename = "#{ENV["HOME"]}/serialize.dat"
    set_title "serialize test"
    set_default_size 400, 600
    vbox = Gtk::Box.new(:vertical, 0)
    textview = Gtk::TextView.new
    textview.set_size_request 400,300
    buffer = textview.buffer
    buffer.text="this a test"
    serialize_format = buffer.register_serialize_tagset(nil)
    deserialize_format = buffer.register_deserialize_tagset(nil)
    button = Gtk::Button.new(:label => "serialize") 
    button.signal_connect "clicked" do
      File.open(filename, "wb") { |io|
        io.write(buffer.serialize(buffer, serialize_format, buffer.start_iter, buffer.end_iter))
      }
    end
    vbox.pack_start(textview, :fill => true, :expand => true)
    vbox.pack_start(button, :fill => false, :expand => false)
    textview1 = Gtk::TextView.new
    textview1.set_size_request 400,300
    buffer = textview1.buffer
    buffer.text =""
    deserialize_format = buffer.register_deserialize_tagset(nil)
    button1 = Gtk::Button.new(:label => "deserialize")
    button1.signal_connect "clicked" do
       File.open(filename, "rb") {|io|
        buffer.delete(buffer.start_iter, buffer.end_iter)
        buffer.deserialize(buffer, deserialize_format, buffer.start_iter, io.read)
       }
    end
    vbox.pack_start(textview1, :fill => true, :expand => true)
    vbox.pack_start(button1, :fill => false, :expand => false)
    add(vbox)
    show_all
    signal_connect("destroy") {Gtk.main_quit}
  end
end
win = MyWin.new

Gtk.main

```

The error message when I try to deserialize the serialized text :
```
/home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb: line 475
   GLib-WARNING **:(gerror.c:381):g_error_new_valist: runtime check failed: (domain != 0)
/home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:475:in `invoke': Unknown error when trying to deserialize application/x-gtk-text-buffer-rich-text
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:475:in `block in define_method'
	 from textbuffer_serialize.rb:35:in `block (2 levels) in initialize'
	 from textbuffer_serialize.rb:33:in `open'
	 from textbuffer_serialize.rb:33:in `block in initialize'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:112:in `call'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:112:in `invoke'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:112:in `block in define_singleton_method'
	 from textbuffer_serialize.rb:47:in `<main>'
```

**Comment by kou** [comment]
Try the following:

```ruby
#!/usr/bin/env ruby
require "gtk3"


class MyWin < Gtk::Window
  def initialize
    super
    filename = "#{ENV["HOME"]}/serialize.dat"
    set_title "serialize test"
    set_default_size 400, 600
    vbox = Gtk::Box.new(:vertical, 0)
    textview = Gtk::TextView.new
    textview.set_size_request 400,300
    serialize_buffer = textview.buffer
    serialize_buffer.text="this a test"
    serialize_format = serialize_buffer.serialize_formats[0]
    button = Gtk::Button.new(:label => "serialize") 
    button.signal_connect "clicked" do
      File.open(filename, "wb") { |io|
        data = serialize_buffer.serialize(serialize_buffer,
                                            serialize_format,
                                            serialize_buffer.start_iter,
                                            serialize_buffer.end_iter)
        io.write(data.pack("C*"))
      }
    end
    vbox.pack_start(textview, :fill => true, :expand => true)
    vbox.pack_start(button, :fill => false, :expand => false)
    textview1 = Gtk::TextView.new
    textview1.set_size_request 400,300
    descerialize_buffer = textview1.buffer
    descerialize_buffer.text =""
    deserialize_format = descerialize_buffer.register_deserialize_tagset(nil)
    button1 = Gtk::Button.new(:label => "deserialize")
    button1.signal_connect "clicked" do
      File.open(filename, "rb") {|io|
        descerialize_buffer.delete(descerialize_buffer.start_iter,
                                   descerialize_buffer.end_iter)
        data = io.read
        descerialize_buffer.deserialize(descerialize_buffer,
                                        deserialize_format,
                                        descerialize_buffer.start_iter,
                                        data)
       }
    end
    vbox.pack_start(textview1, :fill => true, :expand => true)
    vbox.pack_start(button1, :fill => false, :expand => false)
    add(vbox)
    show_all
    signal_connect("destroy") {Gtk.main_quit}
  end
end
win = MyWin.new

Gtk.main
```

Umm. `#serialize` should return ASCII-8BIT String instead of Integer of Array...?

**Comment by cedlemo** [comment]
-_-' 

Umm. #serialize should return ASCII-8BIT String instead of Integer of Array...?

In my head for a moment .. Yes 
but not in the real world it seems.

Sorry

**Comment by kou** [comment]
Thanks for your advice.
I changed `Gtk::TextBuffer#serialize` to return ASCII-8BIT String instead of Integer of Array.
