### ISSUE TITLE
gdk::Screen and gdk::Display

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#376]
I am working on the sample/misc/gdkscreen.rb

```ruby
require 'gtk3'
Gtk.init #used to init a connection in order to have a default display and screen
puts Gdk::Display.default.class
screen = Gdk::Screen.default
puts screen.class
settings_map = [
  "gtk-double-click-time",
  "gtk-dnd-drag-threshold",
  "gtk-can-change-accels",
  "gtk-color-palette",
  "gtk-font-name",
  "gtk-icon-sizes",
  "gtk-key-theme-name",
  "gtk-toolbar-style",
  "gtk-toolbar-icon-size",
  "gtk-im-preedit-style",
  "gtk-im-status-style",
  "gtk-cursor-blink",
  "gtk-cursor-blink-time",
  "gtk-theme-name" 
]

settings_map.each do |v|
  puts "#{v}: #{screen.get_setting(v )}"
end
```
First, the class name that I try to print are displayed like this:

```
#<Class:0x000000038f5518>
#<Class:0x000000038f6350>
```
Then I have this error:

```
/home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:337:in `validate_arguments': Gdk::Screen#get_setting: wrong number of arguments (1 for 2) (ArgumentError)
	from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:480:in `block in define_method'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:485:in `call'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:485:in `block in define_method'
	from gdkscreen.rb:34:in `block in <main>'
	from gdkscreen.rb:33:in `each'
	from gdkscreen.rb:33:in `<main>'

```

It looks like the methods waits for two arguments like in C. Except that in C the second argument is a pointer to the data we want to get.

```C
gboolean
gdk_screen_get_setting (GdkScreen *screen,
                        const gchar *name,
                        GValue *value);
```

**Comment by kou** [comment]
Thanks for your report.
I've pushed commits that support `Gdk::Screen#get_setting`.
