### ISSUE TITLE
Report test 2.2.5 on windows

### ISSUE THREAD

**Issue by glurp** [ruby-gnome2/ruby-gnome2#384]
Event
-------
same problem with datas on EventButton in Drawing widget as 2.2.3 and 2.2.4:
missing Y position is allways 0, X position contain Y position....

BUT: event data X/Y in drawingArea work in gtk-demo :) 

Clutter
-------
ruby -r clutter -e 'Clutter.init ; p "ok" '
```text
"ok"
```

ruby -r clutter-gtk -e 'ClutterGtk.init'
```text
d:/usr/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/gobject-introspection-2.2.5-x86-mingw32/lib/gobject-introspection/loader.rb:35:in `require': Typelib file for namespace 'GtkClutter' (any version) not found (GLib::Error)
        from d:/usr/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/gobject-introspection-2.2.5-x86-mingw32/lib/gobject-introspection/loader.rb:35:in `load'
        from d:/usr/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/clutter-gtk-2.2.5-x86-mingw32/lib/clutter-gtk.rb:47:in `init'
        from -e:1:in `<main>'

```

for /D %d in ( *2.2.5* ) do @gfind %d -name *.typelib
```text
atk-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/Atk-1.0.typelib
clutter-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/Cally-1.0.typelib
clutter-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/Clutter-1.0.typelib
clutter-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/Cogl-1.0.typelib
clutter-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/Cogl-2.0.typelib
clutter-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/CoglPango-1.0.typelib
clutter-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/CoglPango-2.0.typelib
clutter-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/Json-1.0.typelib
clutter-gstreamer-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/ClutterGst-3.0.typelib
clutter-gtk-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/GtkClutter-1.0.typelib
gdk3-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/Gdk-3.0.typelib
gdk3-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/GdkWin32-3.0.typelib
gdk3-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/Gtk-3.0.typelib
gdk_pixbuf2-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/GdkPixbuf-2.0.typelib
gobject-introspection-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/cairo-1.0.typelib
gobject-introspection-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/DBus-1.0.typelib
gobject-introspection-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/DBusGLib-1.0.typelib
gobject-introspection-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/fontconfig-2.0.typelib
gobject-introspection-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/freetype2-2.0.typelib
gobject-introspection-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/Gio-2.0.typelib
gobject-introspection-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/GIRepository-2.0.typelib
gobject-introspection-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/GL-1.0.typelib
gobject-introspection-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/GLib-2.0.typelib
gobject-introspection-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/GModule-2.0.typelib
gobject-introspection-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/GObject-2.0.typelib
gobject-introspection-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/libxml2-2.0.typelib
gobject-introspection-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/win32-1.0.typelib
gobject-introspection-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/xfixes-4.0.typelib
gobject-introspection-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/xft-2.0.typelib
gobject-introspection-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/xlib-2.0.typelib
gobject-introspection-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/xrandr-1.3.typelib
gstreamer-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/Gst-1.0.typelib
gstreamer-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/GstAllocators-1.0.typelib
gstreamer-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/GstApp-1.0.typelib
gstreamer-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/GstAudio-1.0.typelib
gstreamer-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/GstBase-1.0.typelib
gstreamer-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/GstCheck-1.0.typelib
gstreamer-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/GstController-1.0.typelib
gstreamer-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/GstFft-1.0.typelib
gstreamer-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/GstInsertBin-1.0.typelib
gstreamer-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/GstMpegts-1.0.typelib
gstreamer-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/GstNet-1.0.typelib
gstreamer-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/GstPbutils-1.0.typelib
gstreamer-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/GstRiff-1.0.typelib
gstreamer-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/GstRtp-1.0.typelib
gstreamer-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/GstRtsp-1.0.typelib
gstreamer-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/GstSdp-1.0.typelib
gstreamer-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/GstTag-1.0.typelib
gstreamer-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/GstVideo-1.0.typelib
gstreamer-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/Soup-2.4.typelib
gtksourceview3-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/GtkSource-3.0.typelib
pango-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/Pango-1.0.typelib
pango-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/PangoCairo-1.0.typelib
pango-2.2.5-x86-mingw32/vendor/local/lib/girepository-1.0/PangoFT2-1.0.typelib
```

gtk_demo
------------
Work very well, except for cairo menu : Arc,Clip,Curve...
*  the window is white for almost all item, 
*  except for this items : Long Line, text *

Conclusions
--------------
So I close issues on 2.2.4 / Windows
Next week, i will have some times, with a linux and a windows PC, so i will try
to work on the C code...

**Comment by kou** [comment]
Thanks for your try.

About clutter-gtk: It'll be available at the next release. It'll include gtk3 gem based on GObject Introspection. The current error is occurred because `GI_TYPELIB_PATH` doesn't include path for `Gtk-3.0.typelib`. gtk3 gem based on GObject Introspection adds the include path.

**Comment by kou** [comment]
ref: #289

**Comment by kou** [comment]
About event: Can you try it on 64bit Windows?

**Comment by glurp** [comment]
I have explanation with event  ok in demo-gtk : the demo is in GTK2 !!!

64Bit Window
==
* i am in 64 bit windows 7, ruby 32 bits. ==> bug
* installing ruby64, gtk4... => OK ! event is perfect !

**Comment by kou** [comment]
It's moved to #540.
