### ISSUE TITLE
Crash when using symbol flags in MessageDialog.new

### ISSUE THREAD

**Issue by eumario** [ruby-gnome2/ruby-gnome2#385]
When attempting to run this test, it fails to create the dialog when using Symbol flags, instead of Gtk::DialogFlags or'ed together.  The demo below will crash when you click the button.

Code:
```ruby
require 'gtk3'

win = Gtk::Window.new
win.title = "Symbol Dialog Bug"
win.signal_connect("destroy") { Gtk.main_quit }

btn = Gtk::Button.new(:label => "Run Message Dialog")
btn.signal_connect("clicked") do
	dialog = Gtk::MessageDialog.new(
		:parent => win,
		:flags => [:modal,:destroy_with_parent],
		:type => :question,
		:buttons_type => nil,
		:message => "This is a test message to see if we get an exception.")

	dialog.add_button("_Cancel",Gtk::ResponseType::CANCEL)
	dialog.add_button("_No",Gtk::ResponseType::NO)
	dialog.add_button("_Yes",Gtk::ResponseType::YES)

	dialog.title = "Test Recursion bug"
	dlgRet = dialog.run
	if dlgRet == Gtk::ResponseType::YES
		puts "1"
	elsif dlgRet == Gtk::ResponseType::NO
		puts "0"
	else dlgRet == Gtk::ResponseType::CANCEL
		puts "-1"
	end
	dialog.destroy
end

win.add(btn)
win.show_all

Gtk.main
```

Exception:
```
/home/eumario/.gem/ruby/2.2.0/gems/gtk3-2.2.6/lib/gtk3/loader.rb: line 37
   (null)-WARNING **:Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
/home/eumario/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb: line 293
   GLib-GObject-WARNING **:The property GtkButton:use-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.
/home/eumario/.gem/ruby/2.2.0/gems/gtk3-2.2.6/lib/gtk3/message-dialog.rb:42:in `initialize': no implicit conversion of Array into String
	 from /home/eumario/.gem/ruby/2.2.0/gems/gtk3-2.2.6/lib/gtk3/message-dialog.rb:42:in `new'
	 from /home/eumario/.gem/ruby/2.2.0/gems/gtk3-2.2.6/lib/gtk3/message-dialog.rb:42:in `initialize'
	 from /home/eumario/.gem/ruby/2.2.0/gems/glib2-2.2.6/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'
	 from test_bug.rb:9:in `new'
	 from test_bug.rb:9:in `block in <main>'
	 from /home/eumario/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:112:in `call'
	 from /home/eumario/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:112:in `invoke'
	 from /home/eumario/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:112:in `block in define_singleton_method'
	 from test_bug.rb:35:in `<main>'
```

**Comment by eumario** [comment]
I have confirmed, after cleaning all libraries, rebuilding the gems, that glib2 now properly parses the symbols.  I'm closing this bug, as it is corrected.  My apologizes @kou

**Comment by kou** [comment]
No problem. :-)
Thanks for re-confirming it.

**Comment by eumario** [comment]
Not a problem.
