### ISSUE TITLE
TODO: GIArgument(GList)[interface(struct)](void) -> Ruby

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#407]
I am updating sample/misc/dnd.rb and I stumbled on this error:

```
 /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:549:in `invoke': TODO: GIArgument(GList)[interface(struct)](void) -> Ruby
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:549:in `block in define_method'
	 from dnd.rb:54:in `block in initialize'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:114:in `call'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:114:in `invoke'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:114:in `block in define_singleton_method'
	 from dnd.rb:65:in `<main>'
```

The lines 53-55:

```ruby
    signal_connect("drag-drop") do |widget, context, x, y, time|
      widget.drag_get_data(context, context.targets[0], time)
    end
```

**Comment by kou** [comment]
I've fixed it at master.
