### ISSUE TITLE
"require 'gtk3'" failure

### ISSUE THREAD

**Issue by jspillers** [ruby-gnome2/ruby-gnome2#429]
After several hours I managed to get the gtk3 gem built, but now running a very basic test causes a failure on the require of the gem. When I attempted to do a "hello_world.rb" type test I get:

```
/Users/jarrod/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/Users/jarrod/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-13/2.2.0-static/glib2-2.2.5/glib2.bundle, 9): Library not loaded: @@HOMEBREW_PREFIX@@/opt/gettext/lib/libintl.8.dylib (LoadError)
  Referenced from: /Users/jarrod/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-13/2.2.0-static/glib2-2.2.5/glib2.bundle
  Reason: image not found - /Users/jarrod/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-13/2.2.0-static/glib2-2.2.5/glib2.bundle
	from /Users/jarrod/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/jarrod/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/glib2-2.2.5/lib/glib2.rb:105:in `rescue in <top (required)>'
	from /Users/jarrod/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/glib2-2.2.5/lib/glib2.rb:101:in `<top (required)>'
	from /Users/jarrod/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/jarrod/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/jarrod/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/atk-2.2.5/lib/atk.rb:1:in `<top (required)>'
	from /Users/jarrod/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/jarrod/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/jarrod/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/gtk3-2.2.5/lib/gtk3/base.rb:7:in `<top (required)>'
	from /Users/jarrod/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/jarrod/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/jarrod/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/gtk3-2.2.5/lib/gtk3.rb:7:in `<top (required)>'
	from /Users/jarrod/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /Users/jarrod/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /Users/jarrod/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from lib/test.rb:1:in `<main>'
```

**Comment by kou** [comment]
Is `@@HOMEBREW_PREFIX@@` garbage?

**Comment by kou** [comment]
No response.
