### ISSUE TITLE
Undefined method Gtk::BindingSet#entry_remove

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#432]
I have almost finished the update of bindings.rb but I have this strange error. In order to remove a binding, I have searched the existing method which was Gtk::BindingSet#entry_clear but when I use it I have this error:

```
bindings.rb:94:in `block in <main>': 'Gtk::BindingSet#entry_clear' has been deprecated. Use 'Gtk::BindingSet#entry_remove'.
/home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.6/lib/glib2/deprecatable.rb:152:in `block in __define_deprecated_method__': undefined method `entry_remove' for #<Gtk::BindingSet:0x00000003388378>
	 from bindings.rb:94:in `block in <main>'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:114:in `call'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:114:in `invoke'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:114:in `block in define_singleton_method'
	 from bindings.rb:101:in `<main>'
bindings.rb: line 0
   GLib-GObject-WARNING **:The property GtkWidget:style is deprecated and shouldn't be used anymore. It will be removed in a future version.
```

Here is the full version of the script:

```ruby
#!/usr/bin/env ruby
=begin
  bindings.rb - Ruby/GTK sample script.

  Copyright (c) 2002-2015 Ruby-GNOME2 Project Team 
  This program is licenced under the same licence as Ruby-GNOME2.
=end

=begin
Usage:
  bindings.rb <filename>

  Following key bindings are effective in the TextView area.
  
    <Control> + l      : scroll down by one page
    <Control> + m      : scroll up by one page
    <Control> + j      : move cursor donw by one line
    <Control> + k      : move cursor up by one line

  clicking buttons cause following effect

    "space"      : same as pressing <space> in text view area.
    "back_space" : same as pressing <backspace> in text view area.
    "cancel j/k" : disable 'j' and 'k' binding
=end

require "gtk3"

class Pager < Gtk::TextView
  def initialize(path)
    @path = path
    super()
    @buffer = self.buffer
    load
    set_editable(false)
    set_size_request(400, 400)
  end

  def load
    open(@path).read.each_line do |line|
      @buffer.insert_at_cursor(line)
    end
    @buffer.place_cursor(@buffer.start_iter)
  end
end
directory_path = File.expand_path(File.dirname(__FILE__))
file_path = ARGV[0] || __FILE__


window = Gtk::Window.new
window.name = "pager_window"

css_provider = Gtk::CssProvider.new
#css_provider.load(:path => "#{directory_path}/bindings.css")
css_provider.load(:data => DATA.read)


hbox = Gtk::Box.new(:horizontal)

hbox.add(button1 = Gtk::Button.new(:label => "Ctrl + l"))
hbox.add(button2 = Gtk::Button.new(:label => "Ctrl + m"))
hbox.add(button3 = Gtk::Button.new(:label => "Cancel Ctrl + j/k"))

vbox = Gtk::Box.new(:vertical)
sw = Gtk::ScrolledWindow.new
sw.set_size_request(400, 400)

pager = Pager.new(file_path)
pager.style_context.add_provider(css_provider, Gtk::StyleProvider::PRIORITY_USER)
sw.add(pager)

vbox.add(hbox)
vbox.add(sw)

window.add(vbox)
window.show_all


window.signal_connect("destroy") {Gtk.main_quit}

binding_set = Gtk::BindingSet.find("MoveCursor")

button1.signal_connect "clicked" do
  binding_set.activate(Gdk::Keyval::KEY_l, Gdk::ModifierType::CONTROL_MASK, pager)
  pager.grab_focus
end

button2.signal_connect "clicked" do
  binding_set.activate(Gdk::Keyval::KEY_m, Gdk::ModifierType::CONTROL_MASK, pager)
  pager.grab_focus
end

button3.signal_connect "clicked" do
  binding_set.entry_clear(Gdk::Keyval::KEY_j, Gdk::ModifierType::CONTROL_MASK, pager)
  binding_set.entry_clear(Gdk::Keyval::KEY_l, Gdk::ModifierType::CONTROL_MASK, pager)
  pager.grab_focus
end
  
pager.grab_focus

Gtk.main

__END__
@binding-set MoveCursor {
  bind "<Control>j" { "move-cursor" (display-lines, 1, 0) };
  bind "<Control>k" { "move-cursor" (display-lines, -1, 0) };
  bind "<Control>l" { "move-cursor" (buffer-ends, 1, 0) };
  bind "<Control>m" { "move-cursor" (buffer-ends, -1, 0) };
}
GtkTextView {
  -GtkWidget-cursor-color: green;
  -GtkWidget-aspect-ratio: 1.0;
  font: 20 Sans;
  color: #aaa;
  background-color: #333 ;
  gtk-key-bindings: MoveCursor;
}
```

**Comment by kou** [comment]
I've fixed it.

> ```ruby
> binding_set.entry_clear(Gdk::Keyval::KEY_j, Gdk::ModifierType::CONTROL_MASK, pager)
> binding_set.entry_clear(Gdk::Keyval::KEY_l, Gdk::ModifierType::CONTROL_MASK, pager)
> ```

should be changed to the followings:

```ruby
binding_set.remove(Gdk::Keyval::KEY_j, Gdk::ModifierType::CONTROL_MASK)
binding_set.remove(Gdk::Keyval::KEY_k, Gdk::ModifierType::CONTROL_MASK)
```

  * `#entry_clear` -> `#remove`
  * `pager` argument is removed
  * `KEY_l` -> `KEY_k` (just a typo)
