### ISSUE TITLE
TODO: GIArgument(array)[c][interface(object)](GParam) -> Ruby (NotImplementedError)

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#441]
I am updating the script gtk3/sample/misc/properties.rb
With this script : 

```ruby
require 'gtk3'

class MyButton < Gtk::Button
  type_register

  def initialize(label = nil)
    # XXX: 
    # When type_register() is used.
    # super is equivalent to GLib::Object#initialize.
    super("label" => label)
    @fuga = 0
    @hoge = 0
  end

  # define new property "fuga"
  install_property(GLib::Param::Int.new("fuga", # name
                                        "Fuga", # nick
                                        "fuga fuga", # blurb
                                        0,     # min
                                        10000, # max
                                        0,     # default
                                        GLib::Param::READABLE |
                                        GLib::Param::WRITABLE))

  # define new property "hoge"
  install_child_property(1,GLib::Param::Int.new("hoge", # name
                                      "Hoge", # nick
                                      "hoge hoge", # blurb
                                      0,     # min
                                      10000, # max
                                      0,     # default
                                      GLib::Param::READABLE |
                                      GLib::Param::WRITABLE)
                        )

  # implementation of the property "fuga"
  def fuga
    puts "MyButton#fuga is called"
    @fuga
  end
  def fuga=(arg)
    puts "MyButton#fuga= is called"
    @fuga = arg
    notify("fuga")
  end

  # implementation of the property "hoge"
  def get_hoge(child)
    puts "MyButton#get_hoge is called"
    @hoge
  end
  def set_hoge(child, arg)
    puts "MyButton#set_hoge is called"
    @hoge = arg
  end
end

b = MyButton.new("Hello")
p b
p b.label
p b.gtype

p MyButton.properties
p b.get_property("fuga")
b.set_property("fuga", 1)
p b.get_property("fuga")

p MyButton.list_child_properties
p child = b.child
p b.child_get_property(child, "hoge")
b.child_set_property(child, "hoge", 2)
p b.child_get_property(child, "hoge")

p MyButton.ancestors
```

I have this error: 

    home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:549:in `invoke': TODO: GIArgument(array)[c][interface(object)](GParam) -> Ruby (NotImplementedError)
	from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:549:in `block in define_method'
	from properties.rb:81:in `<main>'
    properties.rb: line 0

**Comment by kou** [comment]
I've pushed a commit to supported it.

**Comment by cedlemo** [comment]
thx
