### ISSUE TITLE
Gtk::RecentChooserDialog.new issue

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#447]
When I try to create a Gtk::RecentChooserDialog.new I have a "Stack level too deep" error

For example in irb (the same error happens in scripts):

```
irb(main):001:0> require "gtk3"
=> true
irb(main):002:0> Gtk::RecentChooserDialog.new(:title => "toto")
SystemStackError: stack level too deep
	from /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.6/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.6/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.6/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.6/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.6/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.6/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.6/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.6/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.6/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.6/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.6/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.6/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.6/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.6/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.6/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.6/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'
... 3456 levels...
	from /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.6/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.6/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.6/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.6/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.6/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.6/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.6/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.6/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.6/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.6/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.6/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.6/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.6/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'
	from (irb):2:in `new'
	from (irb):2
	from /usr/bin/irb:11:in `<main>'irb(main):003:0> 

```

**Comment by kou** [comment]
Thanks for your report.
I've fixed it.
