### ISSUE TITLE
Gtk::Widget#style_get_property issue

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#454]
I am currently updating the sample script style_property.rb and I have a problem with the method 
`Gtk::Widget#style_get_property issue`

Here is the script:

```ruby
#!/usr/bin/env ruby
=begin
  style_property.rb - Ruby/GTK sample script.

  Copyright (c) 2004-2015 Ruby-GNOME2 Project Team
  This program is licenced under the same licence as Ruby-GNOME2.
=end

require 'gtk3'

class MyButton < Gtk::Button
  type_register

  def initialize(label = nil)
    # When type_register() is used.
    # super is equivalent to GLib::Object#initialize.
    super("label" => label)
  end

  install_style_property(GLib::Param::Int.new("foo", # name
					      "Foo", # nick
					      "FOO", # blurb
					      0,     #min 
					      100,   #max
					      5,     #default
					      GLib::Param::READABLE |
					      GLib::Param::WRITABLE)) do |pspec, str|
    p pspec, str
    str.to_i + 10  #return the converted value.
  end

  install_style_property(GLib::Param::Enum.new("bar", # name
					       "Bar", # nick
					       "BAR", # blurb
					       GLib::Type["GdkCursorType"], #Enum type
					       Gdk::CursorType::ARROW, #default
					       GLib::Param::READABLE |
					       GLib::Param::WRITABLE)) do |pspec, str|
    p pspec, str
    if str.strip! == "boat"
      Gdk::Cursor::BOAT
    else
      pspec.default
    end
  end
end

style_context = Gtk::StyleContext.new

provider = Gtk::CssProvider.new
provider.load(:data => DATA.read)

display = Gdk::Display.default
screen = display.default_screen
Gtk::StyleContext.add_provider_for_screen(screen, provider, Gtk::StyleProvider::PRIORITY_USER)

win = Gtk::Window.new("Gtk::RC sample")
b = MyButton.new("Hello")
b.signal_connect("clicked"){ Gtk.main_quit }

p MyButton.methods.grep(/properties/)
p MyButton.list_style_properties

win.set_default_size(100, 100)
win.add(b)
win.show_all
win.signal_connect("destroy"){ Gtk.main_quit }

# You need to call them after "Gtk::Widget#show"
# (Or in expose event).
p b.style_get_property("foo")
p cursor = b.style_get_property("bar")

Gtk.main

__END__
* {
  -GtkButton-foo: 30;
  -GtkButton-bar: boat;
}
```

When I run it I have this error:
```
[[#<GLib::Param::Float: Gtk::Widget#cursor-aspect-ratio>, #<GLib::Param::Boxed: Gtk::Widget#cursor-color>, #<GLib::Param::String: Gtk::Widget#focus-line-pattern>, #<GLib::Param::Int: Gtk::Widget#focus-line-width>, #<GLib::Param::Int: Gtk::Widget#focus-padding>, #<GLib::Param::Boolean: Gtk::Widget#interior-focus>, #<GLib::Param::Boxed: Gtk::Widget#link-color>, #<GLib::Param::Int: Gtk::Widget#scroll-arrow-hlength>, #<GLib::Param::Int: Gtk::Widget#scroll-arrow-vlength>, #<GLib::Param::Boxed: Gtk::Widget#secondary-cursor-color>, #<GLib::Param::Int: Gtk::Widget#separator-height>, #<GLib::Param::Int: Gtk::Widget#separator-width>, #<GLib::Param::Int: Gtk::Widget#text-handle-height>, #<GLib::Param::Int: Gtk::Widget#text-handle-width>, #<GLib::Param::Boxed: Gtk::Widget#visited-link-color>, #<GLib::Param::Boolean: Gtk::Widget#wide-separators>, #<GLib::Param::Boolean: Gtk::Widget#window-dragging>, #<GLib::Param::Int: Gtk::Button#child-displacement-x>, #<GLib::Param::Int: Gtk::Button#child-displacement-y>, #<GLib::Param::Boxed: Gtk::Button#default-border>, #<GLib::Param::Boxed: Gtk::Button#default-outside-border>, #<GLib::Param::Boolean: Gtk::Button#displace-focus>, #<GLib::Param::Int: Gtk::Button#image-spacing>, #<GLib::Param::Boxed: Gtk::Button#inner-border>, #<GLib::Param::Enum: MyButton#bar>, #<GLib::Param::Int: MyButton#foo>], 26]
/home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:351:in `validate_arguments': Gtk::Widget#style_get_property: wrong number of arguments (1 for 2) (ArgumentError)
	from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:535:in `block in define_method'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:540:in `call'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:540:in `block in define_method'
	from style_property.rb:70:in `<main>'
style_property.rb: line 0
   GLib-GObject-WARNING **:The property GtkWidget:style is deprecated and shouldn't be used anymore. It will be removed in a future version.

```

The C api is the following (from https://developer.gnome.org/gtk3/unstable/GtkWidget.html#gtk-widget-style-get-property) :

```C
void
gtk_widget_style_get_property (GtkWidget *widget,
                               const gchar *property_name,
                               GValue *value);
```

**Comment by kou** [comment]
Thanks for your report.
I've implemented it.
