### ISSUE TITLE
Best way to itterate over a Gtk::ListStore

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#463]
What is the best way to iterate through a Gtk::ListStore. I have this so far:

```ruby
require "gtk3"

model = Gtk::ListStore.new(TrueClass, String)

iter = model.append
iter[0] = false
iter[1] = "item1"
iter = model.append
iter[0] = false
iter[1] = "item2"
iter = model.append
iter[0] = false
iter[1] = "item3"

iter = model.iter_first
puts model.get_value(iter, 1) 
while(model.iter_next(iter)) do
  puts model.get_value(iter, 1) 
end
```

@kou 
I haven't see any script related to the basic usage of  a list store (creation, add/ remove/modify value, iterate). Maybe it could be a good start .

**Comment by kou** [comment]
Here is the best way:

```ruby
model.each do |_model, path, iter|
  puts iter[1]
end
```

By the way, `append` and `iter[]=` is bored.

```ruby
model.append(0 => false,
             1 => "item1")
model.append(0 => false,
             1 => "item2")
model.append(0 => false,
             1 => "item3")
```

or

```ruby
model.append.set_values(0 => false,
                        1 => "item1")
model.append.set_values(0 => false,
                        1 => "item2")
model.append.set_values(0 => false,
                        1 => "item3")
```

may be better.

Um... It seems that the latter is better because there are some `append` family such as `prepend`.

**Comment by cedlemo** [comment]
Thanks.

**Comment by cedlemo** [comment]
Sorry but I closed it whitout testing. When I test I have an error:

```ruby
model = Gtk::ListStore.new(TrueClass, String)

(1..5).each do |i|
  model.append(false,"item#{i}")
end
```

error message:
```
/home/cedlemo/.gem/ruby/2.2.0/gems/gtk3-2.2.6/lib/gtk3/list-store.rb:47:in `append': wrong number of arguments (2 for 0) (ArgumentError)
```

And

```ruby
model = Gtk::ListStore.new(TrueClass, String)

(1..5).each do |i|
  model.append.set_values(false, "item#{i}")
end
```

Error message:

    combobox_from_cellrender.rb:8:in `block in <main>': undefined method `set_values' for #<Gtk::TreeIter:0x13fc7c0 ptr=0x1c20b40 own=true> (NoMethodError)

**Comment by kou** [comment]
I've added `Gtk::TreeIter#set_values`.
