### ISSUE TITLE
Gtk::TreeModelFilterVisibleFunc callback not supported yet

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#475]
I am updating treemodelfiler.rb and this part of the script : 

```ruby
require 'gtk3'

ls = Gtk::ListStore.new(String, Integer)

column1 = Gtk::TreeViewColumn.new("data1",
				 Gtk::CellRendererText.new, {:text => 0})
column2 = Gtk::TreeViewColumn.new("data2",
				 Gtk::CellRendererText.new, {:text => 1})

mf = Gtk::TreeModelFilter.new( :child_model => ls)
mf.set_visible_func do |model, iter|
  /a/ =~ iter[0]
end
```

exit with this message:

```
/home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:551:in `invoke': TODO: <TreeModelFilterVisibleFunc>(func) callback is not supported yet. (NotImplementedError)
	from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:551:in `block in define_method'
	from treemodelfilter.rb:20:in `<main>'

```

**Comment by kou** [comment]
I've supported it!

**Comment by cedlemo** [comment]
Thanks!!
