### ISSUE TITLE
TODO: GIArgument(array)[array] -> Ruby (NotImplementedError)

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#496]
Here is the script that send me this error:

```ruby
require "gtk3"
require "vte3"
# encoding: UTF-8
p "System #{Encoding.find("filesystem")}"

vte = Vte::Terminal.new
vte.set_encoding("UTF-8")
p "vte #{vte.encoding}"
vte.spawn(:argv => GLib::Shell.parse("bash"),
          :spawn_flags => GLib::Spawn::SEARCH_PATH)
vte.signal_connect("child-exited") do
  Gtk.main_quit
end

str = "toto"
len = str.bytesize
window = Gtk::Window.new
window.add(vte)

window.show_all
window.signal_connect("delete-event") { Gtk.main_quit }

str_start = vte.cursor_position
puts str_start
vte.feed_child(str,str.bytesize)
str_end = vte.cursor_position

puts vte.get_text_range(str_start[0], str_start[1],str_end[0], str_end[1])

Gtk.main

```

Here is the full error message:

```
"System UTF-8"
"vte UTF-8"
0
0
/home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:551:in `invoke': TODO: GIArgument(array)[array] -> Ruby (NotImplementedError)
	from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:551:in `block in define_method'
	from vte3_terminal_fd_read.rb:28:in `<main>'
vte3_terminal_fd_read.rb: line 0
   GLib-GObject-WARNING **:The property GtkWidget:style is deprecated and shouldn't be used anymore. It will be removed in a future version.
```

**Comment by kou** [comment]
I've added its support.
