### ISSUE TITLE
New gio segfault reported!

### ISSUE THREAD

**Issue by dark-yux** [ruby-gnome2/ruby-gnome2#501]
See new comment on #301

**Comment by cedlemo** [comment]
@kou : 

when I run in a script:

```ruby
require "gtk3"
require "gio2"
v = Gio::VolumeMonitor.get
v.mounts
```

Error message:

```
/home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:551:in `invoke': TODO: GIArgument(GList)[interface(interface)](GMount) -> Ruby (NotImplementedError)
	from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:551:in `block in define_method'
	from volume_monitor.rb:4:in `<main>'
```

**Comment by kou** [comment]
Thanks for your report.
I've fixed it at master.
