### ISSUE TITLE
Gtk::Application and the open signal

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#508]
I have some difficulties to use the open signal. As you know when you pass files names as argument to the "run" method, it fires the open signal. (https://wiki.gnome.org/HowDoI/GtkApplication _dealing with the command line_)

Here is the script : 

```ruby
require "gtk3"

require "fileutils"

current_path = File.expand_path(File.dirname(__FILE__))
gresource_bin = "#{current_path}/exampleapp.gresource"
gresource_xml = "#{current_path}/exampleapp.gresource.xml"

Dir.chdir(File.dirname(gresource_xml)) do
  system("glib-compile-resources",
         "--target", gresource_bin,
         File.basename(gresource_xml))
end

at_exit do
  FileUtils.rm_f(gresource_bin)
end

resource = Gio::Resource.load(gresource_bin)
Gio::Resources.register(resource)

class ExampleAppWindow < Gtk::ApplicationWindow
  type_register
  class << self
    def init
      set_template(:resource => "/org/gtk/exampleapp/window.ui")
    end
  end

  def initialize(application)
    super(:application => application)
  end

  def open(file)
    basename = File.basename(file)
    scrolled = Gtk::ScrolledWindow.new
    scrolled.show
    scrolled.set_hexpand(true)
    scrolled.set_vexpand(true)
    view = Gtk::View.new
    view.set_editable(false)
    view.set_cursor_visible(false)
    view.show
    scrolled.add(view)
    stack.add_titled(scrolled, basename, basename)
    view.buffer = File.read(file)
  end
end

class ExampleApp < Gtk::Application
  def initialize
    super("org.gtk.exampleapp", :handles_open)

    signal_connect "activate" do |application|
      window = ExampleAppWindow.new(application)
      window.present
    end

    signal_connect "open" do |application, files, n_files, hint|
      windows = application.windows
      win = nil
      puts application.class
      puts files.class
      puts n_files.class
      puts hint.class
      unless windows.empty?
        win = windows.first
      else
        win = ExampleAppWindow.new(application)
      end

      files.each { |file| win.open(file) }
        
      win.present
    end

  end
end

app = ExampleApp.new

puts app.run(ARGV)
```
The script name is exampleapp3.rb the rest of the files are valid files in the current directory
```
ruby exampleapp3.rb example-0.rb  example-1.rb  example-2.rb  example-4.rb  exampleapp1.rb  exampleapp2.rb  exampleapp3.rb
/home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb: line 551
   Gtk-DEBUG **:Connecting to session manager
ExampleApp
GLib::Pointer
Fixnum
String
exampleapp3.rb:72:in `block in initialize': undefined method `each' for #<GLib::Pointer:0x0000000459e440>
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:551:in `call'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:551:in `invoke'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:551:in `block in define_method'
	 from exampleapp3.rb:82:in `<main>'
```

As you see those lines:

```ruby
signal_connect "open" do |application, files, n_files, hint|
      windows = application.windows
      win = nil
      puts application.class
      puts files.class
      puts n_files.class
      puts hint.class
```

reports:

```
ExampleApp
GLib::Pointer
Fixnum
String
```

I don't know how to deal with the GLib::Pointer. Furthermore, n_files is equal to 6 which doesn't correspond to the arguments numbers.

**Comment by kou** [comment]
I've implemented the `open` signal. Try the following code:

```ruby
    signal_connect "open" do |application, files, hint|
```

Note that `files` isn't an `Array` of file name. It's an `Array` of `Gio::File`. You can't use `File.basename(files[0])`. Use `Gio::File#path` when you want to get path.

**Comment by cedlemo** [comment]
Thanks!
