### ISSUE TITLE
TODO: Ruby -> GIArgument(interface)[callback]: <Callback>

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#513]
@kou 
This issue is related to the issue #512. 

Here is the full script:

```ruby
require "gtk3"

require "fileutils"

current_path = File.expand_path(File.dirname(__FILE__))
gresource_bin = "#{current_path}/exampleapp.gresource.1"
gresource_xml = "#{current_path}/exampleapp.gresource.xml.1"

Dir.chdir(File.dirname(gresource_xml)) do
  system("glib-compile-resources",
         "--target", gresource_bin,
         File.basename(gresource_xml))
end

at_exit do
  FileUtils.rm_f(gresource_bin)
end

resource = Gio::Resource.load(gresource_bin)
Gio::Resources.register(resource)

class ExampleAppWindow < Gtk::ApplicationWindow
  # https://github.com/ruby-gnome2/ruby-gnome2/pull/445
  # https://github.com/ruby-gnome2/ruby-gnome2/issues/503
  type_register
  class << self
    def init
      set_template(:resource => "/org/gtk/exampleapp/window.ui")
      bind_template_child("stack")
    end
  end

  def initialize(application)
    super(:application => application)
  end

  def open(file)
    basename = file.basename
    scrolled = Gtk::ScrolledWindow.new
    scrolled.show
    scrolled.set_hexpand(true)
    scrolled.set_vexpand(true)
    view = Gtk::TextView.new
    view.set_editable(false)
    view.set_cursor_visible(false)
    view.show
    scrolled.add(view)
    stack.add_titled(scrolled, basename, basename)
    stream = file.read
    view.buffer.text = stream.read
  end
end

class ExampleApp < Gtk::Application
  def initialize
    super("org.gtk.exampleapp", :handles_open)

    signal_connect "startup" do |application|
      quit_accels = ["<Ctrl>Q","<Ctrl>O"]
      act_en = Gtk::ActionEntry.new
      act_en.name = "quit"
      act_en.callback = proc do |a1, a2|
        puts "toto"
      end
      application.add_action_entries([act_en], 1)
      application.set_accels_for_action("app.quit", quit_accels)
    
      builder = Gtk::Builder.new(:resource => "/org/gtk/exampleapp/app-menu.ui")
      app_menu = builder.get_object("appmenu")
      application.set_app_menu(app_menu)

    end
    signal_connect "activate" do |application|
      window = ExampleAppWindow.new(application)
      window.present
    end

    signal_connect "open" do |application, files, hint|
      windows = application.windows
      win = nil
      unless windows.empty?
        win = windows.first
      else
        win = ExampleAppWindow.new(application)
      end

      files.each { |file| win.open(file) }
        
      win.present
    end

  end
end

app = ExampleApp.new

puts app.run([$0] + ARGV)
```

When I run it, with : 

    ruby exampleapp4.rb example-0.rb  example-1.rb  example-2.rb  example-4.rb  exampleapp1.rb  exampleapp2.rb  exampleapp3.rb

I have this message:

```
home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb: line 551
   Gtk-DEBUG **:Connecting to session manager
/home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb: line 267
   (null)-CRITICAL **:g_registered_type_info_get_g_type: assertion 'GI_IS_REGISTERED_TYPE_INFO (info)' failed
/home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:267:in `set_field_value': TODO: Ruby -> GIArgument(interface)[callback]: <Callback>
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:267:in `block in load_field'
	 from exampleapp4.rb:62:in `block in initialize'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:551:in `call'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:551:in `invoke'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:551:in `block in define_method'
	 from exampleapp4.rb:97:in `<main>'

```

All the files needed to run this script can be found here:

    https://github.com/cedlemo/ruby-gtk3-tutorial

**Comment by kou** [comment]
`GtkActionEntry` has been deprecated since GTK+ 3.10: https://developer.gnome.org/gtk3/stable/GtkActionGroup.html#GtkActionEntry

We should use `GSimpleAction` instead: https://developer.gnome.org/gio/stable/GSimpleAction.html

I'm working on it. (I'm implementing [`GVariantType`](https://developer.gnome.org/glib/unstable/glib-GVariantType.html) that is needed by `GSimpleAction`.) Please wait.

**Comment by kou** [comment]
Try the following patch:

```text
diff --git a/samples/exampleapp4.rb b/samples/exampleapp4.rb
index 8c9fca6..577d29f 100644
--- a/samples/exampleapp4.rb
+++ b/samples/exampleapp4.rb
@@ -57,12 +57,11 @@ class ExampleApp < Gtk::Application
 
     signal_connect "startup" do |application|
       quit_accels = ["<Ctrl>Q","<Ctrl>O"]
-      act_en = Gtk::ActionEntry.new
-      act_en.name = "quit"
-      act_en.callback = proc do |a1, a2|
+      action = Gio::SimpleAction.new("quit")
+      action.signal_connect("activate") do |_action, parameter|
         puts "toto"
       end
-      application.add_action_entries([act_en], 1)
+      application.add_action(action)
       application.set_accels_for_action("app.quit", quit_accels)
     
       builder = Gtk::Builder.new(:resource => "/org/gtk/exampleapp/app-menu.ui")
```

**Comment by cedlemo** [comment]
Wow, it works great.

A last question before closing this:

As you can see some application examples have different gresource and ui files. In my github repo I have just added a number to them (exampleapp.gresource.1). 

In the original examples, they use a directory for each examples which is easier to compile them and you can directly see which files are associated.

Should I do the same for example create a directory for each application or just create a *data/exampleappn* structure where I would put the related gresource and ui files for each examples?

**Comment by kou** [comment]
> Wow, it works great.

Thanks for trying it. :-)

> Should I do the same for example create a directory for each application

Yes. I think so.

**Comment by cedlemo** [comment]
Ok I will send a pull request with the new files organization.
