### ISSUE TITLE
TODO: GIArgument(gunichar) -> Ruby (NotImplementedError)

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#529]
Here is a minimum script that reproduces the pb:

```ruby
require "gtk3"

view = Gtk::TextView.new
buffer = view.buffer
buffer.text = "ruby gnome gtk3 gstreamer vte3"
start = buffer.start_iter

puts start.char
```

The full error message:

```
/home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:551:in `invoke': TODO: GIArgument(gunichar) -> Ruby (NotImplementedError)
	from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:551:in `block in define_method'
	from buffer_iter.rb:8:in `<main>'
```

**Comment by kou** [comment]
Thanks for your report.
I've fixed it!
