### ISSUE TITLE
gtk3: Gtk::Widget#render_icon_pixbuf doesn't work

### ISSUE THREAD

**Issue by myokoym** [ruby-gnome2/ruby-gnome2#544]
I found the problem in the following line in my softoware with master branch of Ruby-GNOME2:

https://github.com/myokoym/mireru/blob/master/lib/mireru/navigator.rb#L164

## minimum reproducible code

```ruby
require "gtk3"

window = Gtk::Window.new
window.render_icon_pixbuf(Gtk::Stock::DIRECTORY, :menu)
```

## stack trace

```
/.../gobject-introspection-3.0.2/lib/gobject-introspection/loader.rb:551:in `invoke': no implicit conversion of Symbol into Integer (TypeError)
        from /.../gobject-introspection-3.0.2/lib/gobject-introspection/loader.rb:551:in `block in define_method'
        from /.../sample.rb:4:in `<main>'
```

**Comment by cedlemo** [comment]
It works with `Gtk::IconSize::MENU` if you are in a hurry, If I well remember, @kou prefers  the usage of `:menu` instead of `Gtk::IconSize::MENU`, even if both will work,  so I think he will implement it when he will be able to.

**Comment by cedlemo** [comment]
FYI I was able to run (I didn't test it all) after those modifications:

```
diff --git a/lib/mireru/navigator.rb b/lib/mireru/navigator.rb
index 9f9e7f6..fbb1330 100644
--- a/lib/mireru/navigator.rb
+++ b/lib/mireru/navigator.rb
@@ -99,7 +99,7 @@ module Mireru
       tree_view.append_column(column)
 
       renderer = Gtk::CellRendererPixbuf.new
-      renderer.set_fixed_size(*Gtk::IconSize.lookup(:menu))
+      #renderer.set_fixed_size(Gtk::IconSize::MENU)
       column.pack_start(renderer, :expand => false)
       column.add_attribute(renderer, :pixbuf, ICON_COLUMN)
 
@@ -161,7 +161,7 @@ module Mireru
       iter.set_value(FILENAME_COLUMN, File.basename(file))
       if File.directory?(file)
         @dir_iters[file] = iter unless recursive
-        dir_icon = self.render_icon_pixbuf(Gtk::Stock::DIRECTORY, :menu)
+        dir_icon = self.render_icon_pixbuf(Gtk::Stock::DIRECTORY, Gtk::IconSize::MENU)
         iter.set_value(ICON_COLUMN, dir_icon)
         load_dir(model, file, iter, recursive) if recursive
       else
@@ -179,9 +179,9 @@ module Mireru
         @icons[content_type] = Gdk::Pixbuf.new(icon_path)
       else
         if Widget.video?(file) or Widget.music?(file)
-          @icons[content_type] = self.render_icon_pixbuf(Gtk::Stock::CDROM, :menu)
+          @icons[content_type] = self.render_icon_pixbuf(Gtk::Stock::CDROM, Gtk::IconSize::MENU)
         else
-          @icons[content_type] = self.render_icon_pixbuf(Gtk::Stock::FILE, :menu)
+          @icons[content_type] = self.render_icon_pixbuf(Gtk::Stock::FILE, Gtk::IconSize::MENU)
         end
       end
       @icons[content_type]
@@ -192,9 +192,9 @@ module Mireru
       icon = content_type.icon
 
       icon_theme = Gtk::IconTheme.new
-      icon_info = icon_theme.lookup_icon(icon,
+      icon_info = icon_theme.lookup_icon(icon.names[0],
                                          16,
-                                         Gtk::IconTheme::LookupFlags::GENERIC_FALLBACK)
+                                         Gtk::IconLookupFlags::GENERIC_FALLBACK)
 
       if icon_info
         icon_info.filename
```

**Comment by kou** [comment]
Thanks for your report.
Your code will work well without change with gtk3 at master.

**Comment by kou** [comment]
FYI: `Symbol` is recommended rather than constant to refer defined enums as @cedlemo said. Because users don't need to care about namespace. Users just know enum name.

For example, you can write `:generic_fallback` instead of `Gtk::IconTheme::LookupFlags::GENERIC_FALLBACK`.

**Comment by myokoym** [comment]
Thank you @cedlemo and @kou! I'll confirm it later.
