### ISSUE TITLE
Can not use a template on a widget without using the method bind_template_child

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#549]
Since the commits f9f95675797435fe0e8a743de63860cabb0ff7e9, f12140f8d1cb67b5dd5b97fd799523f384780bcb and 3f1db9a48b1b2799c796afbaed883af53dd3298d,a user can not set a template to a widget without using  `Gtk::Widget#bind_template_child`.

For example this command in  the ruby-gnome2 dir:

    ruby gtk3/sample/tutorial/exampleapp2/exampleapp.rb gtk3/sample/tutorial/*.rb

Doesn't work anymore:

```
/home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-3.0.3/lib/gobject-introspection/loader.rb: line 551
   Gtk-DEBUG **:Connecting to session manager
/home/cedlemo/.gem/ruby/2.2.0/gems/gtk3-3.0.3/lib/gtk3/widget.rb:115:in `initialize_post': undefined method `each' for nil:NilClass
	 from gtk3/sample/tutorial/exampleapp2/exampleapp.rb:51:in `initialize'
	 from gtk3/sample/tutorial/exampleapp2/exampleapp.rb:51:in `initialize'
	 from gtk3/sample/tutorial/exampleapp2/exampleapp.rb:64:in `new'
	 from gtk3/sample/tutorial/exampleapp2/exampleapp.rb:64:in `block in initialize'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-3.0.3/lib/gobject-introspection/loader.rb:551:in `call'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-3.0.3/lib/gobject-introspection/loader.rb:551:in `invoke'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-3.0.3/lib/gobject-introspection/loader.rb:551:in `block in define_method'
	 from gtk3/sample/tutorial/exampleapp2/exampleapp.rb:87:in `<main>'

```

**Comment by kou** [comment]
Oh...
I've fixed it.
