### ISSUE TITLE
gtksourceview3 git head: many test suite fail

### ISSUE THREAD

**Issue by mtasaka** [ruby-gnome2/ruby-gnome2#559]
With gtksourceview3 git head 9dd7fe9d3d2acadb2aed7ac096d12dda537bedf1 many test fail like:
```
E
===============================================================================
Error: test_text(TestGutterRendererText): NameError: uninitialized constant GtkSource::GutterRendererText
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gtksourceview3/test/test-source-gutter-renderer.rb:19:in `setup'
===============================================================================
E
===============================================================================
Error: test_language(TestLanguageManager): NameError: uninitialized constant GtkSource::LanguageManager
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gtksourceview3/test/test-source-language-manager.rb:19:in `setup'
===============================================================================
E
===============================================================================
Error: test_language_ids(TestLanguageManager): NameError: uninitialized constant GtkSource::LanguageManager
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gtksourceview3/test/test-source-language-manager.rb:19:in `setup'
===============================================================================
E
===============================================================================
Error: test_search_path(TestLanguageManager): NameError: uninitialized constant GtkSource::LanguageManager
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gtksourceview3/test/test-source-language-manager.rb:19:in `setup'
===============================================================================
E
===============================================================================
Error: test_background(TestMarkAttributes): NameError: uninitialized constant GtkSource::MarkAttributes
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gtksourceview3/test/test-mark-attributes.rb:19:in `setup'
===============================================================================
E
===============================================================================
Error: test_auto_indent(TestSourceView): NameError: uninitialized constant GtkSource::View
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gtksourceview3/test/test-source-view.rb:21:in `setup'
===============================================================================
E
===============================================================================
Error: test_indent_width(TestSourceView): NameError: uninitialized constant GtkSource::View
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gtksourceview3/test/test-source-view.rb:21:in `setup'
===============================================================================
E
===============================================================================
Error: test_insert_spaces_instead_of_tabs(TestSourceView): NameError: uninitialized constant GtkSource::View
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gtksourceview3/test/test-source-view.rb:21:in `setup'
===============================================================================
E
===============================================================================
Error: test_line_number(TestSourceView): NameError: uninitialized constant GtkSource::View
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gtksourceview3/test/test-source-view.rb:21:in `setup'
===============================================================================
E
===============================================================================
Error: test_right_margin_position(TestSourceView): NameError: uninitialized constant GtkSource::View
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gtksourceview3/test/test-source-view.rb:21:in `setup'
===============================================================================
E
===============================================================================
Error: test_show_right_margin(TestSourceView): NameError: uninitialized constant GtkSource::View
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gtksourceview3/test/test-source-view.rb:21:in `setup'
===============================================================================
```

Note that other than the above failures #558 also fails on gtksourceview3. Not tested 3.0.3 tag yet

**Comment by kou** [comment]
Thanks for your report.
It seems that these failures are caused by #558. We should solve #558 before this.

You don't need to test with 3.0.3 tag.

**Comment by mtasaka** [comment]
With 66ccef02ba317e3b58e46b451306bbf8f745d66b I don't see this error any longer, thank you.
