### ISSUE TITLE
gtk3: test failure on git head

### ISSUE THREAD

**Issue by mtasaka** [ruby-gnome2/ruby-gnome2#564]
With 66ccef02ba317e3b58e46b451306bbf8f745d66b now gtk3 test does not see #558 any longer and now I see different errors like:
```
2015-09-21 16:19:30 +0900 running test for /home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gtk3
--------------------------------------------------------------------------------
Loaded suite .
Started/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gtk3/test/test-gc.rb: line 7
   GLib-GObject-WARNING **:The property GtkWidget:style is deprecated and shouldn't be used anymore. It will be removed in a future version.

....O
===============================================================================
XSETTINGS is required. [test: custom type(TestGdkScreen::#get_setting)]
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gtk3/test/test-gdk-screen.rb:36:in `block (2 levels) in <class:TestGdkScreen>'
===============================================================================
......................../home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb: line 551
   GLib-GObject-WARNING **:The property GtkButton:use-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb: line 551
   GLib-GObject-WARNING **:The property GtkSettings:gtk-button-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
...........................F
===============================================================================
Failure: test: no argument(TestGtkColorChooserDialog::.new)
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gtk3/test/test-gtk-color-chooser-dialog.rb:24:in `block (2 levels) in <class:TestGtkColorChooserDialog>'
     21:     test "no argument" do
     22:       dialog = Gtk::ColorChooserDialog.new
     23:       if csd_supported?
  => 24:         assert_equal("", dialog.title)
     25:       else
     26:         assert_nil(dialog.title)
     27:       end
<""> expected but was
<nil>
===============================================================================
.........................................../usr/share/gems/gems/test-unit-3.1.3/lib/test/unit/fixture.rb: line 44
   (null)-WARNING **:atkobject.c:1384: invalid property id 10 for "accessible-table-column-header" of type 'GParamObject' in 'GtkAccessible'
/usr/share/gems/gems/test-unit-3.1.3/lib/test/unit/fixture.rb: line 44
   (null)-WARNING **:atkobject.c:1384: invalid property id 12 for "accessible-table-row-header" of type 'GParamObject' in 'GtkAccessible'
/usr/share/gems/gems/test-unit-3.1.3/lib/test/unit/fixture.rb: line 44
   (null)-WARNING **:atkobject.c:1384: invalid property id 10 for "accessible-table-column-header" of type 'GParamObject' in 'GtkAccessible'
/usr/share/gems/gems/test-unit-3.1.3/lib/test/unit/fixture.rb: line 44
   (null)-WARNING **:atkobject.c:1384: invalid property id 12 for "accessible-table-row-header" of type 'GParamObject' in 'GtkAccessible'
......F
===============================================================================
Failure: test: no argument(TestGtkFontChooserDialog::.new)
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gtk3/test/test-gtk-font-chooser-dialog.rb:24:in `block (2 levels) in <class:TestGtkFontChooserDialog>'
     21:     test "no argument" do
     22:       dialog = Gtk::FontChooserDialog.new
     23:       if csd_supported?
  => 24:         assert_equal("", dialog.title)
     25:       else
     26:         assert_nil(dialog.title)
     27:       end
<""> expected but was
<nil>
===============================================================================
===============================================================================
.................................O
===============================================================================
GTK+ 3.16 doesn't support getting resource path. See GitHub#461. [test: resource(TestGtkImage::.new)]
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gtk3/test/test-gtk-image.rb:49:in `block (2 levels) in <class:TestGtkImage>'
===============================================================================
...............................................................................
....................../home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb: line 551
   Gtk-WARNING **:Style property "nonexistent" is not registered
.............................../home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb: line 307
   GLib-GObject-WARNING **:The property GtkToolButton:stock-id is deprecated and shouldn't be used anymore. It will be removed in a future version.
..........................
..........................

Finished in 6.183407471 seconds.
------
325 tests, 385 assertions, 2 failures, 0 errors, 0 pendings, 2 omissions, 0 notifications
99.3808% passed
------
```

GTK is again 3.17.9.

**Comment by kou** [comment]
Thanks for your report.
I changed the expected values at master. Could you try master again?

I think that https://git.gnome.org/browse/gtk+/commit/?id=03213b9509fc1df16c66194ea168aed6c15110e9 commit may change GTK+ behavior.

**Comment by mtasaka** [comment]
Okay, now with git head I don't see this test failure, thank you!

**Comment by kou** [comment]
Thanks for confirming it.
gtk3 3.0.4 includes this change.
