### ISSUE TITLE
glib 3.0.4: test does not pass on i686 (not x86_64)

### ISSUE THREAD

**Issue by mtasaka** [ruby-gnome2/ruby-gnome2#565]
glib 3.0.4 does not pass test on i686 (not x86_64)
```
+ ruby -Ilib:test:ext/glib2 ./test/run-test.rb
Loaded suite test
Started
...............................................................................
....................../builddir/build/BUILD/rubygem-glib2-3.0.4/usr/share/gems/gems/glib2-3.0.4/test/test_iochannel.rb: line 39
   GLib-CRITICAL **:g_io_channel_read_to_end: assertion 'channel->is_readable' failed
/builddir/build/BUILD/rubygem-glib2-3.0.4/usr/share/gems/gems/glib2-3.0.4/test/test_iochannel.rb: line 54
   GLib-CRITICAL **:g_io_channel_read_to_end: assertion 'channel->is_readable' failed
./builddir/build/BUILD/rubygem-glib2-3.0.4/usr/share/gems/gems/glib2-3.0.4/test/test_iochannel.rb: line 59
   GLib-WARNING **:Invalid file descriptor.
........................E
===============================================================================
Error: test_over_guint32_value(TestGLibFileUtils::#format_size): RangeError: bignum too big to convert into `unsigned long'
/builddir/build/BUILD/rubygem-glib2-3.0.4/usr/share/gems/gems/glib2-3.0.4/test/test_file_utils.rb:52:in `format_size'
/builddir/build/BUILD/rubygem-glib2-3.0.4/usr/share/gems/gems/glib2-3.0.4/test/test_file_utils.rb:52:in `test_over_guint32_value'
     49: 
     50:     def test_over_guint32_value
     51:       guint32_max = 2 ** 32 - 1
  => 52:       assert_equal("4.3 GB", GLib.format_size(guint32_max + 1))
     53:     end
     54: 
     55:     sub_test_case "flags" do
===============================================================================
.......E
===============================================================================`Error: test_over_guint32_value(TestGLibFileUtils::#format_size_for_display): RangeError: bignum too big to convert into `unsigned long'
/builddir/build/BUILD/rubygem-glib2-3.0.4/usr/share/gems/gems/glib2-3.0.4/test/test_file_utils.rb:29:in `format_size_for_display'
/builddir/build/BUILD/rubygem-glib2-3.0.4/usr/share/gems/gems/glib2-3.0.4/test/test_file_utils.rb:29:in `test_over_guint32_value'
     26: 
     27:     def test_over_guint32_value
     28:       guint32_max = 2 ** 32 - 1
  => 29:       assert_equal("4.0 GB", GLib.format_size_for_display(guint32_max + 1))
     30:     end
     31:   end
     32: 
===============================================================================
...............................................................................
.................................................O
===============================================================================
Only for Win32 platform [test_get_package_install_directory_of_module(TestGLibWin32)]
/builddir/build/BUILD/rubygem-glib2-3.0.4/usr/share/gems/gems/glib2-3.0.4/test/glib-test-utils.rb:10:in `only_win32'
===============================================================================
...
Finished in 0.147502616 seconds.
------
267 tests, 503 assertions, 0 failures, 2 errors, 0 pendings, 1 omissions, 0 notifications
99.2481% passed
------
```

**Comment by mtasaka** [comment]
So as g_format_size_for_display has argument (goffset size) and goffset is guint64, perhaps NUM2OFFT should be used.

**Comment by mtasaka** [comment]
... and also for g_format_size() NUM2ULONG should be changed (g_format_size uses guint64)

**Comment by kou** [comment]
Thanks for your report.
Could you try master?

`NUM2OFFT` and `NUM2ULL` are used.

**Comment by mtasaka** [comment]
Well, and also for g_format_size_full() (this also uses guint64), this should be enough.

**Comment by kou** [comment]
Oh. I missed it.
I've also changed it.

**Comment by mtasaka** [comment]
Now test passes, thank you!

**Comment by kou** [comment]
Thanks for confirming this again!
