### ISSUE TITLE
vte3 3.0.4 does not pass test

### ISSUE THREAD

**Issue by mtasaka** [ruby-gnome2/ruby-gnome2#566]
vte3 3.0.4 does not pass tests:
```
--------------------------------------------------------------------------------
2015-09-21 22:13:38 +0900 running test for /home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/vte3
--------------------------------------------------------------------------------
Loaded suite .
Started
..E
===============================================================================
Error: test_term(TestPty): NoMethodError: undefined method `term=' for #<Vte::Pty:0x556c5dabcad8 ptr=0x556c5dac49c0>
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/vte3/test/test-pty.rb:38:in `test_term'
     35: 
     36:   def test_term
     37:     term_type = "vt100"
  => 38:     @pty.term = term_type
     39:     assert_equal(term_type, @pty.term)
     40:   end
     41: 
===============================================================================
../home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/vte3/test/test-terminal.rb:40:in `block (3 levels) in <class:TestTerminal>': 'Vte::Terminal#fork_command' has been deprecated. Use 'Vte::Terminal#spawn'.
./home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/vte3/test/test-terminal.rb:32:in `block (2 levels) in <class:TestTerminal>': 'Vte::Terminal#fork_command' has been deprecated. Use 'Vte::Terminal#spawn'.
...E
===============================================================================
Error: test_background_image_file(TestTerminalProperties): NoMethodError: undefined method `background_image_file=' for #<Vte::Terminal:0x556c5d0b1bb0 ptr=0x556c5df17fa0>
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/vte3/test/test-terminal-properties.rb:36:in `test_background_image_file'
     33: 
     34:   def test_background_image_file
     35:     image_name = "image_file"
  => 36:     @terminal.background_image_file = image_name
     37:     assert_equal(image_name, @terminal.background_image_file)
     38:   end
     39: 
===============================================================================
E
===============================================================================
Error: test_backspace_binding(TestTerminalProperties): NameError: uninitialized constant Vte::TerminalEraseBinding
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/glib2/lib/glib2/deprecatable.rb:96:in `const_missing'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/vte3/test/test-terminal-properties.rb:41:in `test_backspace_binding'
     38:   end
     39: 
     40:   def test_backspace_binding
  => 41:     bind = Vte::TerminalEraseBinding::DELETE_SEQUENCE
     42:     @terminal.backspace_binding = bind
     43:     assert_equal(bind, @terminal.backspace_binding)
     44:   end
===============================================================================
E
===============================================================================
Error: test_cursor_blink_mode(TestTerminalProperties): NameError: uninitialized constant Vte::TerminalCursorBlinkMode
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/glib2/lib/glib2/deprecatable.rb:96:in `const_missing'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/vte3/test/test-terminal-properties.rb:47:in `test_cursor_blink_mode'
     44:   end
     45: 
     46:   def test_cursor_blink_mode
  => 47:     cursor_mode = Vte::TerminalCursorBlinkMode::ON
     48:     @terminal.cursor_blink_mode = cursor_mode
     49:     assert_equal(cursor_mode, @terminal.cursor_blink_mode)
     50:   end
===============================================================================
E
===============================================================================
Error: test_cursor_shape(TestTerminalProperties): NameError: uninitialized constant Vte::TerminalCursorShape
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/glib2/lib/glib2/deprecatable.rb:96:in `const_missing'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/vte3/test/test-terminal-properties.rb:53:in `test_cursor_shape'
     50:   end
     51: 
     52:   def test_cursor_shape
  => 53:     shape = Vte::TerminalCursorShape::IBEAM
     54:     @terminal.cursor_shape = shape
     55:     assert_equal(shape, @terminal.cursor_shape)
     56:   end
===============================================================================
E
===============================================================================
Error: test_delete_binding(TestTerminalProperties): NameError: uninitialized constant Vte::TerminalEraseBinding
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/glib2/lib/glib2/deprecatable.rb:96:in `const_missing'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/vte3/test/test-terminal-properties.rb:59:in `test_delete_binding'
     56:   end
     57: 
     58:   def test_delete_binding
  => 59:     bind = Vte::TerminalEraseBinding::ASCII_DELETE
     60:     @terminal.delete_binding = bind
     61:     assert_equal(bind, @terminal.delete_binding)
     62:   end
===============================================================================
E
===============================================================================
Error: test_emulation(TestTerminalProperties): NoMethodError: undefined method `emulation=' for #<Vte::Terminal:0x556c5d03e908 ptr=0x556c5e131f80>
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/vte3/test/test-terminal-properties.rb:65:in `test_emulation'
     62:   end
     63:   def test_emulation
     64:     terminal_type = "vt100"
  => 65:     @terminal.emulation = terminal_type
     66:     assert_equal(terminal_type, @terminal.emulation)
     67:   end
     68: 
===============================================================================
....E
===============================================================================
Error: test_scroll_background(TestTerminalProperties): NoMethodError: undefined method `scroll_background=' for #<Vte::Terminal:0x556c5e34a880 ptr=0x556c5e347970>
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/vte3/test/test-terminal-properties.rb:95:in `test_scroll_background'
     92: 
     93:   def test_scroll_background
     94:     scroll = true
  => 95:     @terminal.scroll_background = scroll
     96:     assert_true(@terminal.scroll_background?)
     97:   end
     98: 
===============================================================================
...E
===============================================================================
Error: test_visible_bell(TestTerminalProperties): NoMethodError: undefined method `visible_bell=' for #<Vte::Terminal:0x556c5e4fba80 ptr=0x556c5e4f5fc0>
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/vte3/test/test-terminal-properties.rb:119:in `test_visible_bell'
     116: 
     117:   def test_visible_bell
     118:     visible = true
  => 119:     @terminal.visible_bell = visible
     120:     assert_true(@terminal.visible_bell?)
     121:   end
     122: end
===============================================================================
E
===============================================================================
Error: test_beep_signal(TestTerminalSignals): GLib::NoSignalError: no such signal: beep
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/glib2/lib/glib2/deprecatable.rb:85:in `signal_connect'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/glib2/lib/glib2/deprecatable.rb:85:in `block (3 levels) in extended'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/vte3/test/test-terminal-signals.rb:24:in `test_beep_signal'
     21: 
     22:   def test_beep_signal
     23:     called = false
  => 24:     @terminal.signal_connect("beep") do
     25:       called = true
     26:     end
     27:     @terminal.signal_emit("beep")
===============================================================================
......

Finished in 1.486687189 seconds.
------
31 tests, 21 assertions, 0 failures, 10 errors, 0 pendings, 0 omissions, 0 notifications
67.7419% passed
------
```

Using vte3 0.36.4 .

**Comment by kou** [comment]
Thanks for your report.
I've fixed them.

**Comment by mtasaka** [comment]
With 0dd01eef643b438551ac0e475ae51c7361d37fba 
```
--------------------------------------------------------------------------------
2015-09-23 16:31:50 +0900 running test for /home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/vte3
--------------------------------------------------------------------------------
Loaded suite .
Started
E
===============================================================================
Error: test_fd(TestPty): NoMethodError: undefined method `close' for #<Vte::Pty:0x5651b4593b50 ptr=0x5651b45957a0>
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/vte3/test/test-pty.rb:24:in `teardown'
===============================================================================
E
===============================================================================
Error: test_size(TestPty): NoMethodError: undefined method `close' for #<Vte::Pty:0x5651b45a1570 ptr=0x5651b45a8300>
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/vte3/test/test-pty.rb:24:in `teardown'
===============================================================================
E
===============================================================================
Error: test_utf8(TestPty): NoMethodError: undefined method `close' for #<Vte::Pty:0x5651b45b4df0 ptr=0x5651b45bd520>
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/vte3/test/test-pty.rb:24:in `teardown'
===============================================================================
.....................

Finished in 1.598612756 seconds.
------
24 tests, 24 assertions, 0 failures, 3 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
------
```

**Comment by kou** [comment]
Oh...
I just removed them. Because the method will be deprecated since VTE 0.42.

**Comment by mtasaka** [comment]
```
Finished in 1.458231552 seconds.
------
24 tests, 24 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
------
```

Thank you!

**Comment by kou** [comment]
Thanks for confirming it!
