### ISSUE TITLE
gio2 3.0.7: test does not pass on F-24

### ISSUE THREAD

**Issue by mtasaka** [ruby-gnome2/ruby-gnome2#591]
On Fedora 24, gio2 3.0.7 does not pass tests on x86_64 (not on i686)
```
+ ruby -rubygems -Ilib:test:ext/gio2 test/run-test.rb
glib-compile-resources ruby-gio2.gresource.xml
Loaded suite .
Started
../usr/share/gems/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb: line 551
   GLib-CRITICAL **:g_variant_get_type: assertion 'value != NULL' failed
/usr/share/gems/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb: line 551
   GLib-CRITICAL **:g_variant_type_is_subtype_of: assertion 'g_variant_type_check (type)' failed
/usr/share/gems/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb: line 551
   GLib-CRITICAL **:g_variant_dup_bytestring_array: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_BYTESTRING_ARRAY)' failed
E
===============================================================================
Error: test: #arguments(TestApplicationCommandLine): ArgumentError: negative array size (or size too big)
/usr/share/gems/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb:551:in `invoke'
/usr/share/gems/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb:551:in `block in define_method'
/builddir/build/BUILD/gio2-3.0.7/usr/share/gems/gems/gio2/lib/gio2/application-command-line.rb:21:in `arguments'
/builddir/build/BUILD/gio2-3.0.7/usr/share/gems/gems/gio2-3.0.7/test/test-application-command-line.rb:25:in `block in <class:TestApplicationCommandLine>'
===============================================================================
.......................................
Finished in 0.160570075 seconds.
------
42 tests, 43 assertions, 0 failures, 1 errors, 0 pendings, 0 omissions, 0 notifications
97.619% passed
------
```

On local Fedora 23 build currently I cannot reproduce this, however on F-24 it seems 100% reproducible.

**Comment by mtasaka** [comment]
By the way even on Fedora 23 I see the above 3  GLib-CRITICAL messages

**Comment by mtasaka** [comment]
Installed packages
https://kojipkgs.fedoraproject.org//work/tasks/9350/11409350/root.log

**Comment by mtasaka** [comment]
Ah, it seems even on F-23 something seems wrong

```
$ irb
reqirb(main):001:0> require "gio2"
=> true
irb(main):002:0> command_line = Gio::ApplicationCommandLine.new
=> #<Gio::ApplicationCommandLine:0x55a57ec85ea0 ptr=0x55a57e8afd00>
irb(main):003:0> command_line.arguments
/usr/share/gems/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb: line 551
   GLib-CRITICAL **:g_variant_get_type: assertion 'value != NULL' failed
/usr/share/gems/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb: line 551
   GLib-CRITICAL **:g_variant_type_is_subtype_of: assertion 'g_variant_type_check (type)' failed
/usr/share/gems/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb: line 551
   GLib-CRITICAL **:g_variant_dup_bytestring_array: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_BYTESTRING_ARRAY)' failed
NoMemoryError: failed to allocate memory
        from /usr/share/gems/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb:551:in `invoke'
        from /usr/share/gems/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb:551:in `block in define_method'
        from /usr/share/gems/gems/gio2-3.0.7/lib/gio2/application-command-line.rb:21:in `arguments'
        from (irb):3
        from /bin/irb:11:in `<main>'
```

**Comment by mtasaka** [comment]
arch is F-23 x86_64

**Comment by kou** [comment]
Thanks for your report.
We should create `GApplicationCommandLine` with initial `arguments`. It means that the test is invalid.

I added `Gio::Application.new(:arguments => [...])` support and fixed the test.

**Comment by mtasaka** [comment]
confirmed fixed, thank you.

**Comment by kou** [comment]
Thanks for confirming it!
