### ISSUE TITLE
TODO: <Callback>(callback_symbol) callback is not supported yet.

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#623]
Example from an irb session : 

```
irb(main):001:0> require "gtk3"
=> true
irb(main):002:0> builder = Gtk::Builder.new
=> #<Gtk::Builder:0x292aa20 ptr=0x3327890>
irb(main):003:0> builder.add_callback_symbol("toto")
=> #<Enumerator: #<Gtk::Builder:0x292aa20 ptr=0x3327890>:add_callback_symbol("toto")>
irb(main):004:0> {}
=> {}
irb(main):005:0> builder.add_callback_symbol("toto") {}
NotImplementedError: TODO: <Callback>(callback_symbol) callback is not supported yet.
	from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb:551:in `invoke'
	from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb:551:in `block in define_method'
	from (irb):5
	from /usr/bin/irb:11:in `<main>'
```

Do you plan to implement this or is there an alternative?

**Comment by kou** [comment]
We don't support it.
Users should use `Gtk::Builder#connect_signals`.
