### ISSUE TITLE
gtk3 3.0.7: test failure on arm with ruby 2.3.0

### ISSUE THREAD

**Issue by mtasaka** [ruby-gnome2/ruby-gnome2#672]
On Fedora 24 we are now building all ruby arch-dependent packages against ruby 2.3.0 and now gtk3 3.0.7 test suite fails on armv7hl (but succeeds on x86_64, i686) like
```
.....................F
===============================================================================
Failure:
          count_objects(Gtk::TreeIter) <= n_iterators + 1
          |                            |  |           |
          |                            |  |           3
          |                            |  2
          |                            false
          4
test: iter(TestGtkListStore::GC)
/usr/share/gems/gems/power_assert-0.2.7/lib/power_assert.rb:36:in `start'
/builddir/build/BUILD/rubygem-gtk3-3.0.7/usr/share/gems/gems/gtk3-3.0.7/test/test-gtk-list-store.rb:191:in `block (2 levels) in <class:TestGtkListStore>'
     188:       while @store.remove(iter); end
     189:       assert_equal(0, @store.to_enum(:each).to_a.size)
     190:       GC.start
  => 191:       assert do
     192:         count_objects(Gtk::TreeIter) <= n_iterators + 1
     193:       end
     194:     end
===============================================================================
.............................................................................../usr/share/gems/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb: line 551
   Gtk-WARNING **:Style property "nonexistent" is not registered
...............................................................................
.......
Finished in 5.866505013 seconds.
------
337 tests, 392 assertions, 1 failures, 0 errors, 0 pendings, 3 omissions, 0 notifications
99.7006% passed
```

**Comment by kou** [comment]
Thanks for your report.
It'll be difficult to debug...

**Comment by mtasaka** [comment]
If some additional information is needed, please let me know it.

**Comment by kou** [comment]
Thanks. I'll look into this later.

**Comment by mtasaka** [comment]
3.0.8 still fails on arm, and I saw failure on x86_64 one time:

**Comment by kou** [comment]
Thanks for additional information.
I relaxed the condition at https://github.com/ruby-gnome2/ruby-gnome2/commit/4e2ed31b7469f11833b8f5f8fd60833b23a23287
Because it's OK that one or more iterator objects are GC-ed in the test.
