### ISSUE TITLE
TODO: free GIArgument(interface)[union] everything

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#700]
Here is the minimum code that reproduce the error:
```ruby
require "gtk3"

win = Gtk::Window.new(:toplevel)
win.set_size_request(200, 200)
win.signal_connect ("destroy") { Gtk.main_quit }
calendar = Gtk::Calendar.new

calendar.signal_connect "day-selected" do |widget|
  event = Gtk.current_event
end
win.add(calendar)
win.show_all

Gtk.main
````

Just clik on the calendar then there is this error:

```
/home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb:114:in `invoke': TODO: free GIArgument(interface)[union] everything
	 from /home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb:114:in `block in define_singleton_method'
	 from calendar.rb:9:in `block in <main>'
	 from /home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb:114:in `invoke'
	 from /home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb:114:in `block in define_singleton_method'
	 from calendar.rb:14:in `<main>'

```

I have found this reference in the file  *gobject-introspection/ext/gobject-introspection/rb-gi-argument.c* at the line 1921 but I don't really understand what it is about.

**Comment by kou** [comment]
Thanks for your report.
I've implemented it.
