### ISSUE TITLE
Some examples in the tutorials doesn't work anymore

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#703]
@kou ,

On my system I am not able to run some of the examples of the tutorial. It starts with the 7th example:

```
cd ruby-gnome/gtk3/sample/tutorial
ruby exampleapp7/exampleapp.rb exampleapp?/exampleapp.rb                                                                11:24:22
/home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb: line 551
   Gtk-DEBUG **:Connecting to session manager
exampleapp7/exampleapp.rb:86:in `method': #<Gtk::Builder:0x1f5d268 ptr=0x286fdd0> is not a symbol nor a string
	 from exampleapp7/exampleapp.rb:86:in `block in init'
	 from /home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb:551:in `invoke'
	 from /home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb:551:in `block in define_method'
	 from /home/cedlemo/.gem/ruby/2.3.0/gems/gtk3-3.0.7/lib/gtk3/widget.rb:125:in `initialize_post'
	 from exampleapp7/exampleapp.rb:114:in `initialize'
	 from exampleapp7/exampleapp.rb:114:in `initialize'
	 from exampleapp7/exampleapp.rb:187:in `new'
	 from exampleapp7/exampleapp.rb:187:in `block in initialize'
	 from /home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb:551:in `invoke'
	 from /home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb:551:in `block in define_method'
	 from exampleapp7/exampleapp.rb:200:in `<main>'
```

After a git bisect and multiple rebuilds here is the culprit:

```
git bisect bad                                                                                                                    
d06b02bef137b359fc4808f3d6ec221222a0f0dd is the first bad commit
commit d06b02bef137b359fc4808f3d6ec221222a0f0dd
Author: Kouhei Sutou <kou@clear-code.com>
Date:   Sat Jan 9 23:44:12 2016 +0900

    gtk3: use auto generated callback for BuilderConnectFunc

:040000 040000 90a936bf3427467c47d05a45615232423f9d017a 953e3cf471a785d1cd49c5afd904c0603df4653d M	gtk3
fatal: ref HEAD is not a symbolic ref

```

**Comment by kou** [comment]
Thanks for your report!
I've fixed it.
