### ISSUE TITLE
gobject-introspection fails to install on Ruby 2.2.2

### ISSUE THREAD

**Issue by janko-m** [ruby-gnome2/ruby-gnome2#711]
```
    /Users/janko/.rbenv/versions/2.2.2/bin/ruby -r ./siteconf20160211-36595-q5qq7c.rb extconf.rb
checking for --enable-debug-build option... no
checking for -Wall option to compiler... yes
checking for -Waggregate-return option to compiler... yes
checking for -Wcast-align option to compiler... yes
checking for -Wextra option to compiler... yes
checking for -Wformat=2 option to compiler... yes
checking for -Winit-self option to compiler... yes
checking for -Wlarger-than-65500 option to compiler... yes
checking for -Wmissing-declarations option to compiler... yes
checking for -Wmissing-format-attribute option to compiler... yes
checking for -Wmissing-include-dirs option to compiler... yes
checking for -Wmissing-noreturn option to compiler... yes
checking for -Wmissing-prototypes option to compiler... yes
checking for -Wnested-externs option to compiler... yes
checking for -Wold-style-definition option to compiler... yes
checking for -Wpacked option to compiler... yes
checking for -Wp,-D_FORTIFY_SOURCE=2 option to compiler... yes
checking for -Wpointer-arith option to compiler... yes
checking for -Wswitch-default option to compiler... yes
checking for -Wswitch-enum option to compiler... yes
checking for -Wundef option to compiler... yes
checking for -Wout-of-line-declaration option to compiler... yes
checking for -Wunsafe-loop-optimizations option to compiler... no
checking for -Wwrite-strings option to compiler... yes
checking for rb_define_alloc_func() in ruby.h... yes
checking for rb_block_proc() in ruby.h... yes
checking for new allocation framework... yes
checking for attribute assignment... no
checking for Windows... no
checking for gobject-introspection-1.0... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/Users/janko/.rbenv/versions/2.2.2/bin/$(RUBY_BASE_NAME)
        --enable-debug-build
        --disable-debug-build
        --with-pkg-config
        --without-pkg-config
        --with-override-variables
        --without-override-variables
/Users/janko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/pkg-config-1.1.7/lib/pkg-config.rb:265:in `parse_pc': .pc for libffi doesn't exist. (RuntimeError)
        from /Users/janko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/pkg-config-1.1.7/lib/pkg-config.rb:185:in `declaration'
        from /Users/janko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/pkg-config-1.1.7/lib/pkg-config.rb:199:in `collect_cflags'
        from /Users/janko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/pkg-config-1.1.7/lib/pkg-config.rb:138:in `cflags'
        from /Users/janko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/pkg-config-1.1.7/lib/pkg-config.rb:201:in `block in collect_cflags'
        from /Users/janko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/pkg-config-1.1.7/lib/pkg-config.rb:200:in `collect'
        from /Users/janko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/pkg-config-1.1.7/lib/pkg-config.rb:200:in `collect_cflags'
        from /Users/janko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/pkg-config-1.1.7/lib/pkg-config.rb:138:in `cflags'
        from /Users/janko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/pkg-config-1.1.7/lib/pkg-config.rb:395:in `cflags'
        from /Users/janko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/pkg-config-1.1.7/lib/pkg-config.rb:446:in `have_package'
        from /Users/janko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/glib2-3.0.7/lib/mkmf-gnome2.rb:618:in `required_pkg_config_package'
        from extconf.rb:59:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/janko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/gobject-introspection-3.0.7 for inspection.
Results logged to /Users/janko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-14/2.2.0-static/gobject-introspection-3.0.7/gem_make.out
```

**Comment by kou** [comment]
Try `PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig gem install gobject-introspection`.
See also https://github.com/ruby-gnome2/ruby-gnome2/issues/259#issuecomment-59751807

**Comment by cosmo0920** [comment]
Should we add `PKG_CONFIG_PATH` note for OSX in https://github.com/ruby-gnome2/ruby-gnome2#environment-variables?

**Comment by janko-m** [comment]
Sorry for forgetting to search the closed issues. Worked, thanks!
