### ISSUE TITLE
Gdk::Cursor.new fails

### ISSUE THREAD

**Issue by dark-yux** [ruby-gnome2/ruby-gnome2#720]
The following fails:
`$loading = Gdk::Cursor.new(Gdk::Display.default, "wait")`
`$loading = Gdk::Cursor.new($display, "wait")`
And when I read the source code and figured out you [handled](https://github.com/ruby-gnome2/ruby-gnome2/blob/master/gdk3/lib/gdk3/cursor.rb#L20) the $display ...
`$loading = Gdk::Cursor.new("wait")`  still fails.
So, I can't use GdkCursor.

**Comment by cedlemo** [comment]
hi @dark-yux ,

it works for me:

```
require "gtk3"

window = Gtk::Window.new("Gdk::Cursor sample")
window.signal_connect('destroy') {Gtk.main_quit}
window.realize


cursor = Gdk::Cursor.new("wait")
window.window.set_cursor(cursor)

window.set_default_size(400,100)
window.show_all

Gtk.main
```

**Comment by dark-yux** [comment]
Is your example from gtk3/gdk3 3.0.7?

```
➜  ~ irb                                               
irb(main):001:0> require 'gdk3'
=> true
irb(main):002:0> cursor = Gdk::Cursor.new("wait")
TypeError: not a Gdk::CursorType: "wait"
	from /var/lib/gems/2.2.0/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb:307:in `invoke'
	from /var/lib/gems/2.2.0/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb:307:in `block (2 levels) in load_constructor_infos'
	from /var/lib/gems/2.2.0/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb:323:in `block in load_constructor_infos'
	from /var/lib/gems/2.2.0/gems/gdk3-3.0.7/lib/gdk3/cursor.rb:28:in `initialize'
	from (irb):2:in `new'
	from (irb):2
	from /usr/bin/irb:11:in `<main>'
```

**Comment by cedlemo** [comment]
Have you tried the script?

In order to make it work, you should load the gtk3 module (which load the gdk module) instead of only the Gdk3 module. I guess that the gtk3 module initialize some stuff when it is loaded.

**Comment by dark-yux** [comment]
Yes the script you provided has the same error.

```
➜  ~ ruby test.rb
/var/lib/gems/2.2.0/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb:307:in `invoke': failed to initialize (RuntimeError)
	from /var/lib/gems/2.2.0/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb:307:in `block (2 levels) in load_constructor_infos'
	from /var/lib/gems/2.2.0/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb:323:in `block in load_constructor_infos'
	from /var/lib/gems/2.2.0/gems/gdk3-3.0.7/lib/gdk3/cursor.rb:28:in `initialize'
	from test.rb:8:in `new'
	from test.rb:8:in `<main>
```

**Comment by cedlemo** [comment]
FYI I use the git version of the gtk3 gdk3 module.

**Comment by kou** [comment]
The script works well with gtk3 3.0.7 gem on my environment. Debian GNU/Linux sid x64, ruby 2.2.4p230 (2015-12-16) [x86_64-linux-gnu] and GTK+ is 3.18.8:

```text
% ruby -v -r gtk3 -e 'p Gtk::Version::STRING'
ruby 2.2.4p230 (2015-12-16) [x86_64-linux-gnu]
"3.18.8"
```

**Comment by dark-yux** [comment]
Im on `4.2.0-27-generic #32-Ubuntu SMP Fri Jan 22 04:49:08 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
```
➜  ~ ruby -v -r gtk3 -e 'p Gtk::Version::STRING'
ruby 2.2.3p173 (2015-08-18) [x86_64-linux-gnu]
"3.16.7"
```

**Comment by kou** [comment]
What is your GDK backend?

```text
% ruby -v -r gtk3 -e 'p Gdk::Display.default.gtype.name'
ruby 2.2.4p230 (2015-12-16) [x86_64-linux-gnu]
"GdkX11Display"
```

Available cursor names are depends on GDK backend.

**Comment by dark-yux** [comment]
```
➜  ~ ruby -v -r gtk3 -e 'p Gdk::Display.default.gtype.name'
ruby 2.2.3p173 (2015-08-18) [x86_64-linux-gnu]
"GdkX11Display"
```

**Comment by kou** [comment]
I think that this is a problem caused by your environment.

`wait` cursor exists at `/usr/share/icons/Adwaita/cursors/wait` on my environment:

```text
% strace ruby2.2 -r gtk3 -e 'Gdk::Cursor.new("wait")' |& grep wait
execve("/usr/bin/ruby2.2", ["ruby2.2", "-r", "gtk3", "-e", "Gdk::Cursor.new(\"wait\")"], [/* 61 vars */]) = 0
access("/usr/share/themes/Adwaita/gtk-3.0/settings.ini", F_OK) = -1 ENOENT (No such file or directory)
open("/home/kou/.icons/Adwaita/cursors/wait", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/home/kou/.icons/Adwaita/index.theme", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/icons/Adwaita/cursors/wait", O_RDONLY) = 14
```

`wait-nonexistent` doesn't exist:

```text
% strace ruby2.2 -r gtk3 -e 'Gdk::Cursor.new("wait-nonexistent")' |& grep wait
execve("/usr/bin/ruby2.2", ["ruby2.2", "-r", "gtk3", "-e", "Gdk::Cursor.new(\"wait-nonexisten"...], [/* 61 **vars** */]) = 0
access("/usr/share/themes/Adwaita/gtk-3.0/settings.ini", F_OK) = -1 ENOENT (No such file or directory)
open("/home/kou/.icons/Adwaita/cursors/wait-nonexistent", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/home/kou/.icons/Adwaita/index.theme", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/icons/Adwaita/cursors/wait-nonexistent", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/icons/Adwaita/index.theme", O_RDONLY) = 14
read(14, "[Icon Theme]\nName=Adwaita\nName[a"..., 4096) = 4096
open("/usr/share/pixmaps/Adwaita/cursors/wait-nonexistent", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/pixmaps/Adwaita/index.theme", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/home/kou/.icons/default/cursors/wait-nonexistent", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/icons/default/cursors/wait-nonexistent", O_RDONLY) = -1 ENOENT (No such file or directory)
read(14, "[Icon Theme]\nInherits=Adwaita\n", 4096) = 30
open("/usr/share/pixmaps/default/cursors/wait-nonexistent", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/home/kou/.icons/Adwaita/cursors/wait-nonexistent", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/home/kou/.icons/Adwaita/index.theme", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/icons/Adwaita/cursors/wait-nonexistent", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/icons/Adwaita/index.theme", O_RDONLY) = 14
read(14, "[Icon Theme]\nName=Adwaita\nName[a"..., 4096) = 4096
open("/usr/share/pixmaps/Adwaita/cursors/wait-nonexistent", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/pixmaps/Adwaita/index.theme", O_RDONLY) = -1 ENOENT (No such file or directory)
```

See also: http://www.x.org/releases/current/doc/man/man3/Xcursor.3.xhtml
GdkX11Display uses the above API.

**Comment by dark-yux** [comment]
Your right
```
➜  ~ locate /usr/share/icons/Adwaita/cursors/wait
```
fails.
