### ISSUE TITLE
Demo that crash

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#743]
I am updating the textscroll demo. It display two scrolled window with text that is added via 2 `GLib::Timeout.add`. The demo crash after 5~10 sec. Here is the code:

```ruby
# Copyright (c) 2016 Ruby-GNOME2 Project Team
# This program is licenced under the same licence as Ruby-GNOME2.
#
=begin
=  Text View/Automatic Scrolling

 This example demonstrates how to use the gravity of
 GtkTextMarks to keep a text view scrolled to the bottom
 while appending text.
=end
module TextscrollDemo
  def self.run_demo(main_window)
    window = Gtk::Window.new(:toplevel)
    window.screen = main_window.screen

    window.set_default_size(600, 400)

    hbox = Gtk::Box.new(:horizontal, 6)
    hbox.homogeneous = true
    window.add(hbox)

    create_text_view(hbox, true)
    create_text_view(hbox, false)

    if !window.visible?
      window.show_all
    else
      window.destroy
    end
    window
  end

  def self.create_text_view(hbox, to_end)
    swindow = Gtk::ScrolledWindow.new
    hbox.pack_start(swindow, :fill => true, :expand => true, :padding => 0)
    textview = Gtk::TextView.new
    swindow.add(textview)
    timeout = setup_scroll(textview, to_end)
    textview.signal_connect("destroy") { GLib::Source.remove(timeout)}
  end

  def self.setup_scroll(textview, to_end)
    buffer = textview.buffer
    end_iter = buffer.end_iter
    count = 0
    if to_end
      # If we want to scroll to the end, including horizontal scrolling,
      # then we just create a mark with right gravity at the end of the
      # buffer. It will stay at the end unless explicitly moved with
      # gtk_text_buffer_move_mark.
      buffer.create_mark("end", end_iter, false)

      # add scrolling timeout
      return GLib::Timeout.add(50) do # scroll to end
        count += 1
        # Get "end" mark. It's located at the end of buffer because
        # of right gravity
        mark = buffer.get_mark("end")
        mark_iter = buffer.get_iter_at(:mark => mark)
        # and insert some text at its position, the iter will be
        # revalidated after insertion to point to the end of inserted text
        buffer.insert(mark_iter, "\n")
        buffer.insert(mark_iter, " " * count)
        buffer.insert(mark_iter, "Scroll to end scroll to end scroll" +
                                   " to end scroll to end #{count}")
        # Now scroll the end mark onscreen.
        textview.scroll_mark_onscreen(mark)

        # Emulate typewriter behavior, shift to the left if we
        # are far enough to the right.
        count = 0 if count > 150
        GLib::Source::CONTINUE
      end
    else
      # If we want to scroll to the bottom, but not scroll horizontally,
      # then an end mark won't do the job. Just create a mark so we can
      # use it with gtk_text_view_scroll_mark_onscreen, we'll position it
      # explicitly when needed. Use left gravity so the mark stays where
      # we put it after inserting new text.
      buffer.create_mark("scroll", end_iter, true)
      return GLib::Timeout.add(100) do # scroll to bottom
        count += 1
        # Get end iterator
        end_iter = buffer.end_iter
        # and insert some text at it, the iter will be revalidated
        # after insertion to point to the end of inserted text
        buffer.insert(end_iter, "\n")
        buffer.insert(end_iter, " " * count)
        buffer.insert(end_iter,"Scroll to bottom scroll to bottom scroll" +
                                  " to bottom scroll to bottom #{count}")
        # Move the iterator to the beginning of line, so we don't scroll
        # in horizontal direction
        end_iter.line_offset = 0
        # and place the mark at iter. the mark will stay there after we
        # insert some text at the end because it has left gravity.
        mark = buffer.get_mark("scroll")
        buffer.move_mark(mark, end_iter)
        # Scroll the mark onscreen.
        textview.scroll_mark_onscreen(mark)
        # Shift text back if we got enough to the right.
        count = 0 if count > 40
        GLib::Source::CONTINUE
      end
    end
  end
end
```

I use this command in order to remove all `did_you_mean` messages

    ruby --disable=did_you_mean main.rb -r textscroll

Here is the output after the crash:

```
/home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.0.8/lib/gobject-introspection/loader.rb: line 551
   Gtk-DEBUG **:Connecting to session manager
/home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.0.8/lib/gobject-introspection/loader.rb:551:in `invoke'main.rb: [BUG] Segmentation fault at 0x000000000e5bbc
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0004 p:---- s:0008 e:000007 CFUNC  :to_str
c:0003 p:---- s:0006 e:000005 CFUNC  :to_s
c:0002 p:---- s:0004 e:000003 CFUNC  :message
c:0001 p:0000 s:0002 E:001070 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
main.rb:0:in `message'
main.rb:0:in `to_s'
main.rb:0:in `to_str'

-- Machine register context ------------------------------------------------
 RIP: 0x00007f8e09f7d055 RBP: 0x0000000000000ab1 RSP: 0x00007ffc37482528
 RAX: 0x00000000000e5bbc RBX: 0x0000000001c12720 RCX: 0x00000000000000ab
 RDX: 0x00007ffc37482538 RDI: 0x00000000000e510c RSI: 0x0000000000000ab1
  R8: 0x0000000002bc2eef  R9: 0x0000000002bc2ef0 R10: 0x00000000000000ab
 R11: 0x00007f8e09c01020 R12: 0x00007ffc37482538 R13: 0x0000000001c12c48
 R14: 0x0000000000382f38 R15: 0x00007ffc37482588 EFL: 0x0000000000010202

-- C level backtrace information -------------------------------------------
/usr/lib/libruby.so.2.3 [0x7f8e09fca4b5]
/usr/lib/libruby.so.2.3 [0x7f8e09fca6ec]
/usr/lib/libruby.so.2.3 [0x7f8e09ea50e4]
/usr/lib/libruby.so.2.3 [0x7f8e09f56d8e]
/usr/lib/libc.so.6 [0x7f8e09ac8330]
/usr/lib/libruby.so.2.3 [0x7f8e09f7d055]
/usr/lib/libruby.so.2.3 [0x7f8e09fb165c]
/usr/lib/libruby.so.2.3 [0x7f8e09fb4832]
/usr/lib/libruby.so.2.3 [0x7f8e09fc375d]
/usr/lib/libruby.so.2.3(rb_inspect+0x14) [0x7f8e09ef7384]
/usr/lib/libruby.so.2.3(rb_protect+0xfb) [0x7f8e09eaa94b]
/usr/lib/libruby.so.2.3 [0x7f8e09ea65b0]
/usr/lib/libruby.so.2.3 [0x7f8e09fc2cf4]
/usr/lib/libruby.so.2.3 [0x7f8e09fc3120]
/usr/lib/libruby.so.2.3 [0x7f8e09ef6e0c]
/usr/lib/libruby.so.2.3(rb_check_convert_type+0x59) [0x7f8e09ef7af9]
/usr/lib/libruby.so.2.3(rb_String+0x9) [0x7f8e09ef8889]
/usr/lib/libruby.so.2.3 [0x7f8e09fc2cf4]
/usr/lib/libruby.so.2.3 [0x7f8e09fc3815]
/usr/lib/libruby.so.2.3 [0x7f8e09fc2cf4]

```

It looks like the same issue than #716

**Comment by kou** [comment]
Thanks for your report.
I've fixed it.
