### ISSUE TITLE
Vte3 3.0.8: test fails with bad file descriptor

### ISSUE THREAD

**Issue by mtasaka** [ruby-gnome2/ruby-gnome2#745]
Vte3 3.0.8 fails on test:
```
===============================================================================================================================================================
Error: test_fd(TestPty): Gio::IOError::Failed: Failed to open PTY: Inappropriate ioctl for device
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:307:in `invoke'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:307:in `block (2 levels) in load_constructor_infos'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:323:in `block in load_constructor_infos'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/vte3/test/test-pty.rb:20:in `new'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/vte3/test/test-pty.rb:20:in `setup'
===============================================================================================================================================================
E
===============================================================================================================================================================
Error: test_size(TestPty): Gio::IOError::Failed: Failed to open PTY: Bad file descriptor
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:307:in `invoke'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:307:in `block (2 levels) in load_constructor_infos'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:323:in `block in load_constructor_infos'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/vte3/test/test-pty.rb:20:in `new'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/vte3/test/test-pty.rb:20:in `setup'
===============================================================================================================================================================
E
===============================================================================================================================================================
Error: test_utf8(TestPty): Gio::IOError::Failed: Failed to open PTY: Bad file descriptor
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:307:in `invoke'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:307:in `block (2 levels) in load_constructor_infos'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:323:in `block in load_constructor_infos'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/vte3/test/test-pty.rb:20:in `new'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/vte3/test/test-pty.rb:20:in `setup'
===============================================================================================================================================================
.....................

Finished in 1.40297465 seconds.
---------------------------------------------------------------------------------------------------------------------------------------------------------------
24 tests, 21 assertions, 0 failures, 3 errors, 0 pendings, 0 omissions, 0 notifications
87.5% passed
```

**Comment by kou** [comment]
Thanks for your report.
I've fixed it at master.
