### ISSUE TITLE
`GdkPixbuf::Pixbuf#formats` crash

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#839]
@kou,

When I try to list the formats that `GdkPixbuf::Pixbuf` supports in order to save a pixbuf, it crashes.

Minimum code:

```Ruby
require "gtk3"

puts GdkPixbuf::Pixbuf.formats
```

```
ruby gdk_pixbuf_saving_formats.rb 
/home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.0.9/lib/gobject-introspection/loader.rb:114: [BUG] Segmentation fault at 0x00000000000000
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0004 p:---- s:0013 e:000012 CFUNC  :invoke
c:0003 p:0065 s:0009 e:000008 LAMBDA /home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.0.9/lib/gobject-introspection/loader.rb:114 [FINISH]
c:0002 p:0024 s:0005 E:002390 EVAL   gdk_pixbuf_saving_formats.rb:3 [FINISH]
c:0001 p:0000 s:0002 E:000be0 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
gdk_pixbuf_saving_formats.rb:3:in `<main>'
/home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.0.9/lib/gobject-introspection/loader.rb:114:in `block in define_singleton_method'
/home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.0.9/lib/gobject-introspection/loader.rb:114:in `invoke'

-- Machine register context ------------------------------------------------
 RIP: 0x00007f5275557702 RBP: 0x0000000002bf0b20 RSP: 0x00007ffc6ed84b28
 RAX: 0x0000000000000000 RBX: 0x61647869506b6447 RCX: 0x00000000026457b0
 RDX: 0x0000000000000000 RDI: 0x61647869506b6444 RSI: 0x61647869506b6447
  R8: 0x000000000000000c  R9: 0x0000000001eb99e0 R10: 0x00000000000003af
 R11: 0x00007f527579d6b0 R12: 0x00007ffc6ed84b30 R13: 0x61647869506b6447
 R14: 0x0000000000000001 R15: 0x00007ffc6ed84e10 EFL: 0x0000000000010206

-- C level backtrace information -------------------------------------------
/usr/lib/libruby.so.2.3 [0x7f527770b935]
/usr/lib/libruby.so.2.3 [0x7f527770bb6c]
/usr/lib/libruby.so.2.3 [0x7f52775e6114]
/usr/lib/libruby.so.2.3 [0x7f5277697e9e]
/usr/lib/libc.so.6 [0x7f5277209310]
/usr/lib/libgobject-2.0.so.0(g_type_parent+0x12) [0x7f5275557702]
/home/cedlemo/.gem/ruby/2.3.0/gems/glib2-3.0.9/lib/glib2.so(rbgobj_ruby_object_from_instance2+0x58) [0x7f52757935b8]
/home/cedlemo/.gem/ruby/2.3.0/gems/glib2-3.0.9/lib/glib2.so [0x7f527579d3c6]
/usr/lib/libruby.so.2.3(rb_ensure+0xb0) [0x7f52775ebaf0]
/home/cedlemo/.gem/ruby/2.3.0/gems/glib2-3.0.9/lib/glib2.so(rbg_gslist2rval+0x40) [0x7f527579d6f0]
/home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.0.9/lib/gobject_introspection.so(rb_gi_argument_to_ruby+0x51e) [0x7f5274b8e0ee]
/home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.0.9/lib/gobject_introspection.so(rb_gi_return_argument_to_ruby+0x67) [0x7f5274b8f347]
/home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.0.9/lib/gobject_introspection.so(rb_gi_function_info_invoke_raw+0x88d) [0x7f5274b899ed]
/home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.0.9/lib/gobject_introspection.so [0x7f5274b89cd5]
```

*edit*

see here https://developer.gnome.org/gdk-pixbuf/2.33/gdk-pixbuf-File-saving.html#gdk-pixbuf-save

**Comment by kou** [comment]
Sorry for my no response.
Thanks for fixing it!
