### ISSUE TITLE
libgdk-3-0.dll load problem on Ruby 2.3.1 x64 and rcairo 1.14.x

### ISSUE THREAD

**Issue by Mazwak** [ruby-gnome2/ruby-gnome2#849]
Following my problem with rcairo, I now can't use gtk3 3.0.8 with 1.14.6

Windows 7 64b
Ruby 2.3.1 x64 (from ruby installer)
Ruby 2.2.5 x64 (from ruby installer)
rcairo 1.14.6

```ruby
gem 'cairo', '~> 1.14.0'

require 'gtk3'

Gtk.main
```

outputs

```
C:/ruby/231/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x64-mingw32/lib/gobject-introspection/loader.rb: line 233
   (NULL)-WARNING **:Failed to load shared library 'libgdk-3-0.dll' referenced by the typelib: 'libgdk-3-0.dll': La procédure spécif
iée est introuvable.
C:/ruby/231/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x64-mingw32/lib/gobject-introspection/loader.rb:167:in `const_set':
 wrong constant name 2BUTTON_PRESS (NameError)
        from C:/ruby/231/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x64-mingw32/lib/gobject-introspection/loader.rb:167:in
 `load_enum_value'
        from C:/ruby/231/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x64-mingw32/lib/gobject-introspection/loader.rb:200:in
 `block in load_enum_info'
        from C:/ruby/231/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x64-mingw32/lib/gobject-introspection/loader.rb:199:in
 `each'
        from C:/ruby/231/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x64-mingw32/lib/gobject-introspection/loader.rb:199:in
 `load_enum_info'
        from C:/ruby/231/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x64-mingw32/lib/gobject-introspection/loader.rb:63:in
`load_info'
        from C:/ruby/231/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x64-mingw32/lib/gobject-introspection/loader.rb:40:in
`block in load'
        from C:/ruby/231/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x64-mingw32/lib/gobject-introspection/repository.rb:27
:in `block (2 levels) in each'
        from C:/ruby/231/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x64-mingw32/lib/gobject-introspection/repository.rb:26
:in `times'
        from C:/ruby/231/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x64-mingw32/lib/gobject-introspection/repository.rb:26
:in `block in each'
        from C:/ruby/231/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x64-mingw32/lib/gobject-introspection/repository.rb:25
:in `each'
        from C:/ruby/231/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x64-mingw32/lib/gobject-introspection/repository.rb:25
:in `each'
        from C:/ruby/231/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x64-mingw32/lib/gobject-introspection/loader.rb:39:in
`load'
        from C:/ruby/231/lib/ruby/gems/2.3.0/gems/gdk3-3.0.8-x64-mingw32/lib/gdk3.rb:55:in `init'
        from C:/ruby/231/lib/ruby/gems/2.3.0/gems/gtk3-3.0.8-x64-mingw32/lib/gtk3.rb:64:in `init'
        from C:/ruby/231/lib/ruby/gems/2.3.0/gems/gtk3-3.0.8-x64-mingw32/lib/gtk3.rb:49:in `method_missing'
        from -e:1:in `<main>'
```

If I use rcairo 1.15.2, I have the issue reported on rcairo.

On Fedora 24 64b, everything just works.

**Comment by kou** [comment]
Because GTK+ 3.20 requires cairo 1.15.x or later: https://git.gnome.org/browse/gtk+/tree/configure.ac?h=gtk-3-20#n590

gdk3 3.0.8 gem bundles GTK+ 3.20.
