### ISSUE TITLE
NameError: uninitialized constant GdkPixbuf::Version::MAJOR

### ISSUE THREAD

**Issue by x001B** [ruby-gnome2/ruby-gnome2#852]
Greetings. I've been using 3.0.9 for the past month or so without problem (installing the gems from this repo), but recent changes to the Pixbuf gem are now causing errors (just updated the gems today). 

I get the error by simply requiring gtk3; I'm not sure what other info would be useful for you guys to help solve the issue.

Many thanks for all the work put into these bindings!

**Comment by kou** [comment]
Please show your code and backtrace of the case.

**Comment by x001B** [comment]
Sure. And to be clear, I didn't have errors installing any of the up-to-date gems, just when I try to use them. 
```
irb(main):001:0> require 'gtk3'
/home/borat/.gem/ruby/2.3.0/gems/glib2-3.0.9/lib/glib2.rb:184: warning: already initialized constant GLib::Log::DOMAIN
/usr/lib/ruby/site_ruby/2.3.0/glib2.rb:184: warning: previous definition of DOMAIN was here
/home/borat/.gem/ruby/2.3.0/gems/glib2-3.0.9/lib/glib2.rb:185: warning: already initialized constant GLib::Log::LEVELS
/usr/lib/ruby/site_ruby/2.3.0/glib2.rb:185: warning: previous definition of LEVELS was here
/home/borat/.gem/ruby/2.3.0/gems/glib2-3.0.9/lib/glib2.rb:223: warning: already initialized constant GLib::UserDirectory::DESKTOP
/usr/lib/ruby/site_ruby/2.3.0/glib2.rb:223: warning: previous definition of DESKTOP was here
/home/borat/.gem/ruby/2.3.0/gems/glib2-3.0.9/lib/glib2.rb:223: warning: already initialized constant GLib::UserDirectory::DOCUMENTS
/usr/lib/ruby/site_ruby/2.3.0/glib2.rb:223: warning: previous definition of DOCUMENTS was here
/home/borat/.gem/ruby/2.3.0/gems/glib2-3.0.9/lib/glib2.rb:223: warning: already initialized constant GLib::UserDirectory::DOWNLOAD
/usr/lib/ruby/site_ruby/2.3.0/glib2.rb:223: warning: previous definition of DOWNLOAD was here
/home/borat/.gem/ruby/2.3.0/gems/glib2-3.0.9/lib/glib2.rb:223: warning: already initialized constant GLib::UserDirectory::MUSIC
/usr/lib/ruby/site_ruby/2.3.0/glib2.rb:223: warning: previous definition of MUSIC was here
/home/borat/.gem/ruby/2.3.0/gems/glib2-3.0.9/lib/glib2.rb:223: warning: already initialized constant GLib::UserDirectory::PICTURES
/usr/lib/ruby/site_ruby/2.3.0/glib2.rb:223: warning: previous definition of PICTURES was here
/home/borat/.gem/ruby/2.3.0/gems/glib2-3.0.9/lib/glib2.rb:223: warning: already initialized constant GLib::UserDirectory::PUBLIC_SHARE
/usr/lib/ruby/site_ruby/2.3.0/glib2.rb:223: warning: previous definition of PUBLIC_SHARE was here
/home/borat/.gem/ruby/2.3.0/gems/glib2-3.0.9/lib/glib2.rb:223: warning: already initialized constant GLib::UserDirectory::TEMPLATES
/usr/lib/ruby/site_ruby/2.3.0/glib2.rb:223: warning: previous definition of TEMPLATES was here
/home/borat/.gem/ruby/2.3.0/gems/glib2-3.0.9/lib/glib2.rb:223: warning: already initialized constant GLib::UserDirectory::VIDEOS
/usr/lib/ruby/site_ruby/2.3.0/glib2.rb:223: warning: previous definition of VIDEOS was here
/home/borat/.gem/ruby/2.3.0/gems/glib2-3.0.9/lib/glib2.rb:229: warning: already initialized constant GLib::LOG_DOMAIN
/usr/lib/ruby/site_ruby/2.3.0/glib2.rb:229: warning: previous definition of LOG_DOMAIN was here
/home/borat/.gem/ruby/2.3.0/gems/glib2-3.0.9/lib/glib2.rb:232: warning: already initialized constant GLib::Object::LOG_DOMAIN
/usr/lib/ruby/site_ruby/2.3.0/glib2.rb:232: warning: previous definition of LOG_DOMAIN was here
/home/borat/.gem/ruby/2.3.0/gems/glib2-3.0.9/lib/glib2.rb:236: warning: already initialized constant GLib::Thread::LOG_DOMAIN
/usr/lib/ruby/site_ruby/2.3.0/glib2.rb:236: warning: previous definition of LOG_DOMAIN was here
/home/borat/.gem/ruby/2.3.0/gems/glib2-3.0.9/lib/glib2.rb:240: warning: already initialized constant GLib::Module::LOG_DOMAIN
/usr/lib/ruby/site_ruby/2.3.0/glib2.rb:240: warning: previous definition of LOG_DOMAIN was here
NameError: uninitialized constant GdkPixbuf::Version::MAJOR
	from /home/borat/.gem/ruby/2.3.0/gems/gdk_pixbuf2-3.0.9/lib/gdk_pixbuf2/version.rb:19:in `<module:Version>'
	from /home/borat/.gem/ruby/2.3.0/gems/gdk_pixbuf2-3.0.9/lib/gdk_pixbuf2/version.rb:18:in `<module:GdkPixbuf>'
	from /home/borat/.gem/ruby/2.3.0/gems/gdk_pixbuf2-3.0.9/lib/gdk_pixbuf2/version.rb:17:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/borat/.gem/ruby/2.3.0/gems/gdk_pixbuf2-3.0.9/lib/gdk_pixbuf2/loader.rb:35:in `require_libraries'
	from /home/borat/.gem/ruby/2.3.0/gems/gdk_pixbuf2-3.0.9/lib/gdk_pixbuf2/loader.rb:26:in `post_load'
	from /usr/lib/ruby/site_ruby/2.3.0/gobject-introspection/loader.rb:42:in `load'
	from /home/borat/.gem/ruby/2.3.0/gems/gdk_pixbuf2-3.0.9/lib/gdk_pixbuf2.rb:34:in `<module:GdkPixbuf>'
	from /home/borat/.gem/ruby/2.3.0/gems/gdk_pixbuf2-3.0.9/lib/gdk_pixbuf2.rb:29:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/borat/.gem/ruby/2.3.0/gems/gdk3-3.0.9/lib/gdk3.rb:21:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /usr/lib/ruby/site_ruby/2.3.0/gtk3.rb:19:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from (irb):1
	from /usr/bin/irb:11:in `<main>'
irb(main):002:0>
```

**Comment by x001B** [comment]
Just wanted to let you know that if I ```require 'gdk3' ``` before ```require 'gtk3' ``` then it is able to load fine. Let me know if there is anything else I can do/provide on my end to help assist the original issue.

**Comment by kou** [comment]
Remove glib2 gem related files from `/usr/lib/ruby/site_ruby/2.3.0/`. It conflicts glib2 gem installed as gem.

**Comment by x001B** [comment]
... I don't know how I missed such obvious issues. You were correct, of course.

Sorry for wasting your time and thanks again for all your efforts, kou.
