### ISSUE TITLE
Vte::Terminal#spawn_sync

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#895]
@kou,

Since your last commits I have this error : 

```
/home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.1.0/lib/gobject-introspection/loader.rb: line 520
   Gtk-DEBUG **:Connecting to session manager
/home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.1.0/lib/gobject-introspection/loader.rb:641:in `validate_arguments': Vte::Terminal#spawn_sync: wrong number of arguments (7 for 3..6)
	 from /home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.1.0/lib/gobject-introspection/loader.rb:590:in `build'
	 from /home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.1.0/lib/gobject-introspection/loader.rb:511:in `block in define_method'
	 from /home/cedlemo/.gem/ruby/2.3.0/gems/vte3-3.1.0/lib/vte3/terminal.rb:55:in `spawn'
	 from /home/cedlemo/.gem/ruby/2.3.0/gems/topinambour-1.0.10/lib/terminal.rb:29:in `initialize'
	 from /home/cedlemo/.gem/ruby/2.3.0/gems/topinambour-1.0.10/lib/window.rb:41:in `new'
	 from /home/cedlemo/.gem/ruby/2.3.0/gems/topinambour-1.0.10/lib/window.rb:41:in `add_terminal'
	 from /home/cedlemo/.gem/ruby/2.3.0/gems/topinambour-1.0.10/lib/application.rb:35:in `block in initialize'
	 from /home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.1.0/lib/gobject-introspection/loader.rb:520:in `invoke'
	 from /home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.1.0/lib/gobject-introspection/loader.rb:520:in `block in define_method'
	 from /home/cedlemo/.gem/ruby/2.3.0/gems/topinambour-1.0.10/bin/topinambour:59:in `<top (required)>'
	 from /home/cedlemo/.gem/ruby/2.3.0/bin/topinambour:23:in `load'
	 from /home/cedlemo/.gem/ruby/2.3.0/bin/topinambour:23:in `<main>'
```

Here is the code that generates the error (it worked before I merge your last commits):

https://github.com/cedlemo/topinambour/blob/master/lib/terminal.rb#L25

**edit ** 

It works if I revert to this (sorry for the ugly diff): 

```
623,630c623,626
<           unless nil_indexes.empty?
<              nil_indexes[-n_missing_arguments..-1].each do |i|
<                @arguments.insert(i, nil)
<              end
<           # return if nil_indexes.size < n_missing_arguments
<           # nil_indexes.each_with_index do |nil_index, i|
<             # next if i < n_missing_arguments
<             # @arguments.insert(nil_index, nil)
---
>           return if nil_indexes.size < n_missing_arguments
>           nil_indexes.each_with_index do |nil_index, i|
>             next if i < n_missing_arguments
>             @arguments.insert(nil_index, nil)
```

**Comment by kou** [comment]
Good catch!
I've fixed it.
