### ISSUE TITLE
bind template callback

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#931]
@kou,

I work on the listbox demo. (https://github.com/GNOME/gtk/blob/master/demos/gtk-demo/listbox.c)

Here is the code: 

```ruby
# Copyright (c) 2016 Ruby-GNOME2 Project Team
# This program is licenced under the same licence as Ruby-GNOME2.
#
=begin
=  List Box

 GtkListBox allows lists with complicated layouts, using
 regular widgets supporting sorting and filtering.

=end
class ListboxDemo
  def initialize(main_window)
    @window = Gtk::Window.new(:toplevel)
    @window.screen = main_window.screen
    @window.title = "List Box"
    @window.set_default_size(400, 600)
    @avatar_pixbuf_other = GdkPixbuf::Pixbuf.new(:resource => "/listbox/apple-red.png",
                                                :width => 32,
                                                :height => 32,
                                                :preserve_aspect_ratio => false)

    vbox = Gtk::Box.new(:vertical, 12)
    @window.add(vbox)
    label = Gtk::Label.new("Messages from Gtk+ and friends")
    vbox.pack_start(label, :expand => false, :fill => false, :padding => 0)
    scrolled = Gtk::ScrolledWindow.new
    scrolled.set_policy(:never, :automatic)
    vbox.pack_start(scrolled, :expand => true, :fill => true, :padding => 0)

    listbox = Gtk::ListBox.new
    scrolled.add(listbox)

    listbox.set_sort_func do |a, b|
      a.sort(b)
    end
    listbox.activate_on_single_click = false
    listbox.signal_connect "row-activated" do |widget|
      widget.row_activated
    end
    vbox.show_all

    data = Gio::Resources.lookup_data("/listbox/messages.txt", 0)
    data.each_line do |line|
      message = Message.new(line)
      row = GtkMessageRow.new(message)
      row.show
      listbox.add(row)
    end
  end

  def run
    if !@window.visible?
      @window.show_all
    else
      @window.destroy
    end
    @window
  end
end

class Message
  attr_reader :id, :sender_name, :sender_nick, :message, :time, :reply_to,
              :resent_by, :n_favorites, :n_reshares
  def initialize(str)
    strv = str.split("|")
    parse(strv)
  end

  private

  def parse(array_of_strings)
    @id = array_of_strings[0].to_i
    @sender_name = array_of_strings[1]
    @sender_nick = array_of_strings[2]
    @message = array_of_strings[3]
    @time = array_of_strings[4].to_i
    @reply_to = array_of_strings[5] || nil
    @resent_by = array_of_strings[6] || nil
    @n_favorites = array_of_strings[7] ? array_of_strings[7].to_i : nil
    @n_reshares = array_of_strings[8] ? array_of_strings[8].to_i : nil
  end
end

class GtkMessageRow < Gtk::ListBoxRow

  type_register
  class << self
    def init
      set_template(:resource => "/listbox/listbox.ui")
      bind_template_child("content_label")
      bind_template_child("source_name")
      bind_template_child("source_nick")
      bind_template_child("short_time_label")
      bind_template_child("detailed_time_label")
      bind_template_child("extra_buttons_box")
      bind_template_child("details_revealer")
      bind_template_child("avatar_image")
      bind_template_child("resent_box")
      bind_template_child("resent_by_button")
      bind_template_child("n_reshares_label")
      bind_template_child("n_favorites_label")
      bind_template_child("expand_button")

      set_connect_func do |name|
        method(name)
      end
    end
  end

  attr_reader :message

  def initialize(message)
    super()
    @message = message
    message_row_update
  end

  def message_row_update
    source_name.text = @message.sender_name
    source_nick.text = @message.sender_nick
    content_label.text = @message.message
    short_time_label.text = Time.at(@message.time).utc.strftime("%e %b %y")
    detailed_time_label.text = Time.at(@message.time).utc.strftime("%Y - %e %b %Y")
    n_favorites_label.visible = @message.n_favorites != 0
    n_favorites_label.markup = "<b>#{@message.n_favorites}</b>\nFavorites"
    n_reshares_label.visible = @message.n_reshares != 0
    n_reshares_label.markup = "<b>#{@message.n_reshares}</b>\nReshares"
    resent_box.visible = @message.resent_by != nil
    resent_by_button.label = @message.resent_by if @message.resent_by
    if @message.sender_nick == "@GTKtoolkit"
      avatar_image.set_from_icon_name("gtk3-demo", :dnd)
    else
      avatar_image.from_pixbuf = @avatar_pixbuf_other
    end
  end

  def sort(b)
    @message.time - b.message.time
  end

  private

  def expand_clicked
    row_expand
  end

  def reshare_clicked
    @message.n_reshares += 1
    message_row_update
  end

  def favorite_clicked
    @message.n_favorites += 1
    message_row_update
  end

  def state_flags_changed(widget, previous_flags)
    flags = widget.state_flags
    extra_button_box.visible = flags & (Gtk::StateFlag::PRELIGHT | Gtk::StateFlag::SELECTED)
    state_flags_changed(widget, previous_flags)
  end

  def row_expand
    expand = !details_revealer.reveal_child
    details_revealer.reveal_child = !expand
    expand ? expand_button.label = "Hide" : expand_button.label = "Expand"
  end
end
```

You see here : 

```ruby
class GtkMessageRow < Gtk::ListBoxRow

  type_register
  class << self
    def init
      set_template(:resource => "/listbox/listbox.ui")
      bind_template_child("content_label")
      bind_template_child("source_name")
      bind_template_child("source_nick")
      bind_template_child("short_time_label")
      bind_template_child("detailed_time_label")
      bind_template_child("extra_buttons_box")
      bind_template_child("details_revealer")
      bind_template_child("avatar_image")
      bind_template_child("resent_box")
      bind_template_child("resent_by_button")
      bind_template_child("n_reshares_label")
      bind_template_child("n_favorites_label")
      bind_template_child("expand_button")

      set_connect_func do |name|
        method(name)
      end
    end
  end
```
the `set_connect_func` should call the private method whose name is written in the ui file. I have created those private methods but when I launch my demo, I have this message that says that the methods are missing:

```
./main.rb -r listbox
/home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.1.0/lib/gobject-introspection/loader.rb: line 520
   Gtk-DEBUG **:Connecting to session manager
NameError: undefined method `favorite_clicked' for class `#<Class:GtkMessageRow>'
/home/cedlemo/Projets/Ruby/ruby-gnome2/gtk3/sample/gtk-demo/listbox.rb:105:in `method'
/home/cedlemo/Projets/Ruby/ruby-gnome2/gtk3/sample/gtk-demo/listbox.rb:105:in `block in init'
/home/cedlemo/.gem/ruby/2.3.0/gems/gtk3-3.1.0/lib/gtk3/builder.rb:31:in `connect_signal'
/home/cedlemo/.gem/ruby/2.3.0/gems/gtk3-3.1.0/lib/gtk3/widget.rb:56:in `block in set_connect_func'
/home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.1.0/lib/gobject-introspection/loader.rb:520:in `invoke'
/home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.1.0/lib/gobject-introspection/loader.rb:520:in `block in define_method'
/home/cedlemo/.gem/ruby/2.3.0/gems/gtk3-3.1.0/lib/gtk3/widget.rb:127:in `initialize_post'
/home/cedlemo/Projets/Ruby/ruby-gnome2/gtk3/sample/gtk-demo/listbox.rb:113:in `initialize'
/home/cedlemo/Projets/Ruby/ruby-gnome2/gtk3/sample/gtk-demo/listbox.rb:113:in `initialize'
/home/cedlemo/Projets/Ruby/ruby-gnome2/gtk3/sample/gtk-demo/listbox.rb:45:in `new'
/home/cedlemo/Projets/Ruby/ruby-gnome2/gtk3/sample/gtk-demo/listbox.rb:45:in `block in initialize'
/home/cedlemo/Projets/Ruby/ruby-gnome2/gtk3/sample/gtk-demo/listbox.rb:43:in `each_line'
/home/cedlemo/Projets/Ruby/ruby-gnome2/gtk3/sample/gtk-demo/listbox.rb:43:in `initialize'
./main.rb:181:in `new'
./main.rb:181:in `run_demo_from_file'
./main.rb:378:in `run_application'
./main.rb:254:in `block in initialize'
/home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.1.0/lib/gobject-introspection/loader.rb:520:in `invoke'
/home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.1.0/lib/gobject-introspection/loader.rb:520:in `block in define_method'
./main.rb:273:in `block in initialize'
/home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.1.0/lib/gobject-introspection/loader.rb:520:in `invoke'
/home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.1.0/lib/gobject-introspection/loader.rb:520:in `block in define_method'
./main.rb:498:in `<main>'
```

Any hints ?

**Comment by cedlemo** [comment]
My bad, the method should be implemented as class method instead of instance methods sorry : 

```ruby
class GtkMessageRow < Gtk::ListBoxRow

  type_register
  class << self
    def init
      set_template(:resource => "/listbox/listbox.ui")
      bind_template_child("content_label")
      bind_template_child("source_name")
      bind_template_child("source_nick")
      bind_template_child("short_time_label")
      bind_template_child("detailed_time_label")
      bind_template_child("extra_buttons_box")
      bind_template_child("details_revealer")
      bind_template_child("avatar_image")
      bind_template_child("resent_box")
      bind_template_child("resent_by_button")
      bind_template_child("n_reshares_label")
      bind_template_child("n_favorites_label")
      bind_template_child("expand_button")

      set_connect_func do |name|
        method(name)
      end
    end
   
   private

    def expand_clicked
      row_expand
    end

    def reshare_clicked
      @message.n_reshares += 1
      message_row_update
    end

    def favorite_clicked
      @message.n_favorites += 1
      message_row_update
    end
  end

  attr_reader :message

  def initialize(message)
    super()
    @message = message
    message_row_update
  end

  def message_row_update
    source_name.text = @message.sender_name
    source_nick.text = @message.sender_nick
    content_label.text = @message.message
    short_time_label.text = Time.at(@message.time).utc.strftime("%e %b %y")
    detailed_time_label.text = Time.at(@message.time).utc.strftime("%Y - %e %b %Y")
    n_favorites_label.visible = @message.n_favorites != 0
    n_favorites_label.markup = "<b>#{@message.n_favorites}</b>\nFavorites"
    n_reshares_label.visible = @message.n_reshares != 0
    n_reshares_label.markup = "<b>#{@message.n_reshares}</b>\nReshares"
    resent_box.visible = @message.resent_by != nil
    resent_by_button.label = @message.resent_by if @message.resent_by
    if @message.sender_nick == "@GTKtoolkit"
      avatar_image.set_from_icon_name("gtk3-demo", :dnd)
    else
      avatar_image.from_pixbuf = @avatar_pixbuf_other
    end
  end

  def sort(b)
    @message.time - b.message.time
  end

  private


  def state_flags_changed(widget, previous_flags)
    flags = widget.state_flags
    extra_button_box.visible = flags & (Gtk::StateFlag::PRELIGHT | Gtk::StateFlag::SELECTED)
    state_flags_changed(widget, previous_flags)
  end

  def row_expand
    expand = !details_revealer.reveal_child
    details_revealer.reveal_child = !expand
    expand ? expand_button.label = "Hide" : expand_button.label = "Expand"
  end
end

**Comment by kou** [comment]
No problem!
