### ISSUE TITLE
TODO: free GIArgument(void) 

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#952]
I was trying a gst sample according to the documentation (https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer/html/GstPipeline.html#gst-pipeline-get-clock):
 
```
diff --git a/gstreamer/sample/text-color-example.rb b/gstreamer/sample/text-color-example.rb
index 142dcea..d0e0cf8 100755
--- a/gstreamer/sample/text-color-example.rb
+++ b/gstreamer/sample/text-color-example.rb
@@ -32,7 +32,7 @@
 require "gst"
 
 bin = Gst::Pipeline.new("pipeline")
-clock = bin.clock
+clock = bin.pipeline_clock
 src = Gst::ElementFactory.make("videotestsrc", nil)
 raise "need videotestsrc from gst-plugins-base" if src.nil?
 src.pattern = 10 # checkers-8
```

Now I have this message:

```
ruby text-color-example.rb 
/home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.1.0/lib/gobject-introspection/loader.rb:520:in `invoke': TODO: free GIArgument(void) everything (NotImplementedError)
	from /home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.1.0/lib/gobject-introspection/loader.rb:520:in `block in define_method'
	from text-color-example.rb:80:in `<main>'
```

**Comment by kou** [comment]
I fixed it but I don't know whether the fix is correct...

**Comment by cedlemo** [comment]
@kou ,
It seems to work see #953

Thanks.
