### ISSUE TITLE
Cannot load pango.so on Windows 7

### ISSUE THREAD

**Issue by Mazwak** [ruby-gnome2/ruby-gnome2#960]
Hi

There is a problem with pango 3.1.0 on Windows 7 64.

I tried ruby 2.2.5-64, 2.3.1-32 and 2.3.1-64, all fails with this error :

```
C:/ruby/231/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- pango.so (LoadError)
```

After modifying pango.rb require, the actual error is :

```
C:/ruby/231/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require': 127: The specified procedure could not be found.   - C:/ruby/231/lib/ruby/gems/2.3.0/gems/pango-3.1.0-x64-mingw32/lib/2.3/pango.so (LoadError)
```

I cannot reproduce the error on Fedora 24.

**Comment by Mazwak** [comment]
After some fiddling with dependency walker, the only thing strange is 2 functions missing in libfontconfig-1.dll :
FcWeightFromOpenType
FcWeightToOpenType

They were added in 2.11.91, and rcairo, as of now, uses 2.11.1 on windows. Rebuilding rcairo windows gem with latest patch, notably https://github.com/rcairo/rcairo/commit/8017181a188c737fd57b2b6c101b17bcf070a3b0 should fix this issue.

**Comment by kou** [comment]
Could you update cairo gem and try again?

**Comment by Mazwak** [comment]
It works with rcairo 1.15.3. Tested 2.3.1-64, 2.3.1-32 and 2.2.5-64.

**Comment by andymeneely** [comment]
I can confirm that upgrade works for Windows 10 (ruby 2.3.1p112 (2016-04-26 revision 54768) [x64-mingw32]). 3.1.0 does not work unless rcairo is at 1.15.3.

Thank you @kou!!

**Comment by kou** [comment]
Thanks for confirming!

**Comment by jjgh** [comment]
On Windows 7 64: 

```
> ruby -v

Ruby 2.3.3p222 (2016-11-21 revision 56859) [x64-mingw32] 

> gem install gtk3

Fetching: pkg-config-1.2.0.gem (100%)
Successfully installed pkg-config-1.2.0
Fetching: native-package-installer-1.0.0.gem (100%)
Successfully installed native-package-installer-1.0.0
Fetching: cairo-1.15.6-x64-mingw32.gem (100%)
Successfully installed cairo-1.15.6-x64-mingw32
Fetching: glib2-3.1.3-x64-mingw32.gem (100%)
Successfully installed glib2-3.1.3-x64-mingw32
Fetching: gobject-introspection-3.1.3-x64-mingw32.gem (100%)
Successfully installed gobject-introspection-3.1.3-x64-mingw32
Fetching: gio2-3.1.3-x64-mingw32.gem (100%)
Successfully installed gio2-3.1.3-x64-mingw32
Fetching: atk-3.1.3-x64-mingw32.gem (100%)
Successfully installed atk-3.1.3-x64-mingw32
Fetching: cairo-gobject-3.1.3-x64-mingw32.gem (100%)
Successfully installed cairo-gobject-3.1.3-x64-mingw32
Fetching: pango-3.1.3-x64-mingw32.gem (100%)
Successfully installed pango-3.1.3-x64-mingw32
Fetching: gdk_pixbuf2-3.1.3-x64-mingw32.gem (100%)
Successfully installed gdk_pixbuf2-3.1.3-x64-mingw32
Fetching: gdk3-3.1.3-x64-mingw32.gem (100%)
Successfully installed gdk3-3.1.3-x64-mingw32
Fetching: rsvg2-3.1.3-x64-mingw32.gem (100%)
Successfully installed rsvg2-3.1.3-x64-mingw32
Fetching: gtk3-3.1.3-x64-mingw32.gem (100%)
Successfully installed gtk3-3.1.3-x64-mingw32
13 gems installed

> ruby ruby-gnome-example.rb

C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- cairo.so (LoadError)
        from C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cairo-1.15.6-x64-mingw32/lib/cairo.rb:48:in `rescue in <top (required)>'
        from C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cairo-1.15.6-x64-mingw32/lib/cairo.rb:44:in `<top (required)>'
        from C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/glib2-3.1.3-x64-mingw32/lib/glib2.rb:112:in `<top (required)>'
        from C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.1.3-x64-mingw32/lib/gobject-introspection.rb:17:in `<top (required)>'
        from C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gtk3-3.1.3-x64-mingw32/lib/gtk3.rb:17:in `<top (required)>'
        from C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from ruby-gnome-example.rb:1:in `<main>'
```
