### ISSUE TITLE
ruby-gtk3: Debug info printed when clicking on already selected radio button

### ISSUE THREAD

**Issue by PeterWAWood** [ruby-gnome2/ruby-gnome2#981]
When  I click on an already selected radio button, a set of "GdkPixbuf-DEBUG **" messages are printed in the console.

This script demonstrates the issue: 
```ruby
require 'gtk3'

# main window
win = Gtk::Window.new
win.set_title 'Radio Button Debug Warning'
win.set_border_width 10
win.signal_connect('destroy') { Gtk.main_quit }

# hbox for buttons
hbox = Gtk::Box.new :horizontal, 3

# add three radio buttons to hbox
button1 = Gtk::RadioButton.new label: 'Button 1'
button1.signal_connect('toggled') { puts 'Button 1 toggled' }
hbox.pack_start button1, expand: false, fill: false, padding: 0

button2 = Gtk::RadioButton.new label: 'Button 2', member: button1
button2.signal_connect('toggled') { puts 'Button 2 toggled' }
hbox.pack_start button2, expand: false, fill: false, padding: 0

button3 = Gtk::RadioButton.new label: 'Button 3', member: button1
button3.signal_connect('toggled') { puts 'Button 3 toggled' }
hbox.pack_start button3, expand: false, fill: false, padding: 0

# add hbox to window
win.add hbox

# display window and start
win.show_all
Gtk.main
```

This is the output from the Ruby console session:

```text
Button 3 toggled
Button 1 toggled
Button 1 toggled
Button 2 toggled
Button 2 toggled
Button 3 toggled
Button 3 toggled
Button 2 toggled
GdkPixbuf-DEBUG **: gdk_pixbuf_from_pixdata() called on:
	from /usr/local/lib/ruby/gems/2.4.0/gems/gobject-introspection-3.1.0/lib/gobject-introspection/loader.rb:107:in `block in define_singleton_method'
	from ./radio_button.rb:32:in `<main>'
GdkPixbuf-DEBUG **: 	Encoding raw
	from /usr/local/lib/ruby/gems/2.4.0/gems/gobject-introspection-3.1.0/lib/gobject-introspection/loader.rb:107:in `block in define_singleton_method'
	from ./radio_button.rb:32:in `<main>'
GdkPixbuf-DEBUG **: 	Dimensions: 14 x 14
	from /usr/local/lib/ruby/gems/2.4.0/gems/gobject-introspection-3.1.0/lib/gobject-introspection/loader.rb:107:in `block in define_singleton_method'
	from ./radio_button.rb:32:in `<main>'
GdkPixbuf-DEBUG **: 	Rowstride: 56, Length: 808
	from /usr/local/lib/ruby/gems/2.4.0/gems/gobject-introspection-3.1.0/lib/gobject-introspection/loader.rb:107:in `block in define_singleton_method'
	from ./radio_button.rb:32:in `<main>'
GdkPixbuf-DEBUG **: 	Copy pixels == false
	from /usr/local/lib/ruby/gems/2.4.0/gems/gobject-introspection-3.1.0/lib/gobject-introspection/loader.rb:107:in `block in define_singleton_method'
	from ./radio_button.rb:32:in `<main>'

```

ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
gtk3 (3.1.0)
macOS 10.12.2

**Comment by kou** [comment]
Debug level logs should not be reported by default.
I've changed the default log level. "message", "info" and "debug" log levels aren't reported by default. You can enable "message" and "info" by `$VERBOSE = true` or `$DEBUG = true`. You can enable all of them by `$DEBUG = true`.
