### ISSUE TITLE
3.1.1: gio2 TestSettings::.new fail with missing gschemas.compiled

### ISSUE THREAD

**Issue by mtasaka** [ruby-gnome2/ruby-gnome2#990]
With 3.1.1, ``$ ruby run-test.rb`` fails on gio2 like:
```
..........................E
===============================================================================
Error: test: full(TestSettings::.new): GLib::FileError: Failed to open file “/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gio2/test/fixture/schema/gschemas.compiled”: open() failed: そのようなファイルやディレクトリはありません
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:296:in `invoke'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:296:in `block (2 levels) in load_constructor_infos'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:307:in `block in load_constructor_infos'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gio2/test/test-settings.rb:111:in `new'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gio2/test/test-settings.rb:111:in `block (2 levels) in <class:TestSettings>'
===============================================================================
```

Looks like schemas directory is wrong? 
```
$ find . -name gschemas.compiled
./gio2/test/fixture/schema/settings/gschemas.compiled
./gio2/test/fixture/schema/default/gschemas.compiled
./gio2/test/fixture/schema/source/gschemas.compiled
```

**Comment by kou** [comment]
Thanks for your report.
Maybe, I've fixed it.

**Comment by mtasaka** [comment]
Confirmed fixed, thank you!
