### ISSUE TITLE
Error when using the method Gdk::Event#motion.

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#992]
@kou,

I am working on the event_axes.c demo. I have the following : 
An event box which catch a lot of events. In the block used when a "event" signal is send, there is the function `update_axes_event(event)` which crash when I try `event.motion` with the following message:

```
/home/cedlemo/.gem/ruby/2.4.0/gems/gobject-introspection-3.1.2/lib/gobject-introspection/loader.rb:248:in `get_field_value': failed to get field value: motion[interface]
	 from /home/cedlemo/.gem/ruby/2.4.0/gems/gobject-introspection-3.1.2/lib/gobject-introspection/loader.rb:248:in `block in load_field'
	 from /home/cedlemo/Projets/Ruby/ruby-gnome2/gtk3/sample/gtk-demo/event_axes.rb:299:in `update_axes_from_event'
	 from /home/cedlemo/Projets/Ruby/ruby-gnome2/gtk3/sample/gtk-demo/event_axes.rb:65:in `block in initialize'
	 from /home/cedlemo/.gem/ruby/2.4.0/gems/gobject-introspection-3.1.2/lib/gobject-introspection/loader.rb:530:in `invoke'
	 from /home/cedlemo/.gem/ruby/2.4.0/gems/gobject-introspection-3.1.2/lib/gobject-introspection/loader.rb:530:in `block in define_method'
	 from ./main.rb:501:in `<main>'
```

Here is the interesting part of the ruby code : 

```ruby

    box = Gtk::EventBox.new
    @window.add(box)
    box.support_multidevice = true
    box.add_events([:pointer_motion_mask, :button_press_mask,
                   :button_release_mask, :smooth_scroll_mask,
                   :enter_notify_mask, :leave_notify_mask,
                   :touch_mask])

    @event_data = EventData.new({}, {})

    box.signal_connect "event" do |widget, event|
      update_axes_from_event(event)
      widget.queue_draw
      false
    end
```

Tell me if you want to see the full script.

**Comment by kou** [comment]
> Tell me if you want to see the full script.

Please!

**Comment by cedlemo** [comment]
```ruby
class EventAxesDemo
  AxesInfo = Struct.new(:last_source,
                        :last_tool,
                        :axes,
                        :color,
                        :x,
                        :y)

  EventData = Struct.new(:pointer_info, :touch_info)

  Colors = %w(black orchid fuchsia indigo thistle sienna azure plum
              lime navy maroon burlywood)
  PadActionResults = %w(☢ ♨ ☼ ☄ ⚡ 💫 ◑ ⚛)

  def initialize(main_window)
    @cur_color = 0
    @window = Gtk::Window.new(:toplevel)
    @window.screen = main_window.screen
    @window.title = "Event Axes"
    @window.set_default_size(400, 400)

    box = Gtk::EventBox.new
    @window.add(box)
    box.support_multidevice = true
    box.add_events([:pointer_motion_mask, :button_press_mask,
                   :button_release_mask, :smooth_scroll_mask,
                   :enter_notify_mask, :leave_notify_mask,
                   :touch_mask])

    @event_data = EventData.new({}, {})

    box.signal_connect "event" do |widget, event|
      update_axes_from_event(event)
      widget.queue_draw
      false
    end

    box.signal_connect "draw" do |widget, cr|
      y = 0
      # draw_cb
      allocation = widget.allocation

      # Draw Abs info
      @event_data.pointer_info.each do |key, value|
        draw_axes_info(cr, value, allocation)
      end

      @event_data.touch_info.each do |key, value|
        draw_axes_info(cr, value, allocation)
      end

      # Draw name, color legend and misc data
      @event_data.pointer_info.each do |key, value|
        y = draw_device_info(widget, cr, nil, y, value)
      end

      @event_data.pointer_info.each do |key, value|
        y = draw_device_info(widget, cr, key, y, value)
      end

      false
    end

    @label = Gtk::Label.new("")
    @label.use_markup = true
    box.add(@label)
    # init_pad_controller
  end

  def run
    if !@window.visible?
      @window.show_all
    else
      @window.destroy
    end
    @window
  end

  private

  def init_pad_controller
    @window
    @label
  end

  def draw_axes_info(cr, info, allocation)
    axes = info.last_resource.axes
    cr.save
    cr.set_line_width(1)
    cr.set_source_rgba(info.color)
    cr.move_to(0, info.y)
    cr.line_to(allocation.width, info.y)
    cr.move_to(info.x, 0)
    cr.line_to(info.x, allocation.height)
    cr.stroke

    cr.translate(info.x, info.y)

    if info.axes.nil?
      cr.restore
      return
    end

    if axes & Gdk::AxisFlag::XTILT && axes & Gdk::AxisFlag::YTILT
      tiltx = info.last_source.get_axis(info.axes, :axis_xtilt)
      tilty = info.last_source.get_axis(info.axes, :axis_ytilt)

      render_arrow(cr, tiltx * 100, tilty * 100, "Tilt")
    end

    if axes & Gdk::AxisFlag::DISTANCE
      distance = info.last_source.get_axis(info.axes, :axis_distance)

      cr.save
      cr.move_to(distance * 100, 0)
      cr.set_source_rgb(0.0, 0.0, 0.0)
      cr.set_dash([5.0, 5.0], 2, 0.0)
      cr.arc(0, 0, distance * 100, 0, 2 * Math::PI)
      cr.stroke

      cr.move_to(0, -distance * 100)
      extents = cr.text_extents("Distance")
      cr.rel_move_to(-extents.width / 2, 0)
      cr.show_text("Distance")

      cr.move_to(cr, 0, 0)

      cr.restore
    end

    if axes & Gdk::AxisFlag::WHEEL
      wheel = info.last_source.get_axis(info.axes, :axis_wheel)
      cr.save
      cr.set_line_width(10)
      cr.set_source_rgba(0, 0, 0, 0.5)

      cr.new_sub_path
      cr.arc(0, 0, 100, 0, wheel * 2 * Math::PI)
      cr.stroke
      cr.restore
    end

    if axes & Gdk::AxisFlag::ROTATION
      rotation = info.last_source.get_axis(info.axes, :axis_rotation)
      rotation *= (2 * Math::PI)

      cr.save
      cr.rotate( -1 * (Math::PI / 2))
      cr.set_line_cap(Cairo::LINE_CAP_ROUND)
      cr.set_line_width(5)

      cr.new_sub_path
      cr.arc(0, 0, 100, 0, rotation)
      cr.stroke
      cr.restore
    end

    if axes & Gdk::AxisFlag::SLIDER
      slider = info.last_source.get_axis(info.axes, :axis_slider)

      cr.save
      cr.movet_to(0, -10)
      cr.rel_line_to(0, -50)
      cr.rel_line_to(10, 0)
      cr.rel_line_to(-5, 50)
      cr.close_path

      cr.clip_preserve

      pattern = Cairo::LinearPattern.new(0, -10, 0, -60)
      pattern.add_color_stop_rgb(0, 0, 1, 0)
      pattern.add_color_stop_rgb(1, 1, 0, 0)
      cr.set_source(pattern)

      mask = Cairo::LinearPattern.new(0, -10, 0, -60)
      mask.add_color_stop_rgba(0, 0, 0, 0, 1)
      mask.add_color_stop_rgba(slider, 0, 0, 0, 1)
      mask.add_color_stop_rgba(slider, 0, 0, 0, 0)
      mask.add_color_stop_rgba(1, 0, 0, 0, 0)
      cr.mask = mask

      cr.set_source_rgb(0, 0, 0)
      cr.stroke

      cr.restore
    end

    cr.restore
  end

  def draw_device_info(widget, cr, sequence, y, info)
    cr.save
    str = "Source: #{info.last_source.name}"

    str += "\nSequence: #{sequence}" if sequence

    if info.last_tool
      tool_type = tool_type_to_string(info.last_tool.tool_type)
      serial = info.last_tool.serial
      str += "\Tool: #{tool_type}"
      str += ", Serial: #{serial.to_s(16)}" if serial != 0
    end

    cr.move_to(10, y)
    layout = widget.create_pango_layout(str)
    cr.show_pango_layout(layout)
    cr.stroke

    _, h = layout.pixel_size
    cr.set_source_rgba(info.color)
    cr.set_line_width(10)
    cr.move_to(0, y)
    y += h
    cr.line_to(0, y)
    cr.stroke

    cr.restore

    y
  end

  def update_axes_from_event(event)
    device = event.device
    source_device = event.source_device
    sequence = event.event_sequence
    tool = event.device_tool

    if event.type == :touch_end || event.type == :touch_cancel
      @event_data.touch_info.delete(sequence)
      return
    elsif event.type == :leave_notify
      @event_data.pointer_info.delete(device)
      return
    end

    info = nil

    if sequence.nil?
      info = @event_data.pointer_info[device]

      unless info
        info = AxesInfo.new
        info.color = Gdk::RGBA.parse(Colors[@cur_color])
        @cur_color = (@cur_color + 1) % Colors.size

        @event_data.pointer_info[device] = info
      end
    else
      info = @event_data.touch_info[sequence]

      unless info
        info = AxesInfo.new
        info.color = Gdk::RGBA.parse(Colors[@cur_color])
        @cur_color = (@cur_color + 1) % Colors.size
        @event_data.touch_info[sequence] = info
      end
    end

    info.last_source = source_device if info.last_source != source_device
    info.last_tool = tool if info.last_tool != tool

    if event.type == :touch_begin || event.type == :touch_update
      @event_data.pointer_info.delete(device) if (sequence && event.touch.emulating_pointer)
    end

    if event.type == :motion_notify
      puts "tototche"
      @event_data.axes = event.motion.axes[0..source_device.n_axes]
    elsif event.type == :button_press || event.type == :button_release
      @event_data.axes = event.button.axes[0..source_device.n_axes]
    end

    x, y = event.coords
    info.x = x
    info.y = y
  end

  def tool_type_to_string(tool_type)
    case tool_type
    when Gdk::DeviceToolType::PEN
       "Pen"
    when Gdk::DeviceToolType::ERASER
       "Eraser"
    when Gdk::DeviceToolType::BRUSH
       "Brush"
    when Gdk::DeviceToolType::PENCIL
       "Pencil"
    when Gdk::DeviceToolType::AIRBRUSH
       "Airbrush"
    when Gdk::DeviceToolType::MOUSE
       "Mouse"
    when Gdk::DeviceToolType::LENS
       "Lens cursor"
    else
       "Unknown"
    end
  end
end

```

**Comment by kou** [comment]
You don't need `.motion` in `event.motion`. `event` itself is `Gdk::EventMotion`.

**Comment by kou** [comment]
`event.axes` is broken because GObject Introspection information by GDK doesn't provide enough information...
`event.axes` is an array of `gdouble` but GObject Introspection information by GDK just says `gdouble`. So we treat `event.axes` as `Float` not `Array` of `Float`...

We should report it to GTK+ developers.

**Comment by kou** [comment]
It seems that PyGTK doesn't use GI information. It writes the binding by hand...: https://github.com/GNOME/pygtk/blob/master/gtk/gdkevent.override#L514-L521

**Comment by cedlemo** [comment]
@kou, if I well understood, in the Gdk-3.0.gir:6510

```xml
    <record name="EventMotion" c:type="GdkEventMotion">
      <doc xml:space="preserve">Generated when the pointer moves.</doc>
      <field name="type" writable="1">
        <doc xml:space="preserve">the type of the event.</doc>
        <type name="EventType" c:type="GdkEventType"/>
      </field>
      <field name="window" writable="1">
        <doc xml:space="preserve">the window which received the event.</doc>
        <type name="Window" c:type="GdkWindow*"/>
      </field>
      <field name="send_event" writable="1">
        <doc xml:space="preserve">%TRUE if the event was sent explicitly.</doc>
        <type name="gint8" c:type="gint8"/>
      </field>
      <field name="time" writable="1">
        <doc xml:space="preserve">the time of the event in milliseconds.</doc>
        <type name="guint32" c:type="guint32"/>
      </field>
      <field name="x" writable="1">
        <doc xml:space="preserve">the x coordinate of the pointer relative to the window.</doc>
        <type name="gdouble" c:type="gdouble"/>
      </field>
      <field name="y" writable="1">
        <doc xml:space="preserve">the y coordinate of the pointer relative to the window.</doc>
        <type name="gdouble" c:type="gdouble"/>
      </field>
      <field name="axes" writable="1">
        <doc xml:space="preserve">@x, @y translated to the axes of @device, or %NULL if @device is
  the mouse.</doc>
        <type name="gdouble" c:type="gdouble*"/>
      </field>
```

the type declaration should be something like : 

    <array c:type="gdouble*">
      <type> </type>
    </array>

**Comment by kou** [comment]
Yes! You well understood.

We may be able to change `axes`'s type by annotation such as: 

```diff
diff --git a/gdk/gdkevents.h b/gdk/gdkevents.h
index e7ebcc2eeb..6ada21e7b1 100644
--- a/gdk/gdkevents.h
+++ b/gdk/gdkevents.h
@@ -641,7 +641,7 @@ struct _GdkEventVisibility
  * @time: the time of the event in milliseconds.
  * @x: the x coordinate of the pointer relative to the window.
  * @y: the y coordinate of the pointer relative to the window.
- * @axes: @x, @y translated to the axes of @device, or %NULL if @device is
+ * @axes: (array): @x, @y translated to the axes of @device, or %NULL if @device is
  *   the mouse.
  * @state: (type GdkModifierType): a bit-mask representing the state of
  *   the modifier keys (e.g. Control, Shift and Alt) and the pointer
```

It generates the following `Gdk-3.0.gir`:

```xml
      <field name="axes" writable="1">
        <doc xml:space="preserve">@x, @y translated to the axes of @device, or %NULL if @device is
  the mouse.</doc>
        <array zero-terminated="0" c:type="gdouble*">
          <type name="gdouble" c:type="gdouble"/>
        </array>
      </field>
```

But the GObject Introspection information doesn't have array length. If we don't have array length information, we can't convert `axes` to Ruby's `Array`.

I think that we should report the case to GTK+ developers.

**Comment by cedlemo** [comment]
I have a bugzilla account so I will report it. I have some questions @kou on how you deal with the gnome source code in order to test ruby-gnome.

For example I am working on a patch for an application of the gnome project and I build, modify and test with the jhbuild environment. Do you use it too in order to test some patch with ruby-GNOME2 ?
Or do you use another way ?

**Comment by kou** [comment]
> I have a bugzilla account so I will report it.

Thanks!!!

I'm not using jhbuild. I'm using `./configure --prefix=/tmp/local && make && make install` against `git pull`-ed source.

**Comment by cedlemo** [comment]
Is it possible to build the ruby GNOME2 gems so that it load the libs I have modified/patched and built ? You know for example if I wanted to modify the Gdk libs (source or gir files) and to test them with ruby-GNOME2 (instead of my system libs).

**Comment by kou** [comment]
Yes. `LD_LIBRARY_PATH` and `GI_TYPELIB_PATH` environment variables will help you.

I'm using the following:

```text
% LD_LIBRARY_PATH=/tmp/local/lib GI_TYPELIB_PATH=/tmp/local/lib/girepository-1.0 ruby ...
```

The above command line is for GDK configured with `--prefix=/tmp/local`.

**Comment by cedlemo** [comment]
here is the link to the bug : https://bugzilla.gnome.org/show_bug.cgi?id=778141

**Comment by cedlemo** [comment]
@kou,

It seems that we should not access directly the axes field of the GdkEvent structure but we should work with `gdk_event_get_axis()` (https://developer.gnome.org/gdk3/stable/gdk3-Events.html#gdk-event-get-axis).

This method use as argument a `GdkAtom` that we can get with `gdk_device_list_axes` (https://developer.gnome.org/gdk3/stable/GdkDevice.html#gdk-device-list-axes) which is a function that is not wrapped by the Gdk gem.

**Comment by kou** [comment]
Oh, I was wrong. We should use functions. I've fixed.
Thanks for discussing with GTK+ developers!

**Comment by cedlemo** [comment]
Ok thanks.
