### ISSUE TITLE
Unable to run the tests with ruby 2.4

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#996]
@kou, 

I am working on the module atk based on GObject-Introspection and I have found this error when I run the tests : 

```bash
./run-test.rb
/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require': /home/cedlemo/Projets/Ruby/ruby-gnome2/glib2/ext/glib2/glib2.so: undefined symbol: rb_cFixnum - /home/cedlemo/Projets/Ruby/ruby-gnome2/glib2/ext/glib2/glib2.so (LoadError)
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /home/cedlemo/Projets/Ruby/ruby-gnome2/glib2/lib/glib2.rb:120:in `rescue in <top (required)>'
	from /home/cedlemo/Projets/Ruby/ruby-gnome2/glib2/lib/glib2.rb:116:in `<top (required)>'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/cedlemo/Projets/Ruby/ruby-gnome2/gobject-introspection/lib/gobject-introspection.rb:17:in `<top (required)>'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/cedlemo/Projets/Ruby/ruby-gnome2/atk/lib/atk.rb:17:in `<top (required)>'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./run-test.rb:48:in `<main>'
```

I have the same errors with the tests with gdk_pixbuf2. The gems can be built and installed without problems. It looks like it is related to `rb_cFixnum` and the ruby version 2.4.

**Comment by kou** [comment]
What Ruby did you use to run `extconf.rb` for `/home/cedlemo/Projets/Ruby/ruby-gnome2/glib2/`? Did you use Ruby 2.4?

**Comment by cedlemo** [comment]
> What Ruby did you use to run extconf.rb for /home/cedlemo/Projets/Ruby/ruby-gnome2/glib2/? Did you use Ruby 2.4?

I just have just re-used the main extconf.rb with the ruby 2.4 and not the GLib extconf.rb. I will try it.

**Comment by cedlemo** [comment]
Nope, still the same kind of error : 

```bash
./run-test.rb
/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require': /home/cedlemo/Projets/Ruby/ruby-gnome2/glib2/ext/glib2/glib2.so: undefined symbol: rb_cFixnum - /home/cedlemo/Projets/Ruby/ruby-gnome2/glib2/ext/glib2/glib2.so (LoadError)
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /home/cedlemo/Projets/Ruby/ruby-gnome2/glib2/lib/glib2.rb:120:in `rescue in <top (required)>'
	from /home/cedlemo/Projets/Ruby/ruby-gnome2/glib2/lib/glib2.rb:116:in `<top (required)>'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./run-test.rb:35:in `<main>'
```

**Comment by kou** [comment]
Please show `/home/cedlemo/Projets/Ruby/ruby-gnome2/glib2/ext/glib2/Makefile`.

**Comment by cedlemo** [comment]
```bash

SHELL = /bin/sh

# V=0 quiet, V=1 verbose.  other values don't work.
V = 0
Q1 = $(V:1=)
Q = $(Q1:0=@)
ECHO1 = $(V:1=@ :)
ECHO = $(ECHO1:0=@ echo)
NULLCMD = :

#### Start of system configuration section. ####

srcdir = /home/cedlemo/Projets/Ruby/ruby-gnome2/glib2/ext/glib2
topdir = /usr/include/ruby-2.4.0
hdrdir = $(topdir)
arch_hdrdir = /usr/include/ruby-2.4.0/x86_64-linux
PATH_SEPARATOR = :
VPATH = $(srcdir):$(arch_hdrdir)/ruby:$(hdrdir)/ruby
prefix = $(DESTDIR)/usr
rubysitearchprefix = $(rubylibprefix)/$(sitearch)
rubyarchprefix = $(rubylibprefix)/$(arch)
rubylibprefix = $(libdir)/$(RUBY_BASE_NAME)
exec_prefix = $(prefix)
vendorarchhdrdir = $(vendorhdrdir)/$(sitearch)
sitearchhdrdir = $(sitehdrdir)/$(sitearch)
rubyarchhdrdir = $(rubyhdrdir)/$(arch)
vendorhdrdir = $(rubyhdrdir)/vendor_ruby
sitehdrdir = $(rubyhdrdir)/site_ruby
rubyhdrdir = $(includedir)/$(RUBY_VERSION_NAME)
vendorarchdir = $(vendorlibdir)/$(sitearch)
vendorlibdir = $(vendordir)/$(ruby_version)
vendordir = $(rubylibprefix)/vendor_ruby
sitearchdir = $(sitelibdir)/$(sitearch)
sitelibdir = $(sitedir)/$(ruby_version)
sitedir = $(rubylibprefix)/site_ruby
rubyarchdir = $(rubylibdir)/$(arch)
rubylibdir = $(rubylibprefix)/$(ruby_version)
sitearchincludedir = $(includedir)/$(sitearch)
archincludedir = $(includedir)/$(arch)
sitearchlibdir = $(libdir)/$(sitearch)
archlibdir = $(libdir)/$(arch)
ridir = $(datarootdir)/$(RI_BASE_NAME)
mandir = $(datarootdir)/man
localedir = $(datarootdir)/locale
libdir = $(exec_prefix)/lib
psdir = $(docdir)
pdfdir = $(docdir)
dvidir = $(docdir)
htmldir = $(docdir)
infodir = $(datarootdir)/info
docdir = $(datarootdir)/doc/$(PACKAGE)
oldincludedir = $(DESTDIR)/usr/include
includedir = $(prefix)/include
localstatedir = $(DESTDIR)/var
sharedstatedir = $(DESTDIR)/var/lib
sysconfdir = $(DESTDIR)/etc
datadir = $(datarootdir)
datarootdir = $(prefix)/share
libexecdir = $(DESTDIR)/usr/lib/ruby
sbindir = $(exec_prefix)/sbin
bindir = $(exec_prefix)/bin
archdir = $(rubyarchdir)


CC = gcc
CXX = g++
LIBRUBY = $(LIBRUBY_SO)
LIBRUBY_A = lib$(RUBY_SO_NAME)-static.a
LIBRUBYARG_SHARED = -l$(RUBY_SO_NAME)
LIBRUBYARG_STATIC = -l$(RUBY_SO_NAME)-static
empty =
OUTFLAG = -o $(empty)
COUTFLAG = -o $(empty)
CSRCFLAG = $(empty)

RUBY_EXTCONF_H = 
cflags   = $(optflags) $(debugflags) $(warnflags)
cxxflags = $(optflags) $(debugflags) $(warnflags)
optflags = -O3 -fno-fast-math
debugflags = -ggdb3
warnflags = -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wno-tautological-compare -Wno-parentheses-equality -Wno-constant-logical-operand -Wno-self-assign -Wunused-variable -Wimplicit-int -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat -Wsuggest-attribute=noreturn -Wsuggest-attribute=format -Wno-maybe-uninitialized
CCDLFLAGS = -fPIC
CFLAGS   = $(CCDLFLAGS) -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fPIC -Wall -Waggregate-return -Wcast-align -Wformat=2 -Winit-self -Wlarger-than-65500 -Wmissing-declarations -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wpacked -Wp,-D_FORTIFY_SOURCE=2 -Wpointer-arith -Wswitch-default -Wswitch-enum -Wundef -Wunsafe-loop-optimizations -Wwrite-strings -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -pthread -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include $(ARCH_FLAG)
INCFLAGS = -I. -I$(arch_hdrdir) -I$(hdrdir)/ruby/backward -I$(hdrdir) -I$(srcdir) -I$(vendorarchdir) 
DEFS     = 
CPPFLAGS = -DHAVE_UNISTD_H -DHAVE_G_SPAWN_CLOSE_PID -DHAVE_G_THREAD_INIT -DHAVE_G_MAIN_DEPTH -DHAVE_G_LISTENV -DHAVE_RB_CHECK_ARRAY_TYPE -DHAVE_RB_CHECK_HASH_TYPE -DHAVE_RB_EXEC_RECURSIVE -DHAVE_RB_ERRINFO -DHAVE_RB_THREAD_CALL_WITHOUT_GVL -DHAVE_RUBY_NATIVE_THREAD_P -DHAVE_RB_THREAD_CALL_WITH_GVL -DHAVE_RB_GC_REGISTER_MARK_OBJECT -DHAVE_RB_EXC_NEW_STR -DRUBY_GLIB2_COMPILATION -D_FORTIFY_SOURCE=2 $(DEFS) $(cppflags)
CXXFLAGS = $(CCDLFLAGS) -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong $(ARCH_FLAG)
ldflags  = -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic  -pthread
dldflags = -Wl,-O1,--sort-common,--as-needed,-z,relro -Wl,--compress-debug-sections=zlib 
ARCH_FLAG = 
DLDFLAGS = $(ldflags) $(dldflags) $(ARCH_FLAG)
LDSHARED = $(CC) -shared
LDSHAREDXX = $(CXX) -shared
AR = ar
EXEEXT = 

RUBY_INSTALL_NAME = $(RUBY_BASE_NAME)
RUBY_SO_NAME = ruby
RUBYW_INSTALL_NAME = 
RUBY_VERSION_NAME = $(RUBY_BASE_NAME)-$(ruby_version)
RUBYW_BASE_NAME = rubyw
RUBY_BASE_NAME = ruby

arch = x86_64-linux
sitearch = $(arch)
ruby_version = 2.4.0
ruby = $(bindir)/$(RUBY_BASE_NAME)
RUBY = $(ruby)
ruby_headers = $(hdrdir)/ruby.h $(hdrdir)/ruby/backward.h $(hdrdir)/ruby/ruby.h $(hdrdir)/ruby/defines.h $(hdrdir)/ruby/missing.h $(hdrdir)/ruby/intern.h $(hdrdir)/ruby/st.h $(hdrdir)/ruby/subst.h $(arch_hdrdir)/ruby/config.h

RM = rm -f
RM_RF = $(RUBY) -run -e rm -- -rf
RMDIRS = rmdir --ignore-fail-on-non-empty -p
MAKEDIRS = /usr/bin/mkdir -p
INSTALL = /usr/bin/install -c
INSTALL_PROG = $(INSTALL) -m 0755
INSTALL_DATA = $(INSTALL) -m 644
COPY = cp
TOUCH = exit >

#### End of system configuration section. ####

preload = 
libpath = . $(libdir)
LIBPATH =  -L. -L$(libdir)
DEFFILE = 

CLEANFILES = mkmf.log
DISTCLEANFILES = ruby-glib2.pc glib-enum-types.h glib-enum-types.c
DISTCLEANDIRS = 

extout = 
extout_prefix = 
target_prefix = 
LOCAL_LIBS = 
LIBS = $(LIBRUBYARG_SHARED)  -lgobject-2.0 -lglib-2.0 -lgthread-2.0 -lglib-2.0 -lpthread -lgmp -ldl -lcrypt -lm   -lc
ORIG_SRCS = glib-enum-types.c rbglib-variant-type.c rbglib-variant.c rbglib.c rbglib_bookmarkfile.c rbglib_convert.c rbglib_datetime.c rbglib_error.c rbglib_fileutils.c rbglib_gettext.c rbglib_i18n.c rbglib_int64.c rbglib_io_constants.c rbglib_iochannel.c rbglib_iochannel_win32_socket.c rbglib_iochannelerror.c rbglib_keyfile.c rbglib_maincontext.c rbglib_mainloop.c rbglib_matchinfo.c rbglib_messages.c rbglib_pollfd.c rbglib_regex.c rbglib_shell.c rbglib_shellerror.c rbglib_source.c rbglib_spawn.c rbglib_spawnerror.c rbglib_threads.c rbglib_timer.c rbglib_timezone.c rbglib_ucs4.c rbglib_unichar.c rbglib_unicode.c rbglib_utf16.c rbglib_utf8.c rbglib_utils.c rbglib_win32.c rbglibdeprecated.c rbgobj_binding.c rbgobj_boxed.c rbgobj_closure.c rbgobj_convert.c rbgobj_enumflags.c rbgobj_enums.c rbgobj_flags.c rbgobj_object.c rbgobj_param.c rbgobj_paramspecs.c rbgobj_signal.c rbgobj_strv.c rbgobj_type.c rbgobj_typeinstance.c rbgobj_typeinterface.c rbgobj_typemodule.c rbgobj_typeplugin.c rbgobj_value.c rbgobj_valuearray.c rbgobj_valuetypes.c rbgobject.c rbgutil.c rbgutil_callback.c rbgutil_list.c rbgutildeprecated.c
SRCS = $(ORIG_SRCS) rbgobj_binding.c rbgobject.c rbgobj_typeplugin.c rbglib_regex.c rbgobj_closure.c rbglib_win32.c rbglib_datetime.c rbglib_utf16.c rbglib_mainloop.c rbgutil_callback.c rbgobj_typemodule.c rbglib_spawnerror.c rbglib_utf8.c rbgobj_enumflags.c rbgobj_object.c rbglib_ucs4.c rbgutil.c rbgobj_param.c rbgobj_signal.c rbglib_matchinfo.c rbgutil_list.c rbglib_io_constants.c rbglib_unicode.c rbglib_iochannel_win32_socket.c rbglib_keyfile.c rbgobj_strv.c rbgobj_typeinterface.c rbglib_fileutils.c rbglib_i18n.c rbglib_timezone.c glib-enum-types.c rbgobj_value.c rbgobj_valuetypes.c rbglibdeprecated.c rbglib_threads.c rbgobj_type.c rbglib_timer.c rbglib_unichar.c rbgobj_typeinstance.c rbglib_shell.c rbglib-variant-type.c rbglib_maincontext.c rbgobj_enums.c rbglib_shellerror.c rbgobj_convert.c rbglib_error.c rbgutildeprecated.c rbglib_source.c rbglib_convert.c rbglib_pollfd.c rbglib-variant.c rbgobj_paramspecs.c rbglib_iochannelerror.c rbglib_messages.c rbgobj_boxed.c rbglib.c rbglib_int64.c rbglib_utils.c rbgobj_valuearray.c rbglib_bookmarkfile.c rbglib_gettext.c rbglib_iochannel.c rbgobj_flags.c rbglib_spawn.c
OBJS = rbgobj_binding.o rbgobject.o rbgobj_typeplugin.o rbglib_regex.o rbgobj_closure.o rbglib_win32.o rbglib_datetime.o rbglib_utf16.o rbglib_mainloop.o rbgutil_callback.o rbgobj_typemodule.o rbglib_spawnerror.o rbglib_utf8.o rbgobj_enumflags.o rbgobj_object.o rbglib_ucs4.o rbgutil.o rbgobj_param.o rbgobj_signal.o rbglib_matchinfo.o rbgutil_list.o rbglib_io_constants.o rbglib_unicode.o rbglib_iochannel_win32_socket.o rbglib_keyfile.o rbgobj_strv.o rbgobj_typeinterface.o rbglib_fileutils.o rbglib_i18n.o rbglib_timezone.o glib-enum-types.o rbgobj_value.o rbgobj_valuetypes.o rbglibdeprecated.o rbglib_threads.o rbgobj_type.o rbglib_timer.o rbglib_unichar.o rbgobj_typeinstance.o rbglib_shell.o rbglib-variant-type.o rbglib_maincontext.o rbgobj_enums.o rbglib_shellerror.o rbgobj_convert.o rbglib_error.o rbgutildeprecated.o rbglib_source.o rbglib_convert.o rbglib_pollfd.o rbglib-variant.o rbgobj_paramspecs.o rbglib_iochannelerror.o rbglib_messages.o rbgobj_boxed.o rbglib.o rbglib_int64.o rbglib_utils.o rbgobj_valuearray.o rbglib_bookmarkfile.o rbglib_gettext.o rbglib_iochannel.o rbgobj_flags.o rbglib_spawn.o
HDRS = $(srcdir)/rbglib.h $(srcdir)/rbgutil_list.h $(srcdir)/glib-enum-types.h $(srcdir)/rbgutil.h $(srcdir)/rbgobject.h $(srcdir)/rbgcompat.h $(srcdir)/rbgprivate.h $(srcdir)/rbgutildeprecated.h $(srcdir)/rbglibdeprecated.h $(srcdir)/rbglib2conversions.h
LOCAL_HDRS = 
TARGET = glib2
TARGET_NAME = glib2
TARGET_ENTRY = Init_$(TARGET_NAME)
DLLIB = $(TARGET).so
EXTSTATIC = 
STATIC_LIB = 

TIMESTAMP_DIR = .
BINDIR        = $(bindir)
RUBYCOMMONDIR = $(sitedir)$(target_prefix)
RUBYLIBDIR    = $(sitelibdir)$(target_prefix)
RUBYARCHDIR   = $(sitearchdir)$(target_prefix)
HDRDIR        = $(rubyhdrdir)/ruby$(target_prefix)
ARCHHDRDIR    = $(rubyhdrdir)/$(arch)/ruby$(target_prefix)
TARGET_SO_DIR =
TARGET_SO     = $(TARGET_SO_DIR)$(DLLIB)
CLEANLIBS     = $(TARGET_SO) 
CLEANOBJS     = *.o  *.bak

all:    $(DLLIB)
static: $(STATIC_LIB) install-rb
.PHONY: all install static install-so install-rb
.PHONY: clean clean-so clean-static clean-rb

clean-static::
clean-rb-default::
clean-rb::
clean-so::
clean: clean-so clean-static clean-rb-default clean-rb
		-$(Q)$(RM) $(CLEANLIBS) $(CLEANOBJS) $(CLEANFILES) .*.time

distclean-rb-default::
distclean-rb::
distclean-so::
distclean-static::
distclean: clean distclean-so distclean-static distclean-rb-default distclean-rb
		-$(Q)$(RM) Makefile $(RUBY_EXTCONF_H) conftest.* mkmf.log
		-$(Q)$(RM) core ruby$(EXEEXT) *~ $(DISTCLEANFILES)
		-$(Q)$(RMDIRS) $(DISTCLEANDIRS) 2> /dev/null || true

realclean: distclean
install: install-so install-rb

install-so: $(DLLIB) $(TIMESTAMP_DIR)/.sitearchdir.time
	$(INSTALL_PROG) $(DLLIB) $(RUBYARCHDIR)
clean-static::
	-$(Q)$(RM) $(STATIC_LIB)
install-rb: pre-install-rb do-install-rb install-rb-default
install-rb-default: pre-install-rb-default do-install-rb-default
pre-install-rb: Makefile
pre-install-rb-default: Makefile
do-install-rb:
do-install-rb-default:
pre-install-rb-default:
	@$(NULLCMD)
$(TIMESTAMP_DIR)/.sitearchdir.time:
	$(Q) $(MAKEDIRS) $(@D) $(RUBYARCHDIR)
	$(Q) $(TOUCH) $@

site-install: site-install-so site-install-rb
site-install-so: install-so
site-install-rb: install-rb

.SUFFIXES: .c .m .cc .mm .cxx .cpp .o .S

.cc.o:
	$(ECHO) compiling $(<)
	$(Q) $(CXX) $(INCFLAGS) $(CPPFLAGS) $(CXXFLAGS) $(COUTFLAG)$@ -c $(CSRCFLAG)$<

.cc.S:
	$(ECHO) translating $(<)
	$(Q) $(CXX) $(INCFLAGS) $(CPPFLAGS) $(CXXFLAGS) $(COUTFLAG)$@ -S $(CSRCFLAG)$<

.mm.o:
	$(ECHO) compiling $(<)
	$(Q) $(CXX) $(INCFLAGS) $(CPPFLAGS) $(CXXFLAGS) $(COUTFLAG)$@ -c $(CSRCFLAG)$<

.mm.S:
	$(ECHO) translating $(<)
	$(Q) $(CXX) $(INCFLAGS) $(CPPFLAGS) $(CXXFLAGS) $(COUTFLAG)$@ -S $(CSRCFLAG)$<

.cxx.o:
	$(ECHO) compiling $(<)
	$(Q) $(CXX) $(INCFLAGS) $(CPPFLAGS) $(CXXFLAGS) $(COUTFLAG)$@ -c $(CSRCFLAG)$<

.cxx.S:
	$(ECHO) translating $(<)
	$(Q) $(CXX) $(INCFLAGS) $(CPPFLAGS) $(CXXFLAGS) $(COUTFLAG)$@ -S $(CSRCFLAG)$<

.cpp.o:
	$(ECHO) compiling $(<)
	$(Q) $(CXX) $(INCFLAGS) $(CPPFLAGS) $(CXXFLAGS) $(COUTFLAG)$@ -c $(CSRCFLAG)$<

.cpp.S:
	$(ECHO) translating $(<)
	$(Q) $(CXX) $(INCFLAGS) $(CPPFLAGS) $(CXXFLAGS) $(COUTFLAG)$@ -S $(CSRCFLAG)$<

.c.o:
	$(ECHO) compiling $(<)
	$(Q) $(CC) $(INCFLAGS) $(CPPFLAGS) $(CFLAGS) $(COUTFLAG)$@ -c $(CSRCFLAG)$<

.c.S:
	$(ECHO) translating $(<)
	$(Q) $(CC) $(INCFLAGS) $(CPPFLAGS) $(CFLAGS) $(COUTFLAG)$@ -S $(CSRCFLAG)$<

.m.o:
	$(ECHO) compiling $(<)
	$(Q) $(CC) $(INCFLAGS) $(CPPFLAGS) $(CFLAGS) $(COUTFLAG)$@ -c $(CSRCFLAG)$<

.m.S:
	$(ECHO) translating $(<)
	$(Q) $(CC) $(INCFLAGS) $(CPPFLAGS) $(CFLAGS) $(COUTFLAG)$@ -S $(CSRCFLAG)$<

$(TARGET_SO): $(OBJS) Makefile
	$(ECHO) linking shared-object $(DLLIB)
	-$(Q)$(RM) $(@)
	$(Q) $(LDSHARED) -o $@ $(OBJS) $(LIBPATH) $(DLDFLAGS) $(LOCAL_LIBS) $(LIBS)



###
install-so: install-headers
install-headers:
	$(INSTALL_DATA) $(srcdir)/rbglib.h $(RUBYARCHDIR)
	$(INSTALL_DATA) $(srcdir)/rbglibdeprecated.h $(RUBYARCHDIR)
	$(INSTALL_DATA) $(srcdir)/rbglib2conversions.h $(RUBYARCHDIR)
	$(INSTALL_DATA) $(srcdir)/rbgutil.h $(RUBYARCHDIR)
	$(INSTALL_DATA) $(srcdir)/rbgutil_list.h $(RUBYARCHDIR)
	$(INSTALL_DATA) $(srcdir)/rbgutildeprecated.h $(RUBYARCHDIR)
	$(INSTALL_DATA) $(srcdir)/rbgobject.h $(RUBYARCHDIR)
	$(INSTALL_DATA) $(srcdir)/rbgcompat.h $(RUBYARCHDIR)
	$(INSTALL_DATA) glib-enum-types.h $(RUBYARCHDIR)

install: install-pc
install-pc:
	if test -n "$(pkgconfigdir)"; then			\
	  $(MAKEDIRS) $(pkgconfigdir);				\
	  $(INSTALL_DATA) ruby-glib2.pc $(pkgconfigdir);	\
	fi
```

**Comment by kou** [comment]
Thanks. There is no problem.
Could you try `make clean; make`?

**Comment by cedlemo** [comment]
I don't understand why I have not tried it before. Thank you it works.
